//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAStaticTableViewController.h"

#import "WALinkLabelDelegate-Protocol.h"
#import "WARestorable-Protocol.h"

@class NSString, UISwitch, WALinkLabel, WATableRow, WATableSection;

@interface AccountViewController : WAStaticTableViewController <WALinkLabelDelegate, WARestorable>
{
    _Bool _showShareAccountInfoSwitch;
    _Bool _shareAccountOptOutInProgress;
    UISwitch *_switchShareAccountInfo;
    WATableRow *_rowShareAccountInfo;
    WATableSection *_sectionShareAccountInfo;
    WALinkLabel *_shareAccountInfoSectionFooter;
}

- (void).cxx_destruct;
- (void)wa_applicationDidEnterBackground;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (void)setupTableView;
- (void)wa_fontSizeDidChange;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)handleOpenURL:(id)arg1 fromLinkLabel:(id)arg2;
- (void)presentTosErrorNoNetworkAlert;
- (void)presentTosErrorNotAllowedAlert;
- (void)optOutOfSharingAccountInfo;
- (void)switchAccountInfoSharingChanged:(id)arg1;
- (void)adjustFooterViewInsetsForInterfaceOrientation:(long long)arg1 reloadTableIfChange:(_Bool)arg2;
- (void)addShareAccountInfoSwitchRow;
- (void)setShouldShowShareInfoOptOutSwitch:(_Bool)arg1;
- (void)deleteAccountAction;
- (void)changeNumberAction;
- (void)show2FASettings;
- (void)showAccountSecuritySettings;
- (void)setPrivacyAction;
- (id)initWithStyle:(long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

