//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (Types)
- (id)wa_arrayForKey:(id)arg1;
- (id)wa_dictionaryForKey:(id)arg1;
- (id)wa_dataForKey:(id)arg1;
- (id)wa_stringForKey:(id)arg1;
- (id)wa_dateForKey:(id)arg1;
- (id)wa_numberForKey:(id)arg1;
- (id)wa_objectForKey:(id)arg1 ofClass:(Class)arg2;
@end

