//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate;
@protocol WADeviceDate;

@interface RecordingUserData : NSObject
{
    NSDate<WADeviceDate> *_startTime;
    struct gzFile_s *_fileHandle;
}

@property(nonatomic) struct gzFile_s *fileHandle; // @synthesize fileHandle=_fileHandle;
@property(retain, nonatomic) NSDate<WADeviceDate> *startTime; // @synthesize startTime=_startTime;
- (void).cxx_destruct;
- (id)initWithDate:(id)arg1 fileHandle:(struct gzFile_s *)arg2;

@end

