//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAChatNavigationController.h"

@interface StatusV3NavigationController : WAChatNavigationController
{
    _Bool _showUnreadIndicator;
}

@property(nonatomic) _Bool showUnreadIndicator; // @synthesize showUnreadIndicator=_showUnreadIndicator;
- (void)dismissTextStatusComposer:(id)arg1 withGestureRecognizer:(id)arg2;
- (void)presentTextStatusComposerFromView:(id)arg1 inViewController:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dismissMultiShotCameraController:(id)arg1 withGestureRecognizer:(id)arg2;
- (void)presentMultiShotCameraFromView:(id)arg1 inViewController:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)init;
- (void)reloadViewControllers;

@end

