//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIDevice.h>

@interface UIDevice (WhatsApp)
- (_Bool)wa_iPhoneX;
- (_Bool)wa_frontCameraSupportsHDCapture;
- (_Bool)wa_iPhone5OrBetter;
- (_Bool)wa_iPhone5SOrBetter;
- (_Bool)wa_iPhone6OrBetter;
- (_Bool)wa_iPhone6sOrBetter;
- (_Bool)wa_iPhone7OrBetter;
- (long long)wa_physicalMemoryInBytes;
- (_Bool)wa_hasMulticoreProcessor;
- (_Bool)wa_supports4KVideo;
- (id)modelName;
- (id)machine;
- (id)wa_systemBootDate;
- (_Bool)wa_isDeviceSupported;
- (_Bool)wa_isDeviceSuspicious;
@end

