//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WATableViewController.h"

@class NSIndexPath, NSString, UILabel, UIView, WAAutoBackupSettings;

@interface WAAutobackupSettingsViewController : WATableViewController
{
    double _cachedFooterWidth;
    WAAutoBackupSettings *_autoBackupSettings;
    UIView *_viewFooter;
    UILabel *_labelFooter;
    NSIndexPath *_selectedIndexPath;
    double _sideTextMargin;
}

+ (id)stringForSequence:(id)arg1;
+ (unsigned long long)autoBackupFrequencyForIndexPath:(id)arg1;
+ (id)indexForAutoBackupFrequency:(unsigned long long)arg1;
+ (id)disableCellularDataSequence;
@property(readonly, nonatomic) double sideTextMargin; // @synthesize sideTextMargin=_sideTextMargin;
@property(retain, nonatomic) NSIndexPath *selectedIndexPath; // @synthesize selectedIndexPath=_selectedIndexPath;
@property(retain, nonatomic) UILabel *labelFooter; // @synthesize labelFooter=_labelFooter;
@property(retain, nonatomic) UIView *viewFooter; // @synthesize viewFooter=_viewFooter;
@property(retain, nonatomic) WAAutoBackupSettings *autoBackupSettings; // @synthesize autoBackupSettings=_autoBackupSettings;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)wa_fontSizeDidChange;
- (void)viewSafeAreaInsetsDidChange;
- (void)layoutFooterView;
- (void)viewDidLoad;
@property(readonly, nonatomic) NSString *bottomText;
- (id)initWithAutoBackupSettings:(id)arg1;
- (id)init;
- (id)initWithStyle:(long long)arg1;

@end

