//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString, XMPPConnection;
@protocol OS_dispatch_queue;

@interface WABackupKeyManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableDictionary *_backupKeys;
    NSMutableDictionary *_restoreKeys;
    NSString *_name;
    XMPPConnection *_connection;
    double _maximumConnectionDelay;
}

+ (id)backupKeyErrorForCode:(long long)arg1;
+ (id)backupKeyErrorForXMPPError:(id)arg1;
+ (id)defaultManager;
- (void).cxx_destruct;
- (_Bool)removeItemsInSubdomain:(id)arg1;
- (void)resetKeysInSubdomain:(id)arg1 keyCache:(id)arg2;
- (void)resetDecryptionKeyCache;
- (void)resetAllEncryptionKeys;
- (id)baseQueryForIdentifier:(id)arg1 inSubdomain:(id)arg2;
- (_Bool)saveEntry:(id)arg1 usingIdentifier:(id)arg2 inSubdomain:(id)arg3;
- (id)loadEntryWithIdentifier:(id)arg1 inSubdomain:(id)arg2 maximumAge:(id)arg3;
- (_Bool)saveKey:(id)arg1 usingIdentifier:(id)arg2 inSubdomain:(id)arg3;
- (id)loadKeyWithIdentifier:(id)arg1 inSubdomain:(id)arg2 maximumAge:(id)arg3;
- (id)loadKeyWithIdentifier:(id)arg1 inSubdomain:(id)arg2;
- (void)registerBackupKey:(id)arg1 forWID:(id)arg2;
- (void)loadEncryptionKeyForPhoneNumber:(id)arg1 usingDispatcher:(id)arg2;
- (id)encryptionKeyDispatcherForPhoneNumber:(id)arg1;
- (void)requestEncryptionKeyForPhoneNumber:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)loadDecryptionKeyForPhoneNumber:(id)arg1 compositeKey:(id)arg2 usingIdentity:(id)arg3 onExclusiveConnection:(id)arg4 usingDispatcher:(id)arg5;
- (id)decryptionKeyForPhoneNumber:(id)arg1 usingIdentity:(id)arg2 onExclusiveConnection:(id)arg3;
- (void)requestDecryptionKeyForPhoneNumber:(id)arg1 usingIdentity:(id)arg2 onExclusiveConnection:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (id)initWithName:(id)arg1 usingConnection:(id)arg2 maximumConnectionDelay:(double)arg3;
- (id)init;
- (void)saveFileKeys:(id)arg1 forBackupIdentifier:(id)arg2;
- (id)fileKeysForBackupIdentifier:(id)arg1;
- (void)postKeysFrom:(id)arg1 error:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)requestDecryptionAccountKeysForPhoneNumber:(id)arg1 usingIdentity:(id)arg2 onExclusiveConnection:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)requestEncryptionAccountKeysForPhoneNumber:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

