//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSDate, NSString, WAPBVerifiedNameCertificate_Details;

@interface WABizVerifiedName : NSManagedObject
{
}

+ (id)insertWithJID:(id)arg1 certificateDetails:(id)arg2 verificationLevel:(int)arg3 inManagedObjectContext:(id)arg4;
- (_Bool)localizedNameMatchesText:(id)arg1 fullTextSearch:(_Bool)arg2 language:(id)arg3 locale:(id)arg4;
- (id)localizedNameForLanguage:(id)arg1 locale:(id)arg2;
- (id)localizedName;

// Remaining properties
@property(retain, nonatomic) WAPBVerifiedNameCertificate_Details *certificateDetails; // @dynamic certificateDetails;
@property(retain, nonatomic) NSDate *expires; // @dynamic expires;
@property(copy, nonatomic) NSString *jid; // @dynamic jid;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(nonatomic) int verificationLevel; // @dynamic verificationLevel;

@end

