//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface WADocumentAttachment : NSObject
{
    _Bool _ownsFile;
    NSURL *_fileURL;
    NSString *_MIMEType;
    NSString *_originalFilename;
    NSString *_name;
    unsigned long long _fileSize;
    long long _pageCount;
}

+ (id)thumbnailForMicrosoftXMLDocumentAtURL:(id)arg1 MIMEType:(id)arg2 preferredWidth:(double)arg3;
+ (id)temporaryFileURL;
+ (id)thumbnailForPDF:(struct CGPDFDocument *)arg1 preferredWidth:(double)arg2;
+ (id)thumbnailForPDFAtURL:(id)arg1 preferredWidth:(double)arg2;
+ (id)thumbnailForDocumentAtURL:(id)arg1 MIMEType:(id)arg2 preferredWidth:(double)arg3;
+ (double)preferredThumbnailWidthInPixelsForChat;
@property(readonly, nonatomic) long long pageCount; // @synthesize pageCount=_pageCount;
@property(readonly, nonatomic) unsigned long long fileSize; // @synthesize fileSize=_fileSize;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) NSString *originalFilename; // @synthesize originalFilename=_originalFilename;
@property(readonly, nonatomic) NSString *MIMEType; // @synthesize MIMEType=_MIMEType;
@property(readonly, nonatomic) NSURL *fileURL; // @synthesize fileURL=_fileURL;
- (void).cxx_destruct;
- (void)processMSFTDocXWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)processPDFWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)processWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithFileURL:(id)arg1 transferFileOwnership:(_Bool)arg2;

@end

