//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAChatStorageManagedObject.h"

#import "WAContactable-Protocol.h"

@class NSNumber, NSString, WAChatSession;

@interface WAGroupMember : WAChatStorageManagedObject <WAContactable>
{
    int _change;
    _Bool _blocked;
    NSString *_statusMessage;
}

@property(nonatomic) _Bool blocked; // @synthesize blocked=_blocked;
@property(copy, nonatomic) NSString *statusMessage; // @synthesize statusMessage=_statusMessage;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isUnknownContact) _Bool unknownContact;
- (void)awakeFromInsert;

// Remaining properties
@property(retain, nonatomic) WAChatSession *chatSession; // @dynamic chatSession;
@property(nonatomic) int contactABID; // @dynamic contactABID;
@property(copy, nonatomic) NSString *contactIdentifier; // @dynamic contactIdentifier;
@property(nonatomic) _Bool isActive; // @dynamic isActive;
@property(nonatomic) _Bool isAdmin; // @dynamic isAdmin;
@property(copy, nonatomic) NSString *memberJID; // @dynamic memberJID;
@property(retain, nonatomic) NSNumber *senderKeySent; // @dynamic senderKeySent;

@end

