//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDate, NSDateFormatter, NSFileHandle, NSPipe, NSString, NSUserDefaults;
@protocol OS_dispatch_group, OS_dispatch_io, OS_dispatch_queue;

@interface WALogWriter : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSString *_directory;
    NSDateFormatter *_filenameDateFormatter;
    unsigned long long _fileIndex;
    NSString *_launchIdentifier;
    NSUserDefaults *_userDefaults;
    long long _level;
    NSArray *_modifiers;
    NSDateFormatter *_dateFormatter;
    NSObject<OS_dispatch_io> *_standardErrorChannel;
    NSPipe *_standardErrorPipe;
    NSFileHandle *_fileHandle;
    NSDate *_creationDate;
    NSString *_activeLogFilePath;
    NSString *_previousLogFilePath;
    NSObject<OS_dispatch_group> *_groupRemoveLogs;
    CDUnknownBlockType _getFileHeader;
}

+ (id)stringFromLevel:(int)arg1;
+ (id)sharedLogger;
+ (void)prepareWithDirectory:(id)arg1 withLineModifiers:(id)arg2;
@property(copy, nonatomic) CDUnknownBlockType getFileHeader; // @synthesize getFileHeader=_getFileHeader;
- (void).cxx_destruct;
- (void)printStandardErrorLine:(id)arg1;
- (void)write:(int)arg1 truncate:(_Bool)arg2 format:(id)arg3;
- (void)write:(int)arg1 format:(id)arg2;
- (void)write:(int)arg1 truncate:(_Bool)arg2 format:(id)arg3 arguments:(char *)arg4;
- (id)formatLogText:(id)arg1 withLevel:(int)arg2;
- (_Bool)rotateLogFileIfNeeded;
- (void)rotateLogFile;
- (void)rotateLogFileWithCompletion:(CDUnknownBlockType)arg1;
- (void)openLogFile;
- (id)buildFileNameForContinuation:(_Bool)arg1;
- (void)enableBetaLogging;
- (void)getPreviousLogFilePathWithCompletion:(CDUnknownBlockType)arg1;
- (void)getActiveLogFilePathWithCompletion:(CDUnknownBlockType)arg1;
- (void)waitForPendingRequests;
- (id)currentDirectory;
- (id)initWithDirectory:(id)arg1 withLineModifiers:(id)arg2;

@end

