//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@interface WamEventLiveLocationSharingSession : WamEvent
{
    double _live_location_sharing_session_t;
    double _live_location_sharing_session_ended_reason;
}

@property(nonatomic) double live_location_sharing_session_ended_reason; // @synthesize live_location_sharing_session_ended_reason=_live_location_sharing_session_ended_reason;
@property(nonatomic) double live_location_sharing_session_t_milliseconds; // @synthesize live_location_sharing_session_t_milliseconds=_live_location_sharing_session_t;
@property(nonatomic) double live_location_sharing_session_t_seconds;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

