//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@interface WamEventReceiptsRecv : WamEvent
{
    double _receipts_proc_t;
    double _receipts_type;
    double _message_type;
}

@property(nonatomic) double message_type; // @synthesize message_type=_message_type;
@property(nonatomic) double receipts_type; // @synthesize receipts_type=_receipts_type;
@property(nonatomic) double receipts_proc_t_milliseconds; // @synthesize receipts_proc_t_milliseconds=_receipts_proc_t;
@property(nonatomic) double receipts_proc_t_seconds;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

