//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAMessageContainerSlice.h"

@interface WAMessageStickerSlice : WAMessageContainerSlice
{
    long long _messagesCount;
}

+ (Class)viewClass;
- (struct UIEdgeInsets)stickerImageViewInsets;
- (void)internalFitToWidth:(double)arg1;
- (_Bool)showsMedia;
- (void)mediaDownloadDidSucceed:(id)arg1;
- (void)dealloc;
- (id)initWithMessages:(id)arg1 metrics:(CDStruct_8ee84fd7)arg2;

@end

