//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@interface WamEventStatusPost : WamEvent
{
    double _status_session_id;
    double _media_type;
    double _retry_count;
    double _status_post_result;
    double _status_post_origin;
}

@property(nonatomic) double status_post_origin; // @synthesize status_post_origin=_status_post_origin;
@property(nonatomic) double status_post_result; // @synthesize status_post_result=_status_post_result;
@property(nonatomic) double retry_count; // @synthesize retry_count=_retry_count;
@property(nonatomic) double media_type; // @synthesize media_type=_media_type;
@property(nonatomic) double status_session_id; // @synthesize status_session_id=_status_session_id;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

