//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@interface WamEventAwayMessage : WamEvent
{
    double _away_message_state_changed_from;
    double _away_message_state_changed_to;
    double _away_message_contents_changed;
    double _away_message_contents_using_default;
    double _away_message_time_range_changed;
}

@property(nonatomic) double away_message_time_range_changed; // @synthesize away_message_time_range_changed=_away_message_time_range_changed;
@property(nonatomic) double away_message_contents_using_default; // @synthesize away_message_contents_using_default=_away_message_contents_using_default;
@property(nonatomic) double away_message_contents_changed; // @synthesize away_message_contents_changed=_away_message_contents_changed;
@property(nonatomic) double away_message_state_changed_to; // @synthesize away_message_state_changed_to=_away_message_state_changed_to;
@property(nonatomic) double away_message_state_changed_from; // @synthesize away_message_state_changed_from=_away_message_state_changed_from;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

