//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@class NSString;

@interface WamEventIphoneChatSocketConnect : WamEvent
{
    double _iphone_socket_connection_t;
    double _iphone_socket_connect_duration_t;
    double _tcp_handshake_t;
    double _dns_resolution_t;
    double _iphone_socket_connection_state_type;
    double _iphone_socket_disconnect_is_external;
    double _iphone_socket_port;
    NSString *_iphone_socket_hostname;
    NSString *_iphone_socket_ip;
    double _iphone_socket_is_http;
    double _iphone_socket_is_hint;
    double _iphone_socket_is_fallback;
    double _dns_resolution_type;
    double _dns_resolution_parallel;
}

@property(nonatomic) double dns_resolution_parallel; // @synthesize dns_resolution_parallel=_dns_resolution_parallel;
@property(nonatomic) double dns_resolution_type; // @synthesize dns_resolution_type=_dns_resolution_type;
@property(nonatomic) double iphone_socket_is_fallback; // @synthesize iphone_socket_is_fallback=_iphone_socket_is_fallback;
@property(nonatomic) double iphone_socket_is_hint; // @synthesize iphone_socket_is_hint=_iphone_socket_is_hint;
@property(nonatomic) double iphone_socket_is_http; // @synthesize iphone_socket_is_http=_iphone_socket_is_http;
@property(copy, nonatomic) NSString *iphone_socket_ip; // @synthesize iphone_socket_ip=_iphone_socket_ip;
@property(copy, nonatomic) NSString *iphone_socket_hostname; // @synthesize iphone_socket_hostname=_iphone_socket_hostname;
@property(nonatomic) double iphone_socket_port; // @synthesize iphone_socket_port=_iphone_socket_port;
@property(nonatomic) double iphone_socket_disconnect_is_external; // @synthesize iphone_socket_disconnect_is_external=_iphone_socket_disconnect_is_external;
@property(nonatomic) double iphone_socket_connection_state_type; // @synthesize iphone_socket_connection_state_type=_iphone_socket_connection_state_type;
@property(nonatomic) double dns_resolution_t_milliseconds; // @synthesize dns_resolution_t_milliseconds=_dns_resolution_t;
@property(nonatomic) double tcp_handshake_t_milliseconds; // @synthesize tcp_handshake_t_milliseconds=_tcp_handshake_t;
@property(nonatomic) double iphone_socket_connect_duration_t_milliseconds; // @synthesize iphone_socket_connect_duration_t_milliseconds=_iphone_socket_connect_duration_t;
@property(nonatomic) double iphone_socket_connection_t_milliseconds; // @synthesize iphone_socket_connection_t_milliseconds=_iphone_socket_connection_t;
- (void).cxx_destruct;
@property(nonatomic) double dns_resolution_t_seconds;
@property(nonatomic) double tcp_handshake_t_seconds;
@property(nonatomic) double iphone_socket_connect_duration_t_seconds;
@property(nonatomic) double iphone_socket_connection_t_seconds;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

