//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@class NSString;

@interface WamEventAndroidVideoStreamPlayback : WamEvent
{
    double _media_download_t;
    double _connect_t;
    double _route_selection_delay_t;
    double _network_download_t;
    double _file_validation_t;
    double _time_to_first_byte_t;
    double _time_since_download_start_t;
    double _initial_stream_buffering_t;
    double _time_since_previous_fetch_t;
    double _video_pause_t;
    double _total_rebuffering_t;
    double _media_type;
    double _media_download_result;
    double _bytes_transferred;
    double _media_used_cdn;
    NSString *_route_hostname;
    NSString *_route_ip;
    double _is_reuse;
    double _download_resume_point;
    double _mms_version;
    double _media_size;
    double _e2e_media_encryption;
    double _media_download_mode;
    double _downloaded_bytes_at_start;
    double _downloaded_bytes_at_playback;
    double _downloaded_bytes_at_finish;
    double _download_stage_at_start;
    double _download_stage_at_playback;
    double _download_stage_at_end;
    double _playback_error_count;
    double _playback_error_fatal;
    double _was_playback_ready_to_play;
    double _reached_playback_end;
    double _total_rebuffering_count;
    double _playback_state;
    double _user_playback_exit_count;
    double _video_duration;
    double _video_size;
    double _video_play_t;
    double _video_age;
}

@property(nonatomic) double video_age; // @synthesize video_age=_video_age;
@property(nonatomic) double video_play_t; // @synthesize video_play_t=_video_play_t;
@property(nonatomic) double video_size; // @synthesize video_size=_video_size;
@property(nonatomic) double video_duration; // @synthesize video_duration=_video_duration;
@property(nonatomic) double user_playback_exit_count; // @synthesize user_playback_exit_count=_user_playback_exit_count;
@property(nonatomic) double playback_state; // @synthesize playback_state=_playback_state;
@property(nonatomic) double total_rebuffering_count; // @synthesize total_rebuffering_count=_total_rebuffering_count;
@property(nonatomic) double reached_playback_end; // @synthesize reached_playback_end=_reached_playback_end;
@property(nonatomic) double was_playback_ready_to_play; // @synthesize was_playback_ready_to_play=_was_playback_ready_to_play;
@property(nonatomic) double playback_error_fatal; // @synthesize playback_error_fatal=_playback_error_fatal;
@property(nonatomic) double playback_error_count; // @synthesize playback_error_count=_playback_error_count;
@property(nonatomic) double download_stage_at_end; // @synthesize download_stage_at_end=_download_stage_at_end;
@property(nonatomic) double download_stage_at_playback; // @synthesize download_stage_at_playback=_download_stage_at_playback;
@property(nonatomic) double download_stage_at_start; // @synthesize download_stage_at_start=_download_stage_at_start;
@property(nonatomic) double downloaded_bytes_at_finish; // @synthesize downloaded_bytes_at_finish=_downloaded_bytes_at_finish;
@property(nonatomic) double downloaded_bytes_at_playback; // @synthesize downloaded_bytes_at_playback=_downloaded_bytes_at_playback;
@property(nonatomic) double downloaded_bytes_at_start; // @synthesize downloaded_bytes_at_start=_downloaded_bytes_at_start;
@property(nonatomic) double media_download_mode; // @synthesize media_download_mode=_media_download_mode;
@property(nonatomic) double e2e_media_encryption; // @synthesize e2e_media_encryption=_e2e_media_encryption;
@property(nonatomic) double media_size; // @synthesize media_size=_media_size;
@property(nonatomic) double mms_version; // @synthesize mms_version=_mms_version;
@property(nonatomic) double download_resume_point; // @synthesize download_resume_point=_download_resume_point;
@property(nonatomic) double is_reuse; // @synthesize is_reuse=_is_reuse;
@property(copy, nonatomic) NSString *route_ip; // @synthesize route_ip=_route_ip;
@property(copy, nonatomic) NSString *route_hostname; // @synthesize route_hostname=_route_hostname;
@property(nonatomic) double media_used_cdn; // @synthesize media_used_cdn=_media_used_cdn;
@property(nonatomic) double bytes_transferred; // @synthesize bytes_transferred=_bytes_transferred;
@property(nonatomic) double media_download_result; // @synthesize media_download_result=_media_download_result;
@property(nonatomic) double media_type; // @synthesize media_type=_media_type;
@property(nonatomic) double total_rebuffering_t_milliseconds; // @synthesize total_rebuffering_t_milliseconds=_total_rebuffering_t;
@property(nonatomic) double video_pause_t_milliseconds; // @synthesize video_pause_t_milliseconds=_video_pause_t;
@property(nonatomic) double time_since_previous_fetch_t_milliseconds; // @synthesize time_since_previous_fetch_t_milliseconds=_time_since_previous_fetch_t;
@property(nonatomic) double initial_stream_buffering_t_milliseconds; // @synthesize initial_stream_buffering_t_milliseconds=_initial_stream_buffering_t;
@property(nonatomic) double time_since_download_start_t_milliseconds; // @synthesize time_since_download_start_t_milliseconds=_time_since_download_start_t;
@property(nonatomic) double time_to_first_byte_t_milliseconds; // @synthesize time_to_first_byte_t_milliseconds=_time_to_first_byte_t;
@property(nonatomic) double file_validation_t_milliseconds; // @synthesize file_validation_t_milliseconds=_file_validation_t;
@property(nonatomic) double network_download_t_milliseconds; // @synthesize network_download_t_milliseconds=_network_download_t;
@property(nonatomic) double route_selection_delay_t_milliseconds; // @synthesize route_selection_delay_t_milliseconds=_route_selection_delay_t;
@property(nonatomic) double connect_t_milliseconds; // @synthesize connect_t_milliseconds=_connect_t;
@property(nonatomic) double media_download_t_milliseconds; // @synthesize media_download_t_milliseconds=_media_download_t;
- (void).cxx_destruct;
@property(nonatomic) double total_rebuffering_t_seconds;
@property(nonatomic) double video_pause_t_seconds;
@property(nonatomic) double time_since_previous_fetch_t_seconds;
@property(nonatomic) double initial_stream_buffering_t_seconds;
@property(nonatomic) double time_since_download_start_t_seconds;
@property(nonatomic) double time_to_first_byte_t_seconds;
@property(nonatomic) double file_validation_t_seconds;
@property(nonatomic) double network_download_t_seconds;
@property(nonatomic) double route_selection_delay_t_seconds;
@property(nonatomic) double connect_t_seconds;
@property(nonatomic) double media_download_t_seconds;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

