//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAPaintCanvasTextureRecipe.h"

@class WAPaintBrushContent;

@interface WAPaintCanvasBrushContentTextureRecipe : WAPaintCanvasTextureRecipe
{
    WAPaintBrushContent *_content;
    Class _rendererClass;
    struct CGSize _aspectRatio;
}

+ (id)recipeForContent:(id)arg1;
@property(readonly, nonatomic) struct CGSize aspectRatio; // @synthesize aspectRatio=_aspectRatio;
@property(readonly, nonatomic) Class rendererClass; // @synthesize rendererClass=_rendererClass;
@property(readonly, nonatomic) WAPaintBrushContent *content; // @synthesize content=_content;
- (void).cxx_destruct;
-     // Error parsing type: v100@0:8@16@24{CGSize=dd}32f48{?=[3]}52, name: addMetadataToDictionary:fromSample:renderSize:uncroppedAspectRatio:viewportTransform:
- (id)initWithContent:(id)arg1;

@end

