//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@interface WAPBChatFlags : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool archived; // @dynamic archived;
@property(nonatomic) _Bool hasArchived; // @dynamic hasArchived;
@property(nonatomic) _Bool hasHidden; // @dynamic hasHidden;
@property(nonatomic) _Bool hasTrustedChat; // @dynamic hasTrustedChat;
@property(nonatomic) _Bool hasVCardMatchDeclined; // @dynamic hasVCardMatchDeclined;
@property(nonatomic) _Bool hidden; // @dynamic hidden;
@property(nonatomic) _Bool trustedChat; // @dynamic trustedChat;
@property(nonatomic) _Bool vCardMatchDeclined; // @dynamic vCardMatchDeclined;

@end

