//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAVectorGraphic.h"

@interface WAPDFVectorGraphic : WAVectorGraphic
{
    struct CGPDFDocument *_pdf;
    struct CGPDFPage *_page;
}

- (id)imageOfSize:(struct CGSize)arg1;
- (struct CGSize)aspectRatio;
- (void)dealloc;
- (id)initWithName:(id)arg1;

@end

