//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface WASQLStatement : NSObject
{
    NSMutableArray *_allColumnNames;
    NSString *_query;
    CDUnknownBlockType _block;
    struct sqlite3_stmt *_stmt;
}

+ (id)statementWithFormat:(id)arg1;
@property(readonly, nonatomic) struct sqlite3_stmt *stmt; // @synthesize stmt=_stmt;
@property(readonly, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(readonly, nonatomic) NSString *query; // @synthesize query=_query;
@property(retain, nonatomic) NSMutableArray *allColumnNames; // @synthesize allColumnNames=_allColumnNames;
- (void).cxx_destruct;
- (_Bool)bindNonNullString:(id)arg1 atIndex:(int)arg2;
- (_Bool)bindString:(id)arg1 atIndex:(int)arg2;
- (_Bool)bindData:(id)arg1 atIndex:(int)arg2;
- (_Bool)bindDouble:(double)arg1 atIndex:(int)arg2;
- (_Bool)bindUInt64:(unsigned long long)arg1 atIndex:(int)arg2;
- (_Bool)bindUInt:(unsigned int)arg1 atIndex:(int)arg2;
- (_Bool)bindInt64:(long long)arg1 atIndex:(int)arg2;
- (_Bool)bindBOOL:(_Bool)arg1 atIndex:(int)arg2;
- (_Bool)bindInt:(int)arg1 atIndex:(int)arg2;
- (_Bool)bindNullAtIndex:(int)arg1;
- (_Bool)bindAtIndex:(int)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)releaseStatement;
- (void)addColumnWithName:(id)arg1;
- (_Bool)prepareWithDB:(struct sqlite3 *)arg1;
- (id)description;
- (id)initWithQuery:(id)arg1 bindBlock:(CDUnknownBlockType)arg2;
- (id)initWithQuery:(id)arg1;

@end

