//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WASQLObject : NSObject
{
}

+ (unsigned long long)countInDB:(struct sqlite3 *)arg1;
+ (_Bool)createTableIfNecessaryInDB:(struct sqlite3 *)arg1;
+ (id)tableName;
- (_Bool)replaceInDB:(struct sqlite3 *)arg1;
- (_Bool)insertIntoDB:(struct sqlite3 *)arg1;
- (_Bool)insertOrReplace:(id)arg1 db:(struct sqlite3 *)arg2;
- (_Bool)deleteFromDB:(struct sqlite3 *)arg1;
- (id)initWithDictionary:(id)arg1;
- (_Bool)populateWithDictionary:(id)arg1;
- (_Bool)bindAllValuesToStatement:(id)arg1;
- (id)allValues;
- (_Bool)bindIdentityToStatement:(id)arg1;
- (id)identityWhereClause;

@end

