//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_XMPPWebClientRequest.h"

@interface XMPPRequestWebClientForwardUnreadMessagesInChat : _XMPPWebClientRequest
{
}

- (id)initWithMessages:(id)arg1 firstUnread:(id)arg2 isResume:(_Bool)arg3 isLastBatch:(_Bool)arg4 forWebSession:(id)arg5 completion:(CDUnknownBlockType)arg6;

@end

