//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSSecureCoding-Protocol.h"

@class NSArray, NSData, NSMutableArray, NSString, XMPPAttributes, XMPPMutableAttributes;

@interface XMPPStanzaElement : NSObject <NSSecureCoding>
{
    XMPPMutableAttributes *_attributes;
    NSMutableArray *_children;
    _Bool _compressed;
    NSString *_name;
    NSData *_dataValue;
}

+ (_Bool)supportsSecureCoding;
+ (id)userElementFromJIDEntity:(id)arg1;
+ (id)chatElementFromChatSession:(id)arg1;
+ (id)batteryElement;
+ (id)configElement;
@property(copy, nonatomic) NSData *dataValue; // @synthesize dataValue=_dataValue;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) _Bool compressed; // @synthesize compressed=_compressed;
@property(readonly, nonatomic) NSArray *children; // @synthesize children=_children;
- (void).cxx_destruct;
- (id)log;
- (id)descriptionIncludingChildren:(_Bool)arg1;
@property(readonly, copy, nonatomic) NSString *summaryDescription;
@property(readonly, copy, nonatomic) NSString *description;
- (id)childArrayByName:(id)arg1;
- (id)childByName:(id)arg1 attribute:(id)arg2 value:(id)arg3;
- (id)childByName:(id)arg1;
- (id)childByIndex:(unsigned long long)arg1;
- (unsigned long long)childCount;
- (void)removeChild:(id)arg1;
- (void)addChild:(id)arg1;
@property(nonatomic) long long edit;
@property(readonly, nonatomic) _Bool hasEdit;
- (void)setStringValue:(id)arg1 sanitize:(_Bool)arg2;
- (id)stringValue_sanitize:(_Bool)arg1;
@property(readonly, copy, nonatomic) XMPPAttributes *attributes;
- (void)enumerateAttributeNamesUsingBlock:(CDUnknownBlockType)arg1;
- (unsigned long long)attributeCount;
- (id)attributeByName:(id)arg1 sanitize:(_Bool)arg2;
- (void)setAttributeWithName:(id)arg1 value:(id)arg2 sanitize:(_Bool)arg3;
- (id)initWithStanzaElement:(id)arg1;
- (id)initWithName:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)setVersionAndFeatures;
@property(readonly, copy, nonatomic) NSArray *participantJIDs;

@end

