//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_XMPPWebClientRequest.h"

@interface XMPPRequestWebClientSendChatStates : _XMPPWebClientRequest
{
}

- (id)initWithChatStates:(id)arg1 requestID:(id)arg2 isDuplicate:(_Bool)arg3 isPreemptive:(_Bool)arg4 statusChecksum:(id)arg5 forWebSession:(id)arg6 completion:(CDUnknownBlockType)arg7;

@end

