//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAActionSheetPresenter.h"

#import "UIActionSheetDelegate-Protocol.h"

@class NSMutableDictionary, NSString, UIActionSheet;

@interface _WAActionSheetPresenterOS7 : WAActionSheetPresenter <UIActionSheetDelegate>
{
    UIActionSheet *_actionSheet;
    UIActionSheet *_retainedActionSheetBeforePresentation;
    NSMutableDictionary *_actionMap;
    BOOL _disableDestructiveButtons;
}

- (void).cxx_destruct;
- (void)didPresentActionSheet:(id)arg1;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)addCancelButton;
- (void)addDestructiveButtonWithTitle:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)addButtonWithTitle:(id)arg1 image:(id)arg2 useBoldText:(BOOL)arg3 handler:(CDUnknownBlockType)arg4;
- (void)dismissByCancellingWithAnimation:(BOOL)arg1;
- (void)presentFromViewController:(id)arg1;
- (id)initWithTitle:(id)arg1 message:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

