//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

#import "CAAnimationDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class CADisplayLink, NSArray, NSMutableSet, NSString, UIPanGestureRecognizer, UIView, WAGrabHandleView;
@protocol _WACameraRollStripScrollViewDelegate;

@interface _WACameraRollStripScrollView : UIScrollView <UIGestureRecognizerDelegate, CAAnimationDelegate>
{
    WAGrabHandleView *_grabBarView;
    float _grabBarHeight;
    float _visibleHeightBeforeDragging;
    float _initialVisibleHeight;
    float _lastVisibleHeight;
    NSMutableSet *_visibleViews;
    NSMutableSet *_recycledViews;
    UIPanGestureRecognizer *_panGesture;
    int _panGestureCounter;
    int _panGestureCounterOnTouchDown;
    float _panGestureOffset;
    int _itemCount;
    int _initialHighlightedIndex;
    BOOL _isHighlightingCell;
    UIView *_backgroundView;
    CADisplayLink *_displayLink;
    float _animationToValue;
    float _animationFromValue;
    double _animationStartTime;
    double _animationDuration;
    double _swipeStartTime;
    BOOL _horizontallyFlipped;
    float _visibleHeight;
    UIView *_forceTouchSourceView;
    unsigned int _presentationState;
    float _thumbnailAlpha;
    struct CGSize _maximumThumbnailSizeInPixels;
}

+ (float)preferredThumbnailWidth;
+ (float)preferredHeight;
@property(nonatomic) float thumbnailAlpha; // @synthesize thumbnailAlpha=_thumbnailAlpha;
@property(nonatomic, getter=isHorizontallyFlipped) BOOL horizontallyFlipped; // @synthesize horizontallyFlipped=_horizontallyFlipped;
@property(readonly, nonatomic) struct CGSize maximumThumbnailSizeInPixels; // @synthesize maximumThumbnailSizeInPixels=_maximumThumbnailSizeInPixels;
@property(nonatomic) unsigned int presentationState; // @synthesize presentationState=_presentationState;
@property(readonly, nonatomic) UIView *forceTouchSourceView; // @synthesize forceTouchSourceView=_forceTouchSourceView;
@property(readonly, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(readonly, nonatomic) float visibleHeight; // @synthesize visibleHeight=_visibleHeight;
- (void).cxx_destruct;
- (int)indexForLocationPoint:(struct CGPoint)arg1;
- (void)reloadData;
@property(readonly, nonatomic) NSArray *visibleCells;
- (id)cellForItemAtIndex:(int)arg1;
- (void)willMoveToWindow:(id)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)cellAtPoint:(struct CGPoint)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)setGrabBarState:(float)arg1 animated:(BOOL)arg2;
- (void)setGrabBarStateWithAnimation:(BOOL)arg1;
- (float)targetVisibleHeightForCurrentHeight:(float)arg1 velocity:(struct CGPoint)arg2;
- (void)handleSecondaryPanGesture:(id)arg1;
- (void)handleLongPress:(id)arg1;
- (struct _NSRange)visibleRange;
- (float)thumbnailWidthForVisibleHeight:(float)arg1;
- (float)currentThumbnailWidth;
- (struct CGRect)centerAndSizeForItemAtIndex:(int)arg1;
- (void)layoutSubviews;
- (void)updateAnimation:(id)arg1;
- (void)animateFromVisibleHeight:(float)arg1 to:(float)arg2 duration:(double)arg3;
- (void)setVisibleHeight:(float)arg1 animated:(BOOL)arg2;
- (void)setPresentationState:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)contractIfPossible;
- (void)expandIfPossible;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <_WACameraRollStripScrollViewDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

