//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSString, NSTimer, UICollectionView, UILabel, UIView;
@protocol EntryCellDelegate;

@interface EntryCell : UITableViewCell <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    BOOL _isMasked;
    BOOL _confirmIsMasked;
    BOOL _isPrimaryActive;
    BOOL _isSelected;
    BOOL _isBigStyle;
    NSString *_cellTypeKey;
    int _fieldlength;
    NSString *_topText;
    UIView *_parentView;
    UILabel *_topLabel;
    UIView *_textFieldView;
    UIView *_secondaryView;
    NSString *_fieldText;
    UIView *_confirmParentView;
    NSString *_confirmText;
    UILabel *_confrimTopLabel;
    UIView *_confrimTextFieldView;
    UIView *_confrimSecondaryView;
    NSString *_language;
    id <EntryCellDelegate> _delegate;
    UICollectionView *_collectionView;
    UICollectionView *_confirmCollectionView;
    NSTimer *_resendOtpTimer;
    NSTimer *_buttonStateTimer;
}

+ (void)disableDelayedTouches:(id)arg1;
@property(retain, nonatomic) NSTimer *buttonStateTimer; // @synthesize buttonStateTimer=_buttonStateTimer;
@property(retain, nonatomic) NSTimer *resendOtpTimer; // @synthesize resendOtpTimer=_resendOtpTimer;
@property(retain, nonatomic) UICollectionView *confirmCollectionView; // @synthesize confirmCollectionView=_confirmCollectionView;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) BOOL isBigStyle; // @synthesize isBigStyle=_isBigStyle;
@property(nonatomic) __weak id <EntryCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL isSelected; // @synthesize isSelected=_isSelected;
@property(copy, nonatomic) NSString *language; // @synthesize language=_language;
@property(nonatomic) BOOL isPrimaryActive; // @synthesize isPrimaryActive=_isPrimaryActive;
@property(retain, nonatomic) UIView *confrimSecondaryView; // @synthesize confrimSecondaryView=_confrimSecondaryView;
@property(retain, nonatomic) UIView *confrimTextFieldView; // @synthesize confrimTextFieldView=_confrimTextFieldView;
@property(retain, nonatomic) UILabel *confrimTopLabel; // @synthesize confrimTopLabel=_confrimTopLabel;
@property(copy, nonatomic) NSString *confirmText; // @synthesize confirmText=_confirmText;
@property(nonatomic) BOOL confirmIsMasked; // @synthesize confirmIsMasked=_confirmIsMasked;
@property(retain, nonatomic) UIView *confirmParentView; // @synthesize confirmParentView=_confirmParentView;
@property(copy, nonatomic) NSString *fieldText; // @synthesize fieldText=_fieldText;
@property(retain, nonatomic) UIView *secondaryView; // @synthesize secondaryView=_secondaryView;
@property(retain, nonatomic) UIView *textFieldView; // @synthesize textFieldView=_textFieldView;
@property(retain, nonatomic) UILabel *topLabel; // @synthesize topLabel=_topLabel;
@property(nonatomic) BOOL isMasked; // @synthesize isMasked=_isMasked;
@property(retain, nonatomic) UIView *parentView; // @synthesize parentView=_parentView;
@property(copy, nonatomic) NSString *topText; // @synthesize topText=_topText;
@property(nonatomic) int fieldlength; // @synthesize fieldlength=_fieldlength;
@property(copy, nonatomic) NSString *cellTypeKey; // @synthesize cellTypeKey=_cellTypeKey;
- (void).cxx_destruct;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(int)arg3;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (float)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(int)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)layoutSubviews;
- (void)resetMpin;
- (void)changePrimary;
- (id)confirmPressed;
- (void)updateText:(id)arg1;
- (void)showHide:(id)arg1;
- (void)hide;
- (void)showHideDown:(id)arg1;
- (void)resendOtp;
- (void)enableOtp;
- (id)secondaryViewFor:(int)arg1;
- (void)deSelected;
- (void)selected;
- (void)commonInitType:(id)arg1 topText:(id)arg2 fieldLength:(int)arg3 secondaryViewType:(int)arg4 isMasked:(BOOL)arg5 confirm:(id)arg6 language:(id)arg7;
- (void)reloadCollectionView;
- (id)initWithBigStyle:(int)arg1 reuseIdentifier:(id)arg2 topText:(id)arg3 fieldLength:(int)arg4 isMasked:(BOOL)arg5 secondaryView:(int)arg6 withConfirm:(id)arg7 withLanguage:(id)arg8;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 topText:(id)arg3 fieldLength:(int)arg4 isMasked:(BOOL)arg5 secondaryView:(int)arg6 withConfirm:(id)arg7 withLanguage:(id)arg8;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

