//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableAttributedString.h>

@interface NSMutableAttributedString (Attachments)
- (void)wa_insertAttachmentsUsingFont:(id)arg1 withControlCharacters:(BOOL)arg2;
- (void)wa_resizeAttachmentsToMatchFont:(id)arg1;
- (void)wa_stripAttachments;
- (void)wa_insertAttachentWithAttachmentNamed:(id)arg1 location:(int)arg2 font:(id)arg3 addControlCharacters:(BOOL)arg4 insertNameIfNoAttachement:(BOOL)arg5;
@end

