//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAOperation.h"

@interface WAAsynchronousOperation : WAOperation
{
    unsigned int _internalState;
}

@property unsigned int internalState; // @synthesize internalState=_internalState;
- (void)performTaskWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)start;
- (void)skipExecuting;
- (void)stopExecuting;
- (void)startExecuting;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (BOOL)isAsynchronous;

@end

