//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableData, NSString, NSURL;

@interface WAAssetManagerFetchTask : NSObject
{
    BOOL _allowsCellularAccess;
    NSString *_assetIdentifier;
    NSURL *_url;
    unsigned int _attemptCount;
    NSMutableData *_receivedData;
}

@property(readonly, nonatomic) NSMutableData *receivedData; // @synthesize receivedData=_receivedData;
@property(readonly, nonatomic) BOOL allowsCellularAccess; // @synthesize allowsCellularAccess=_allowsCellularAccess;
@property(readonly, nonatomic) unsigned int attemptCount; // @synthesize attemptCount=_attemptCount;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
@property(readonly, nonatomic) NSString *assetIdentifier; // @synthesize assetIdentifier=_assetIdentifier;
- (void).cxx_destruct;
- (id)initWithAssetIdentifier:(id)arg1 url:(id)arg2 attemptCount:(unsigned int)arg3 allowsCellularAccess:(BOOL)arg4;

@end

