//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class AVPlayerItem, AVQueuePlayer, NSString, WAAudioActivity;
@protocol WAAutoPlayVideoPlayerPlaybackDelegate;

@interface WAAutoPlayVideoPlayerView : UIView
{
    BOOL _wasPlaying;
    BOOL _muted;
    NSString *_currentPlayerItemFilePath;
    AVPlayerItem *_originalItem;
    AVPlayerItem *_observedItem;
    WAAudioActivity *_playbackActivity;
    CDStruct_1b6d18a9 _playbackStartTime;
    BOOL _disabled;
    BOOL _isDisabledInternal;
    BOOL _isObservingPlayer;
    struct CGSize _internalItemSize;
    id _timeObserver;
    CDStruct_1b6d18a9 _internalTime;
    int _scrubbingCounter;
    BOOL _appForegrounded;
    id <WAAutoPlayVideoPlayerPlaybackDelegate> _delegate;
}

+ (Class)layerClass;
@property(nonatomic) BOOL appForegrounded; // @synthesize appForegrounded=_appForegrounded;
@property(nonatomic, getter=isDisabled) BOOL disabled; // @synthesize disabled=_disabled;
@property(nonatomic) __weak id <WAAutoPlayVideoPlayerPlaybackDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didEnterForeground:(id)arg1;
- (void)didEnterBackground:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)stopObservingPlayer;
- (void)handleTimeObserverUpdateWithTime:(CDStruct_1b6d18a9)arg1;
- (void)startObservingPlayer;
- (void)didMoveToWindow;
- (void)updatePlayerForStateChange;
- (BOOL)canAutoPlay;
- (void)endScrubbingAtTime:(CDStruct_1b6d18a9)arg1 completion:(CDUnknownBlockType)arg2;
- (void)beginScrubbing;
- (BOOL)isScrubbing;
- (struct CGSize)intrinsicContentSize;
@property(readonly, nonatomic) CDStruct_1b6d18a9 sourceTime;
- (void)updatePlayerItemForPlayerItem:(id)arg1;
- (void)updatePlayerItemForURLPath:(id)arg1;
- (void)prepareForNewPlayerItem;
- (void)updatePlayerForNewPlayerItem:(id)arg1;
- (void)enqueueAllPlayerItemsIfNeeded;
- (void)updateForNoItem;
- (void)failPlayerItemUpdate;
- (void)setPlaybackFinishTime:(CDStruct_1b6d18a9)arg1;
- (void)setPlaybackStartTime:(CDStruct_1b6d18a9)arg1;
- (void)setCurrentPlayStartTime:(CDStruct_1b6d18a9)arg1;
- (void)detachPlayer;
- (void)attachPlayer;
@property(nonatomic, getter=isMuted) BOOL muted;
@property(retain, nonatomic) AVQueuePlayer *player;
- (id)playerLayer;
- (void)dealloc;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

