//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView;

@interface WABackupIcon : UIView
{
    unsigned int _style;
    unsigned int _state;
    UIImageView *_image;
}

+ (id)imageForState:(unsigned int)arg1;
@property(retain, nonatomic) UIImageView *image; // @synthesize image=_image;
@property(nonatomic) unsigned int state; // @synthesize state=_state;
@property(nonatomic) unsigned int style; // @synthesize style=_style;
- (void).cxx_destruct;
- (void)updateAnimation;
- (void)updateIcon;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(unsigned int)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

