//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "WAPopupActionMenuSupport-Protocol.h"

@class NSArray, NSString, UILabel, UIView;

@interface WABizInfoTableViewCell : UITableViewCell <WAPopupActionMenuSupport>
{
    NSArray *_customConstraints;
    float _labelSpacing;
    float _rightMargin;
    UILabel *_descriptionTextLabel;
    BOOL _expandable;
    BOOL _expanded;
    UILabel *_titleTextLabel;
    UIView *_expandableView;
    struct UIEdgeInsets _cellInsets;
}

@property(readonly, nonatomic) struct UIEdgeInsets cellInsets; // @synthesize cellInsets=_cellInsets;
@property(nonatomic, getter=isExpanded) BOOL expanded; // @synthesize expanded=_expanded;
@property(nonatomic, getter=isExpandable) BOOL expandable; // @synthesize expandable=_expandable;
@property(readonly, nonatomic) UIView *expandableView; // @synthesize expandableView=_expandableView;
@property(readonly, nonatomic) UILabel *titleTextLabel; // @synthesize titleTextLabel=_titleTextLabel;
- (void).cxx_destruct;
- (void)performAction:(SEL)arg1 withSender:(id)arg2;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (BOOL)shouldShowPopupActionMenu;
- (void)updateViewsForExpansionState:(BOOL)arg1;
- (BOOL)toggleExpansion;
@property(copy, nonatomic) NSString *descriptionText;
- (void)updateForTextWithWidth:(float)arg1;
- (float)preferredHeightForWidth:(float)arg1;
- (float)emptyCellHeightForContentWidth:(float)arg1;
- (void)layoutSubviews;
- (void)updateConstraints;
- (id)customExpandableViewConstraints;
- (id)customLayouts;
- (void)setUpExpandableView;
- (void)deviceOrientationDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (id)init;

@end

