//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSData, NSDate, NSString;

@interface WABizConversionInfo : NSManagedObject
{
}

+ (void)insertWithJID:(id)arg1 creationDate:(id)arg2 lastUpdateTime:(id)arg3 data:(id)arg4 source:(id)arg5 inManagedObjectContext:(id)arg6;

// Remaining properties
@property(copy, nonatomic) NSDate *creationDate; // @dynamic creationDate;
@property(copy, nonatomic) NSData *data; // @dynamic data;
@property(copy, nonatomic) NSString *jid; // @dynamic jid;
@property(copy, nonatomic) NSDate *lastUpdateTime; // @dynamic lastUpdateTime;
@property(copy, nonatomic) NSString *source; // @dynamic source;

@end

