//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WABizInfoTableViewCell.h"

@class NSArray, UIView, WABizHoursView;

@interface WABizHoursTableViewCell : WABizInfoTableViewCell
{
    WABizHoursView *_todayView;
    UIView *_otherDaysSuperView;
    WABizHoursView *_day1View;
    WABizHoursView *_day2View;
    WABizHoursView *_day3View;
    WABizHoursView *_day4View;
    WABizHoursView *_day5View;
    WABizHoursView *_day6View;
    NSArray *_otherDayViews;
    float _todayViewHeight;
    float _labelVerticalSpacing;
}

- (void).cxx_destruct;
- (void)updateViewsForExpansionState:(BOOL)arg1;
- (void)updateForTextWithWidth:(float)arg1;
- (void)updateForBizHours:(id)arg1;
- (float)preferredHeightForWidth:(float)arg1;
- (id)customExpandableViewConstraints;
- (void)setUpOtherDays;
- (void)setUpExpandableView;

@end

