//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WABizHoursConfig : NSObject
{
    // Error parsing type: , name: mode
    // Error parsing type: , name: day
    // Error parsing type: , name: openTime
    // Error parsing type: , name: closeTime
}

+ (BOOL)supportsSecureCoding;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithMode:(id)arg1 day:(id)arg2 openTime:(int)arg3 closeTime:(int)arg4;
@property(nonatomic) int closeTime; // @synthesize closeTime;
@property(nonatomic) int openTime; // @synthesize openTime;
@property(nonatomic) int day; // @synthesize day;
@property(nonatomic) int mode; // @synthesize mode;

@end

