//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAChatDataStoreCoordinator.h"

#import "WAPersistentRequestManagerRegistering-Protocol.h"
#import "WASyncedContactListProviding-Protocol.h"

@class NSSet, NSString, WASyncedContactList, XMPPConnection;

@interface WABlockedContactsList : WAChatDataStoreCoordinator <WASyncedContactListProviding, WAPersistentRequestManagerRegistering>
{
    WASyncedContactList *_syncedList;
    XMPPConnection *_xmppConnection;
}

@property(readonly, nonatomic) XMPPConnection *xmppConnection; // @synthesize xmppConnection=_xmppConnection;
- (void).cxx_destruct;
- (void)registerHandlersForPersistentRequestManager:(id)arg1;
- (id)sharedObjectKeyForPersistentRequestManager:(id)arg1;
- (void)syncedContactList:(id)arg1 didUpdateWithJid:(id)arg2;
- (void)fetchJIDsForSyncedContactList:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)syncedContactList:(id)arg1 didRequestSendJIDs:(id)arg2 webClientRequestID:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)permanentlySaveJIDs:(id)arg1 forSyncedContactList:(id)arg2;
- (id)pathToPendingContactsStoreForSyncedContactList:(id)arg1;
- (id)permanentlySavedJIDsForSyncedContactList:(id)arg1;
@property(nonatomic) BOOL listInSync;
- (void)setNeedsDownstreamSync;
- (void)unblockJID:(id)arg1 webClientRequestID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)blockJID:(id)arg1 webClientRequestID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)isJIDBlocked:(id)arg1;
@property(readonly, nonatomic) NSSet *jids;
@property(readonly, nonatomic) unsigned int size;
- (id)initWithChatDataStores:(id)arg1 xmppConnection:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

