//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSLayoutConstraint, UILabel, UIView, WAAggregateCallEvent, WAProfilePictureThumbnailView;

@interface WACallHistoryTableViewCell : UITableViewCell
{
    WAAggregateCallEvent *_aggregateCallEvent;
    NSLayoutConstraint *_textContainerTrailingMargin;
    NSLayoutConstraint *_profilePictureLeadingMargin;
    unsigned int _lastCellState;
    WAProfilePictureThumbnailView *_profilePicture;
    UIView *_textContainer;
    UILabel *_displayNameLabel;
    UILabel *_eventCountLabel;
    UILabel *_detailLabel;
    UILabel *_dateLabel;
}

+ (id)callDetailsFont;
+ (float)preferredHeight;
+ (void)initialize;
@property(retain, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *eventCountLabel; // @synthesize eventCountLabel=_eventCountLabel;
@property(retain, nonatomic) UILabel *displayNameLabel; // @synthesize displayNameLabel=_displayNameLabel;
@property(retain, nonatomic) UIView *textContainer; // @synthesize textContainer=_textContainer;
@property(retain, nonatomic) WAProfilePictureThumbnailView *profilePicture; // @synthesize profilePicture=_profilePicture;
- (void).cxx_destruct;
- (id)infoIconImageView;
- (void)willTransitionToState:(unsigned int)arg1;
- (void)applyFonts;
- (void)updateLeadingMarginIfNecessary;
- (void)layoutMarginsDidChange;
- (void)layoutSubviews;
- (id)accessibilityLabel;
- (void)configureWithAggregateCallEvent:(id)arg1;
- (void)setupAutoLayoutConstraints;
- (void)updateSeparatorInset;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

