//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WACallParticipantInfo : NSObject
{
    BOOL _isMuted;
    BOOL _isInterrupted;
    BOOL _isVideoDecodePaused;
    BOOL _isVideoDecodeStarted;
    BOOL _isAudioVideoSwitchEnabled;
    BOOL _isAudioVideoSwitchSupported;
    BOOL _isRxTrafficStopped;
    NSString *_jid;
    unsigned int _videoState;
    struct CGSize _videoSize;
}

+ (unsigned int)videoStateFromCallInfoVideoState:(int)arg1;
@property(readonly, nonatomic) BOOL isRxTrafficStopped; // @synthesize isRxTrafficStopped=_isRxTrafficStopped;
@property(readonly, nonatomic) BOOL isAudioVideoSwitchSupported; // @synthesize isAudioVideoSwitchSupported=_isAudioVideoSwitchSupported;
@property(readonly, nonatomic) BOOL isAudioVideoSwitchEnabled; // @synthesize isAudioVideoSwitchEnabled=_isAudioVideoSwitchEnabled;
@property(readonly, nonatomic) BOOL isVideoDecodeStarted; // @synthesize isVideoDecodeStarted=_isVideoDecodeStarted;
@property(readonly, nonatomic) BOOL isVideoDecodePaused; // @synthesize isVideoDecodePaused=_isVideoDecodePaused;
@property(readonly, nonatomic) unsigned int videoState; // @synthesize videoState=_videoState;
@property(readonly, nonatomic) struct CGSize videoSize; // @synthesize videoSize=_videoSize;
@property(readonly, nonatomic) BOOL isInterrupted; // @synthesize isInterrupted=_isInterrupted;
@property(readonly, nonatomic) BOOL isMuted; // @synthesize isMuted=_isMuted;
@property(readonly, nonatomic) NSString *jid; // @synthesize jid=_jid;
- (void).cxx_destruct;
- (id)initWithParticipantInfo:(struct wa_call_participant_detail_info_t)arg1;

@end

