//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAViewController.h"

#import "CLLocationManagerDelegate-Protocol.h"
#import "SinglePersonPickerDelegate-Protocol.h"
#import "WACallActionViewDelegate-Protocol.h"
#import "WACallSpamReportViewDelegate-Protocol.h"
#import "WACallVideoViewDelegate-Protocol.h"
#import "WACallViewDelegate-Protocol.h"
#import "WACallViewTopPanelViewDelegate-Protocol.h"
#import "WAVoiceCallInteractionBlockingViewDelegate-Protocol.h"
#import "WAVoiceCallRatingOptionsViewDelegate-Protocol.h"
#import "WAVoiceCallRatingViewDelegate-Protocol.h"

@class MPVolumeView, NSObject, NSString, NSTimer, UIImage, UIView, WACallView, WALayoutBoundsManager, WAVoiceCallInteractionBlockingView, _WATouchCapturingGestureRecognizer;
@protocol OS_dispatch_queue, WACallViewControllerDelegate;

@interface WACallViewController : WAViewController <WAVoiceCallInteractionBlockingViewDelegate, CLLocationManagerDelegate, WAVoiceCallRatingViewDelegate, WAVoiceCallRatingOptionsViewDelegate, WACallSpamReportViewDelegate, WACallViewDelegate, WACallViewTopPanelViewDelegate, WACallVideoViewDelegate, SinglePersonPickerDelegate, WACallActionViewDelegate>
{
    BOOL _minimized;
    BOOL _changingMinimizedState;
    NSTimer *_timer;
    BOOL _hasTimerFired;
    UIImage *_blurredImage;
    unsigned int _backgroundTask;
    WACallView *_callView;
    BOOL _isMonitoringProximity;
    NSString *_peerDisplayName;
    NSString *_peerFirstName;
    BOOL _isPeerKnown;
    BOOL _isIncomingCall;
    double _lastBatteryPrintTime;
    int _callDurationInSeconds;
    UIView *_snapshotOfPresentingView;
    int _oldState;
    BOOL _idleTimerDisabled;
    double _batteryLevelTime;
    double _lastBatteryLevel;
    int _callRating;
    BOOL _videoCall;
    MPVolumeView *_audioRouteButton;
    WAVoiceCallInteractionBlockingView *_interactionBlockingView;
    _WATouchCapturingGestureRecognizer *_touchCapturingRecognizer;
    NSTimer *_delayedInteractionBlockingTimer;
    BOOL _videoPreviewMinimized;
    BOOL _peerVideoRenderStarted;
    int _cameraType;
    NSTimer *_toggleButtonsTimer;
    BOOL _callDidEnd;
    UIView *_snapshot;
    BOOL _requestPeerViewFullScreen;
    BOOL _switchingCamera;
    WALayoutBoundsManager *_layoutBoundsManager;
    BOOL _dragging;
    struct CGPoint _initialPanPoint;
    struct CGRect _initialPeerVideoViewFrame;
    struct CGRect _initialPreviewVideoViewFrame;
    struct CGRect _intermediatePeerVideoViewFrame;
    struct CGRect _intermediatePreviewVideoViewFrame;
    struct CGRect _finalPeerVideoViewFrame;
    struct CGRect _finalPreviewVideoViewFrame;
    struct CGSize _initialPeerVideoSubviewSize;
    struct CGSize _initialPreviewVideoSubviewSize;
    struct CGRect _finalPeerVideoSubviewFrame;
    struct CGRect _finalPreviewVideoSubviewFrame;
    float _initialPeerCornerRadius;
    float _initialPreviewCornerRadius;
    float _finalPeerCornerRadius;
    float _finalPreviewCornerRadius;
    int _initialOrientation;
    int _minimizedVideoViewANchorLocation;
    BOOL _adjustAudioRouteAfterTransition;
    NSObject<OS_dispatch_queue> *_serialAudioRouteQueue;
    NSString *_calleeJID;
    id <WACallViewControllerDelegate> _delegate;
    int _callState;
    struct WACallOverlayAnchorsWithOffset _callOverlayViewAnchors;
}

@property(nonatomic) struct WACallOverlayAnchorsWithOffset callOverlayViewAnchors; // @synthesize callOverlayViewAnchors=_callOverlayViewAnchors;
@property(readonly, nonatomic, getter=isVideoCall) BOOL videoCall; // @synthesize videoCall=_videoCall;
@property(nonatomic) int callState; // @synthesize callState=_callState;
@property(nonatomic) __weak id <WACallViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) WACallView *callView; // @synthesize callView=_callView;
@property(readonly, copy, nonatomic) NSString *calleeJID; // @synthesize calleeJID=_calleeJID;
@property(readonly, nonatomic, getter=isChangingMinimizedState) BOOL changingMinimizedState; // @synthesize changingMinimizedState=_changingMinimizedState;
@property(readonly, nonatomic, getter=isMinimized) BOOL minimized; // @synthesize minimized=_minimized;
- (void).cxx_destruct;
- (id)excludedJIDsForSinglePersonPicker:(id)arg1;
- (void)singlePersonPickerDidCancel:(id)arg1;
- (void)singlePersonPicker:(id)arg1 didSelectContact:(id)arg2;
- (void)callVideoViewDidRequestCancelUpgrade:(id)arg1;
- (void)callViewTopPanelViewDidRequestDetailedInfoView:(id)arg1;
- (void)callViewTopPanelViewDidRequestInfoView:(id)arg1;
- (void)callViewTopPanelViewDidRequestBack:(id)arg1;
- (void)callViewTopPanelViewDidRequestAddParticipant:(id)arg1;
- (void)audioSessionRouteChanged:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (void)updateAudioRoute;
- (void)proximityStateDidChange:(id)arg1;
- (void)stopMonitoringProximity;
- (void)startMonitoringProximityIfNeeded;
- (void)updateProximityMonitoring;
@property(readonly, nonatomic, getter=isCallRatingViewVisible) BOOL callRatingViewVisible;
- (void)dismissCallRatingScreen;
- (void)showCallRatingScreen;
- (void)voiceCallRatingOptionsView:(id)arg1 didFinishWithAction:(unsigned int)arg2;
- (void)voiceCallRatingView:(id)arg1 didFinishWithAction:(unsigned int)arg2;
- (BOOL)shouldShowRatingView;
@property(readonly, nonatomic, getter=isSpamReportViewVisible) BOOL spamReportViewVisible;
- (void)dismissSpamReportScreen;
- (void)showSpamReportScreen;
- (void)callSpamReportView:(id)arg1 didFinishWithAction:(unsigned int)arg2;
- (BOOL)shouldShowSpamReportView;
- (void)remindToCallWhenLeaving;
- (void)remindToCallInOneHour;
- (id)createReminder;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)handleSelfVideoStreamChange;
- (void)handlePeerVideoStreamChange;
- (void)handleVideoCallUpgradeRequestCompletion;
- (void)handleVideoCallUpgradeCompletion;
- (void)handleVideoCallUpgradeTimeout;
- (void)handleVideoCallUpgradeReject;
- (void)handleVideoCallUpgradeCancel;
- (void)handleVideoCallUpgradeRequest;
- (void)requestUpgradeToVideoCall;
- (void)turnCameraOff;
- (void)turnCameraOn;
- (void)showErrorAlertWithTitle:(id)arg1;
- (void)becomeActiveFromView:(id)arg1;
- (void)minimize;
- (void)rejectCallAndGoToChatView;
- (void)callActionViewDidToggleVideo:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)rejectCallAndSendMessageText:(id)arg1;
- (void)callActionViewDidRequestSendMessage:(id)arg1;
- (void)callActionViewDidRequestCancelAndSendMessage:(id)arg1;
- (void)callActionViewDidToggleSpeaker:(id)arg1;
- (void)callActionViewDidRequestSwitchCamera:(id)arg1;
- (void)callActionView:(id)arg1 didRequestSetMute:(BOOL)arg2;
- (void)callActionViewDidRequestAcceptOrEndCall:(id)arg1;
- (void)callActionViewDidRequestCancelAndAddReminder:(id)arg1;
- (void)callActionViewDidRequestRejectCall:(id)arg1;
- (id)snapshotOfPresentingViewForCallView:(id)arg1;
- (void)rejectOrEndCall;
- (void)acceptCall;
- (void)cancelOutgoingCall;
- (void)handleCallUnavailable;
- (void)handleCallBusy;
- (void)handleCallPreaccept;
- (void)handleCallTimeout;
- (void)handleCallFailure;
- (void)handleCallRejectedByPeer;
- (void)handleCallTerminationByPeer;
- (void)reallyDismissWithDelayIfNeeded:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dismiss:(BOOL)arg1;
- (BOOL)isTransitioningToVideoCall;
- (void)setCallState:(int)arg1 animated:(BOOL)arg2;
- (void)appWillResignActive:(id)arg1;
- (void)callStateDidBecomeActive:(id)arg1;
- (void)applicationDidChangeStatusBarFrame:(id)arg1;
- (void)printBatteryLevel;
- (void)loadLargeProfileImageAsyncForCallView:(id)arg1;
- (void)updateCallStateLabels;
- (void)transitionToVoiceCallInterface;
- (void)transitionToVideoCallInterface;
- (void)timerFired:(id)arg1;
- (int)preferredStatusBarUpdateAnimation;
- (BOOL)wa_prefersStatusBarHidden;
- (void)viewDidLayoutSubviews;
- (void)endDisablingApplicationIdleTimer;
- (void)beginDisablingApplicationIdleTimer;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)setupCallView;
- (void)viewDidLoad;
- (int)preferredStatusBarStyle;
- (void)setBlurredImageFromView:(id)arg1;
- (void)updateSnapshot;
- (void)prepareToAnimateInFromView:(id)arg1;
- (id)uniqueIdentifier;
- (void)dealloc;
- (id)initWithInitialCallState:(int)arg1 isVideoCall:(BOOL)arg2;
- (struct CGSize)sizeForPercentage:(float)arg1 initialFrameSize:(struct CGSize)arg2 finalFrameSize:(struct CGSize)arg3;
- (struct CGPoint)largeVideoViewOriginForPercentage:(float)arg1 initialLargeVideoFrame:(struct CGRect)arg2 finalLargeVideoFrame:(struct CGRect)arg3 currentFrameSize:(struct CGSize)arg4;
- (void)computeFinalFrames;
- (void)computeIntermediateFrames;
- (void)computeInitialFrames;
- (void)computeAnchorForVelocity:(struct CGPoint)arg1;
- (void)setPeerVideoViewFrame:(struct CGRect)arg1 peerVideoSubviewSize:(struct CGSize)arg2 previewVideoViewFrame:(struct CGRect)arg3 previewVideoSubviewSize:(struct CGSize)arg4 peerRadius:(float)arg5 previewRadius:(float)arg6;
- (void)minimizeVideoViewsWithPercentage:(float)arg1;
- (void)circleVideoViewsWithPercentage:(float)arg1;
- (void)transformVideoViewsWithPercentage:(float)arg1;
- (void)completeMinimizeWithVelocity:(struct CGPoint)arg1;
- (void)maximize;
- (void)minimizeWithPan:(id)arg1;
- (void)videoMinimize;
- (BOOL)isPreviewVideoFullScreen;
- (void)rotateViewsWithAngle:(float)arg1;
- (void)rotateViewsIfNeeded;
- (void)deviceOrientationDidChange:(id)arg1;
- (void)setButtonHidden:(BOOL)arg1;
- (void)hideButtons;
- (void)setHideButtonsTimer;
- (void)toggleButtons:(id)arg1;
- (void)videoBecomeActiveFromView:(id)arg1;
- (BOOL)prefersHomeIndicatorAutoHidden;
- (int)videoPreferredStatusBarUpdateAnimation;
- (BOOL)videoPrefersStatusBarHidden;
- (void)videoCallActionViewDidRequestSwitchCamera:(id)arg1;
- (void)videoCallActionView:(id)arg1 didRequestSetMute:(BOOL)arg2;
- (void)callDidEnd:(id)arg1;
- (void)peerVideoRenderStarted:(id)arg1;
- (void)videoPreviewMinimized:(id)arg1;
@property(readonly, nonatomic) int minimizedVideoViewAnchorLocation;
- (void)videoViewDidDisappear;
- (void)videoViewDidAppear;
- (void)videoSetUpCallView:(id)arg1;
- (void)videoInit;
- (void)voiceCallInteractionBlockingViewDidUnlock:(id)arg1;
- (void)didTouch;
- (void)setUpTouchCapturingRecognizerIfNeeded;
- (void)cancelDelayedInteractionBlocking;
- (void)startDelayedInteractionBlocking;
- (void)restartDelayedInteractionBlocking;
- (void)hideInteractionBlockingView;
- (void)setUpInteractionBlockingViewIfNeeded;
- (void)showInteractionBlockingView;
- (void)stopInteractionBlockingIfNeeded;
- (void)startInteractionBlockingIfNeeded;
- (BOOL)isCallEnding;
- (void)audioRouteDidChange:(id)arg1;
- (void)updateInterfaceForCurrentAudioRoute;
- (void)voiceCallActionViewDidToggleSpeaker:(id)arg1;
- (void)showAudioRoutePicker;
- (void)installInvisibleAudioRouteButtonIfNeeded;
- (void)voiceSetUpCallView:(id)arg1;
- (void)voiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

