//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSSet, NSString, NSURL, WAChatSession, WAPBBackupChat;

@protocol WAChatStoragePIBackupProtocol <NSObject>
@property(readonly, nonatomic) NSURL *databaseStoreURL;
- (WAChatSession *)chatSessionForJID:(NSString *)arg1;
- (void)messagesForBackupKey:(NSString *)arg1 completion:(void (^)(NSArray *))arg2;
- (void)updateLastMessageForChatSessionsWithCompletion:(void (^)(void))arg1;
- (void)requestParticipatingGroups:(BOOL)arg1 withCompletion:(void (^)(NSError *))arg2;
- (void)prepareBroadcastMessagesForStanzaIDs:(NSSet *)arg1 shouldCancelBlock:(BOOL (^)(void))arg2 completion:(void (^)(void))arg3;
- (void)addMessagesForBackupMessages:(NSArray *)arg1 includesSort:(BOOL)arg2 completion:(void (^)(NSError *, NSArray *, NSSet *))arg3;
- (WAChatSession *)addChatForBackupChat:(WAPBBackupChat *)arg1;
- (void)save;
@end

