//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WANoChatsView.h"

@class UITableViewCell;
@protocol WAEmptyChatListViewDelegate;

@interface WAEmptyChatListView : WANoChatsView
{
    UITableViewCell *_tellAFriendCell;
    UITableViewCell *_startMessagingCell;
    id <WAEmptyChatListViewDelegate> _delegate;
}

@property(nonatomic) __weak id <WAEmptyChatListViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)updateFonts;
- (id)labelText;
- (id)topLabelTextWithFont:(id)arg1 lineSpacing:(float)arg2;
- (id)init;

@end

