//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAViewController.h"

#import "UISearchBarDelegate-Protocol.h"
#import "UISearchControllerDelegate-Protocol.h"
#import "UISearchDisplayDelegate-Protocol.h"
#import "UISearchResultsUpdating-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UIToolbarDelegate-Protocol.h"
#import "WAForwardPickerDataSourceDelegate-Protocol.h"
#import "WASearchResultsControllerDelegate-Protocol.h"

@class NSArray, NSLayoutConstraint, NSMutableArray, NSMutableDictionary, NSMutableSet, NSSet, NSString, UIBarButtonItem, UISearchController, UISearchDisplayController, UITableView, WAForwardPickerDataSource, WASearchResultsController, WamEventForwardPicker, _WAForwardPickerEmptyListView, _WAForwardPickerMultiselectBar, _WAMyStatusTableViewCell;

@interface WAForwardPickerViewController : WAViewController <WAForwardPickerDataSourceDelegate, WASearchResultsControllerDelegate, UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, UISearchDisplayDelegate, UIToolbarDelegate, UISearchResultsUpdating, UISearchControllerDelegate>
{
    _WAForwardPickerEmptyListView *_emptyListView;
    UIBarButtonItem *_barButtonCancel;
    BOOL _showCancelButton;
    WASearchResultsController *_searchResultsController;
    NSMutableDictionary *_contactsForChatSessions;
    NSMutableArray *_selectedContacts;
    BOOL _showStatusVideoTruncationWarning;
    BOOL _showStatusTextTruncationWarning;
    _WAMyStatusTableViewCell *_myStatusCell;
    _WAForwardPickerMultiselectBar *_multiSelectBar;
    NSLayoutConstraint *_multiSelectBarToSuperViewBottom;
    BOOL _resetScrollOffsetInLayoutSubviews;
    float _keyboardHeight;
    WamEventForwardPicker *_fsEvent;
    double _controllerDidAppearTimestamp;
    NSMutableSet *_selectedSearchResults;
    NSArray *_originalNavigationStack;
    BOOL _requiresConfirmation;
    BOOL _allowsMultipleSelection;
    BOOL _allowsStatusSelection;
    BOOL _statusSelectionDisabled;
    BOOL _statusSelected;
    BOOL _useSearchController;
    CDUnknownBlockType _completionHandler;
    NSString *_confirmationButtonTitle;
    NSString *_confirmationTextForStatus;
    CDUnknownBlockType _confirmationTextForContact;
    CDUnknownBlockType _shouldProceedWithContact;
    int _contentType;
    UITableView *_tableView;
    WAForwardPickerDataSource *_dataSource;
    UISearchController *_searchController;
    UISearchDisplayController *_searchDisplayController;
}

+ (id)controller;
@property(retain, nonatomic) UISearchDisplayController *searchDisplayController; // @synthesize searchDisplayController=_searchDisplayController;
@property(retain, nonatomic) UISearchController *searchController; // @synthesize searchController=_searchController;
@property(nonatomic) BOOL useSearchController; // @synthesize useSearchController=_useSearchController;
@property(retain, nonatomic) WAForwardPickerDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) int contentType; // @synthesize contentType=_contentType;
@property(copy, nonatomic) NSArray *selectedContacts; // @synthesize selectedContacts=_selectedContacts;
@property(copy, nonatomic) CDUnknownBlockType shouldProceedWithContact; // @synthesize shouldProceedWithContact=_shouldProceedWithContact;
@property(copy, nonatomic) CDUnknownBlockType confirmationTextForContact; // @synthesize confirmationTextForContact=_confirmationTextForContact;
@property(copy, nonatomic) NSString *confirmationTextForStatus; // @synthesize confirmationTextForStatus=_confirmationTextForStatus;
@property(copy, nonatomic) NSString *confirmationButtonTitle; // @synthesize confirmationButtonTitle=_confirmationButtonTitle;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) BOOL statusSelected; // @synthesize statusSelected=_statusSelected;
@property(nonatomic) BOOL statusSelectionDisabled; // @synthesize statusSelectionDisabled=_statusSelectionDisabled;
@property(nonatomic) BOOL allowsStatusSelection; // @synthesize allowsStatusSelection=_allowsStatusSelection;
@property(nonatomic) BOOL allowsMultipleSelection; // @synthesize allowsMultipleSelection=_allowsMultipleSelection;
@property(nonatomic) BOOL requiresConfirmation; // @synthesize requiresConfirmation=_requiresConfirmation;
- (void).cxx_destruct;
- (BOOL)shouldProceedWithContact:(id)arg1;
- (void)tableView:(id)arg1 didSelectContactRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectStatusRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (BOOL)tableViewIsDisplayingSearchResults:(id)arg1;
- (id)tableView:(id)arg1 cellForStatusAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForContact:(id)arg2 atIndexPath:(id)arg3;
- (void)forwardPickerDataSourceDidChangeContent:(id)arg1;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (BOOL)searchBarShouldBeginEditing:(id)arg1;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (void)searchDisplayController:(id)arg1 willHideSearchResultsTableView:(id)arg2;
- (void)searchDisplayController:(id)arg1 willShowSearchResultsTableView:(id)arg2;
- (void)searchDisplayController:(id)arg1 didLoadSearchResultsTableView:(id)arg2;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)didDismissSearchController:(id)arg1;
- (void)didPresentSearchController:(id)arg1;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (void)searchResultsControllerDidChangeContent:(id)arg1;
- (void)searchResultsController:(id)arg1 didDeleteSections:(id)arg2;
- (void)searchResultsController:(id)arg1 didInsertSections:(id)arg2;
- (void)searchResultsController:(id)arg1 didUpdateRowsAtIndexPaths:(id)arg2;
- (void)searchResultsController:(id)arg1 didDeleteRowsAtIndexPaths:(id)arg2;
- (void)searchResultsController:(id)arg1 didInsertRowsAtIndexPaths:(id)arg2;
- (void)searchResultsControllerWillChangeContent:(id)arg1;
- (BOOL)searchResultsControllerShouldReloadData:(id)arg1;
- (BOOL)searchResultsController:(id)arg1 shouldLoadAsynchronously:(unsigned int)arg2;
- (void)searchResultsControllerDidReloadData:(id)arg1;
- (id)searchResultsTableView;
- (void)tearDownSearchResultsController;
- (void)initializeSearchResultsController;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)contactForSearchResultAtIndexPath:(id)arg1;
- (id)contactForChatSessionSearchResult:(id)arg1;
- (void)updateContactSelection;
- (void)finishWithSelectedContacts;
- (void)statusPrivacyPolicyDidChange:(id)arg1;
- (void)showStatusPrivacySettingsPicker;
- (BOOL)showPrivacySettingsHelperPopup;
- (void)showHelperPopupAfterStatusSelection;
- (BOOL)isStatusCellSufficientlyVisible;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)setKeyboardHeight:(float)arg1;
@property(copy, nonatomic) NSSet *excludedJIDs;
- (void)setSharedMediaItems:(id)arg1;
- (void)setSharedItems:(id)arg1;
- (void)updateMultiSelectBarContentInsets;
- (void)updateTableViewInsets;
- (void)cancel:(id)arg1;
- (void)cancel;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)wa_fontSizeDidChange;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewSafeAreaInsetsDidChange;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

