//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MapKit/MKAnnotationView.h>

@class CAShapeLayer, NSString, UIImage, UIImageView, UIView, WAWeakTimer;

@interface WAFriendLocationAnnotationView : MKAnnotationView
{
    UIView *_pulseView;
    CAShapeLayer *_pulseLayer;
    UIView *_dot;
    CAShapeLayer *_dotShapeLayer;
    BOOL _observingNotifications;
    WAWeakTimer *_staleTimer;
    CAShapeLayer *_accuracyLayer;
    float _scale;
    BOOL _stale;
    BOOL _highlightDot;
    UIImageView *_profileImageView;
    NSString *_jid;
    CDUnknownBlockType _profilePictureDidChange;
    UIImageView *_imageView;
}

+ (id)roundImageWithProfilePic:(id)arg1;
+ (BOOL)shouldPulse;
+ (float)heightBelowPoint;
+ (float)heightAbovePoint;
+ (float)sidePadding;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(copy, nonatomic) CDUnknownBlockType profilePictureDidChange; // @synthesize profilePictureDidChange=_profilePictureDidChange;
@property(nonatomic) BOOL highlightDot; // @synthesize highlightDot=_highlightDot;
@property(readonly, nonatomic) NSString *jid; // @synthesize jid=_jid;
@property(readonly, nonatomic) UIImageView *profileImageView; // @synthesize profileImageView=_profileImageView;
- (void).cxx_destruct;
- (void)profilePictureDidChange:(id)arg1;
- (void)setScale:(float)arg1 animated:(BOOL)arg2 animationDuration:(double)arg3 completion:(CDUnknownBlockType)arg4;
- (void)setScale:(float)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (CDUnknownBlockType)internalSetScale:(float)arg1 animated:(BOOL)arg2 duration:(double)arg3;
- (struct CGRect)frameForProfileImageViewWithScale:(float)arg1;
- (void)addPulseView;
- (float)transparentPadding;
- (void)updatePulseLayerColor;
@property(readonly, nonatomic) BOOL pulseLayerShouldBeRed;
- (void)setStale:(BOOL)arg1;
- (void)updateStaleTimerWithLastUpdateAt:(id)arg1;
- (void)handleLocationUpdate:(id)arg1;
- (void)installAnimation;
- (struct CGSize)intrinsicContentSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (BOOL)annotationIsMeAndILackLocationPermission;
- (BOOL)haveLocationPermission;
- (void)didMoveToWindow;
- (struct CGPoint)pulseInsets;
- (float)sideLength;
- (void)setAnnotation:(id)arg1;
- (struct CGPath *)accuracyPath;
- (void)updateAccuracyCircleAnimated:(BOOL)arg1;
- (id)enclosingMapView;
- (void)setShowAccuracyCircle:(BOOL)arg1;
- (id)profilePic;
@property(readonly, nonatomic) UIImage *rasterization;
- (id)profileImage;
- (id)imageName;
- (BOOL)hasDot;
@property(readonly, nonatomic) BOOL hasProfilePicture;
- (void)dealloc;
- (void)wa_commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithAnnotation:(id)arg1 reuseIdentifier:(id)arg2;

@end

