//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@interface WamEventIphoneBackgroundFetch : WamEvent
{
    double _iphone_background_fetch_result;
}

@property(nonatomic) double iphone_background_fetch_result; // @synthesize iphone_background_fetch_result=_iphone_background_fetch_result;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

