//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@interface WamEventLiveLocationDurationPicker : WamEvent
{
    double _live_location_duration_picker_selected_duration;
    double _live_location_duration_picker_entry_point;
}

@property(nonatomic) double live_location_duration_picker_entry_point; // @synthesize live_location_duration_picker_entry_point=_live_location_duration_picker_entry_point;
@property(nonatomic) double live_location_duration_picker_selected_duration; // @synthesize live_location_duration_picker_selected_duration=_live_location_duration_picker_selected_duration;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

