//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WAMemoryMappedImageStore : NSObject
{
}

+ (void)internalRemoveImageForKey:(id)arg1;
+ (void)internalSetImage:(id)arg1 forKey:(id)arg2;
+ (id)filenameForKey:(id)arg1 width:(int)arg2 height:(int)arg3;
+ (id)internalImageForKey:(id)arg1;
+ (void)rescanFiles;
+ (void)rescanFilesIfNeeded;
+ (void)setNeedsRescanFiles;
+ (id)mmappedFilesDirectory;
+ (void)setImage:(id)arg1 forKey:(id)arg2;
+ (id)imageForKey:(id)arg1;
+ (BOOL)hasImageForKey:(id)arg1;
+ (void)initialize;

@end

