//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAChatDataStoreCoordinator.h"

@class NSMutableDictionary, NSString, WABackgroundConnectionAvailableNotifier, WAMediaUploader, WAPersistentKeyValueStore, WASignalManager, XMPPConnection;

@interface WAMessagingService : WAChatDataStoreCoordinator
{
    NSMutableDictionary *_chatJidToSendQueue;
    NSMutableDictionary *_retryMessagePool;
    WABackgroundConnectionAvailableNotifier *_bgNotifier;
    unsigned int _backgroundTaskIdentifier;
    NSString *_chatConnectionIdentifier;
    NSString *_uploadAttemptIdentifier;
    BOOL _uploadPingInProgress;
    BOOL _connectionReady;
    XMPPConnection *_xmppConnection;
    WASignalManager *_signalManager;
    WAMediaUploader *_mediaUploader;
    WAPersistentKeyValueStore *_keyValueStore;
}

+ (id)persistentTaskKeyForParentMessageId:(id)arg1 participant:(id)arg2;
+ (BOOL)uploadTaskIsSmall:(id)arg1;
+ (BOOL)nextSendTaskBatchable:(id)arg1 withLastSendTask:(id)arg2;
@property(readonly, nonatomic) WAPersistentKeyValueStore *keyValueStore; // @synthesize keyValueStore=_keyValueStore;
@property(readonly, nonatomic) WAMediaUploader *mediaUploader; // @synthesize mediaUploader=_mediaUploader;
@property(readonly, nonatomic) WASignalManager *signalManager; // @synthesize signalManager=_signalManager;
@property(readonly, nonatomic) XMPPConnection *xmppConnection; // @synthesize xmppConnection=_xmppConnection;
- (void).cxx_destruct;
- (void)updateUploadAttemptIdentifierAndRetryFailedUploads:(id)arg1;
- (void)didChangeDataStoreReadiness;
- (void)xmppConnectionStateDidChange:(id)arg1;
- (void)chatStorageDidDeleteMessages:(id)arg1;
- (void)updateMessageSendDateForMessages:(id)arg1;
- (void)updateBackgroundExecutionStateIfNeeded;
- (void)resendAllMessages;
- (void)encryptAndSendMessageTask:(id)arg1 participant:(id)arg2 retryCount:(unsigned int)arg3 completion:(CDUnknownBlockType)arg4;
- (BOOL)canSendMessages;
- (id)payNodeForMessage:(id)arg1 paymentTransaction:(id)arg2 paymentTransactionCache:(id)arg3;
- (BOOL)didFinishUploadForMessage:(id)arg1 withError:(id)arg2 terminal:(BOOL)arg3;
- (void)didFinishUploadForMessage:(id)arg1;
- (void)didCancelUploadForMessage:(id)arg1;
- (id)didReceiveServerAckForMessageWithId:(id)arg1 participant:(id)arg2 negativeAck:(BOOL)arg3;
- (void)asyncLoadSavedRetryMessageTasks;
- (void)completeRetryMessageTaskWithMessageId:(id)arg1 participant:(id)arg2;
- (void)addToInMemoryCollectionAndSendRetryMessage:(id)arg1 participant:(id)arg2 retryCount:(unsigned int)arg3;
- (void)retryMessageWithMessageId:(id)arg1 participant:(id)arg2 recipientRegistrationId:(id)arg3 retryCount:(unsigned int)arg4;
- (void)loadPendingMessages;
- (void)bumpSendQueueWithChatJid:(id)arg1;
- (BOOL)completePendingMessageTaskWithMessageId:(id)arg1 sendSuccess:(BOOL)arg2 returnedMessage:(id *)arg3;
- (BOOL)completePendingMessageTaskWithMessageId:(id)arg1 sendSuccess:(BOOL)arg2;
- (void)failPendingMessageTaskWithMessageId:(id)arg1 message:(id)arg2;
- (void)insertAndStartQueueForTask:(id)arg1;
- (void)cancelSendForMessage:(id)arg1;
- (void)retryUploadForMessage:(id)arg1;
- (void)sendMessageGroup:(id)arg1;
- (void)sendMessageWithInProgressUpload:(id)arg1;
- (void)sendMessage:(id)arg1;
- (void)handleBackgroundSessionEventCompletionHandler:(CDUnknownBlockType)arg1;
- (void)asyncLoadPendingMessages;
- (id)initWithChatDataStores:(id)arg1 xmppConnection:(id)arg2 signalManager:(id)arg3 mediaUploader:(id)arg4 keyValueStore:(id)arg5;

@end

