//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WASearchEngine.h"

@class NSPredicate;

@interface WAMessageSearchEngine : WASearchEngine
{
    NSPredicate *_predicateForIndexableMessages;
}

- (void).cxx_destruct;
- (id)searchResultOrderColumn;
- (id)metadataFieldsToSelect;
- (id)extraColumnsForFullTextSearch;
- (id)newlyAddedMetadataColumns;
- (id)extraMetadataColumns;
- (void)didIndexObject:(id)arg1 docID:(id)arg2;
- (void)didFailToIndexObject:(id)arg1 docID:(id)arg2;
- (BOOL)executeMetadataInsertTo:(id)arg1 docID:(long long)arg2 userInfo:(id)arg3;
- (long long)docIDForObject:(id)arg1;
- (id)executeInsertTo:(id)arg1 object:(id)arg2 contents:(id)arg3 timeShift:(double)arg4;
- (id)indexableContentForObject:(id)arg1;
- (BOOL)isValidObject:(id)arg1;
- (BOOL)internalIsIndexReady;
- (id)restrictionsWithMinimumScore:(float)arg1 chatJIDs:(id)arg2 type:(int)arg3;
- (id)fetchRequestForMessages;
- (void)markIndexReady;
- (id)docIDsMatchingSearchTerm:(id)arg1 chatSessionJIDs:(id)arg2 minimumScore:(float)arg3 type:(int)arg4 offset:(unsigned int)arg5 limit:(unsigned int)arg6;
- (id)totalCountOfMessagesMatchingSearchTerm:(id)arg1 chatSessionJIDs:(id)arg2 type:(int)arg3;
- (BOOL)indexMessages:(id)arg1;
- (int)indexMessagesOfCount:(unsigned int)arg1 inContext:(id)arg2;
- (void)setMessageDocumentType:(int)arg1 ofDocIDs:(id)arg2;
- (void)updateSearchScoreForMessage:(id)arg1;
- (id)init;

@end

