//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@class NSString;

@interface WamEventDaily : WamEvent
{
    NSString *_os_build_number;
    NSString *_language_code;
    NSString *_location_code;
    double _live_location_sharing_t;
    double _live_location_reporting_t;
    double _icloud_backup_interval;
    double _auto_dl_image_wifi;
    double _auto_dl_image_cellular;
    double _auto_dl_image_roaming;
    double _auto_dl_audio_wifi;
    double _auto_dl_audio_cellular;
    double _auto_dl_audio_roaming;
    double _auto_dl_video_wifi;
    double _auto_dl_video_cellular;
    double _auto_dl_video_roaming;
    double _auto_dl_doc_wifi;
    double _auto_dl_doc_cellular;
    double _auto_dl_doc_roaming;
    double _sim_mcc;
    double _sim_mnc;
    double _network_is_roaming;
    double _receipts_enabled;
    double _backup_schedule;
    double _backup_network_setting;
    double _addressbook_size;
    double _addressbook_whatsapp_size;
    double _individual_chat_count;
    double _individual_archived_chat_count;
    double _group_chat_count;
    double _group_archived_chat_count;
    double _broadcast_chat_count;
    double _broadcast_archived_chat_count;
    double _chat_database_size;
    double _media_folder_size;
    double _media_folder_file_count;
    double _video_folder_size;
    double _video_folder_file_count;
    double _db_messages_cnt;
    double _db_messages_unindexed_cnt;
    double _db_messages_starred_cnt;
    double _db_messages_indexed_pct;
    double _iphone_jailbroken;
    double _iphone_icloud_signed_in;
    double _db_search_fts;
    double _storage_avail_size;
    double _storage_total_size;
    double _iphone_camera_roll_photo_cnt;
    double _iphone_camera_roll_video_cnt;
}

@property(nonatomic) double iphone_camera_roll_video_cnt; // @synthesize iphone_camera_roll_video_cnt=_iphone_camera_roll_video_cnt;
@property(nonatomic) double iphone_camera_roll_photo_cnt; // @synthesize iphone_camera_roll_photo_cnt=_iphone_camera_roll_photo_cnt;
@property(nonatomic) double storage_total_size; // @synthesize storage_total_size=_storage_total_size;
@property(nonatomic) double storage_avail_size; // @synthesize storage_avail_size=_storage_avail_size;
@property(nonatomic) double db_search_fts; // @synthesize db_search_fts=_db_search_fts;
@property(nonatomic) double iphone_icloud_signed_in; // @synthesize iphone_icloud_signed_in=_iphone_icloud_signed_in;
@property(nonatomic) double iphone_jailbroken; // @synthesize iphone_jailbroken=_iphone_jailbroken;
@property(nonatomic) double db_messages_indexed_pct; // @synthesize db_messages_indexed_pct=_db_messages_indexed_pct;
@property(nonatomic) double db_messages_starred_cnt; // @synthesize db_messages_starred_cnt=_db_messages_starred_cnt;
@property(nonatomic) double db_messages_unindexed_cnt; // @synthesize db_messages_unindexed_cnt=_db_messages_unindexed_cnt;
@property(nonatomic) double db_messages_cnt; // @synthesize db_messages_cnt=_db_messages_cnt;
@property(nonatomic) double video_folder_file_count; // @synthesize video_folder_file_count=_video_folder_file_count;
@property(nonatomic) double video_folder_size; // @synthesize video_folder_size=_video_folder_size;
@property(nonatomic) double media_folder_file_count; // @synthesize media_folder_file_count=_media_folder_file_count;
@property(nonatomic) double media_folder_size; // @synthesize media_folder_size=_media_folder_size;
@property(nonatomic) double chat_database_size; // @synthesize chat_database_size=_chat_database_size;
@property(nonatomic) double broadcast_archived_chat_count; // @synthesize broadcast_archived_chat_count=_broadcast_archived_chat_count;
@property(nonatomic) double broadcast_chat_count; // @synthesize broadcast_chat_count=_broadcast_chat_count;
@property(nonatomic) double group_archived_chat_count; // @synthesize group_archived_chat_count=_group_archived_chat_count;
@property(nonatomic) double group_chat_count; // @synthesize group_chat_count=_group_chat_count;
@property(nonatomic) double individual_archived_chat_count; // @synthesize individual_archived_chat_count=_individual_archived_chat_count;
@property(nonatomic) double individual_chat_count; // @synthesize individual_chat_count=_individual_chat_count;
@property(nonatomic) double addressbook_whatsapp_size; // @synthesize addressbook_whatsapp_size=_addressbook_whatsapp_size;
@property(nonatomic) double addressbook_size; // @synthesize addressbook_size=_addressbook_size;
@property(nonatomic) double backup_network_setting; // @synthesize backup_network_setting=_backup_network_setting;
@property(nonatomic) double backup_schedule; // @synthesize backup_schedule=_backup_schedule;
@property(nonatomic) double receipts_enabled; // @synthesize receipts_enabled=_receipts_enabled;
@property(nonatomic) double network_is_roaming; // @synthesize network_is_roaming=_network_is_roaming;
@property(copy, nonatomic) NSString *location_code; // @synthesize location_code=_location_code;
@property(copy, nonatomic) NSString *language_code; // @synthesize language_code=_language_code;
@property(copy, nonatomic) NSString *os_build_number; // @synthesize os_build_number=_os_build_number;
@property(nonatomic) double sim_mnc; // @synthesize sim_mnc=_sim_mnc;
@property(nonatomic) double sim_mcc; // @synthesize sim_mcc=_sim_mcc;
@property(nonatomic) double auto_dl_doc_roaming; // @synthesize auto_dl_doc_roaming=_auto_dl_doc_roaming;
@property(nonatomic) double auto_dl_doc_cellular; // @synthesize auto_dl_doc_cellular=_auto_dl_doc_cellular;
@property(nonatomic) double auto_dl_doc_wifi; // @synthesize auto_dl_doc_wifi=_auto_dl_doc_wifi;
@property(nonatomic) double auto_dl_video_roaming; // @synthesize auto_dl_video_roaming=_auto_dl_video_roaming;
@property(nonatomic) double auto_dl_video_cellular; // @synthesize auto_dl_video_cellular=_auto_dl_video_cellular;
@property(nonatomic) double auto_dl_video_wifi; // @synthesize auto_dl_video_wifi=_auto_dl_video_wifi;
@property(nonatomic) double auto_dl_audio_roaming; // @synthesize auto_dl_audio_roaming=_auto_dl_audio_roaming;
@property(nonatomic) double auto_dl_audio_cellular; // @synthesize auto_dl_audio_cellular=_auto_dl_audio_cellular;
@property(nonatomic) double auto_dl_audio_wifi; // @synthesize auto_dl_audio_wifi=_auto_dl_audio_wifi;
@property(nonatomic) double auto_dl_image_roaming; // @synthesize auto_dl_image_roaming=_auto_dl_image_roaming;
@property(nonatomic) double auto_dl_image_cellular; // @synthesize auto_dl_image_cellular=_auto_dl_image_cellular;
@property(nonatomic) double auto_dl_image_wifi; // @synthesize auto_dl_image_wifi=_auto_dl_image_wifi;
@property(nonatomic) double icloud_backup_interval; // @synthesize icloud_backup_interval=_icloud_backup_interval;
@property(nonatomic) double live_location_reporting_t; // @synthesize live_location_reporting_t=_live_location_reporting_t;
@property(nonatomic) double live_location_sharing_t; // @synthesize live_location_sharing_t=_live_location_sharing_t;
- (void).cxx_destruct;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

