//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@interface WamEventVideoPlay : WamEvent
{
    double _video_initial_buffering_t;
    double _video_duration;
    double _video_size;
    double _video_play_t;
    double _video_age;
    double _video_play_type;
    double _video_play_result;
    double _video_play_surface;
    double _video_play_origin;
}

@property(nonatomic) double video_play_origin; // @synthesize video_play_origin=_video_play_origin;
@property(nonatomic) double video_play_surface; // @synthesize video_play_surface=_video_play_surface;
@property(nonatomic) double video_play_result; // @synthesize video_play_result=_video_play_result;
@property(nonatomic) double video_play_type; // @synthesize video_play_type=_video_play_type;
@property(nonatomic) double video_age; // @synthesize video_age=_video_age;
@property(nonatomic) double video_play_t; // @synthesize video_play_t=_video_play_t;
@property(nonatomic) double video_size; // @synthesize video_size=_video_size;
@property(nonatomic) double video_duration; // @synthesize video_duration=_video_duration;
@property(nonatomic) double video_initial_buffering_t_milliseconds; // @synthesize video_initial_buffering_t_milliseconds=_video_initial_buffering_t;
@property(nonatomic) double video_initial_buffering_t_seconds;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

