//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@protocol WANotificationSnippetDelegate;

@interface WANotificationSnippet : UIView
{
    BOOL _shouldExpand;
    BOOL _contentExpanded;
    BOOL _allowsReplying;
    id <WANotificationSnippetDelegate> _delegate;
    float _collapsedHeight;
    UIView *_backgroundView;
    UIView *_contentView;
    float _expandedHeight;
}

+ (float)preferredHeightForInterfaceOrientation:(int)arg1;
+ (void)initialize;
@property(nonatomic) float expandedHeight; // @synthesize expandedHeight=_expandedHeight;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) float collapsedHeight; // @synthesize collapsedHeight=_collapsedHeight;
@property(nonatomic) BOOL allowsReplying; // @synthesize allowsReplying=_allowsReplying;
@property(nonatomic) BOOL contentExpanded; // @synthesize contentExpanded=_contentExpanded;
@property(nonatomic) BOOL shouldExpand; // @synthesize shouldExpand=_shouldExpand;
@property(nonatomic) __weak id <WANotificationSnippetDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)closeAction:(id)arg1;
- (void)contentViewTouchUp:(id)arg1;
- (void)contentViewAnyTouch:(id)arg1;
- (id)initWithOrientation:(int)arg1;

@end

