//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAChatStorageManagedObject.h"

@class NSData, NSDate, NSString, UIColor, WAMessageID, WAPaymentTransactionCache, WAPaymentTransactionMetadata;
@protocol WAServerDate;

@interface WAPaymentTransaction : WAChatStorageManagedObject
{
    WAPaymentTransactionMetadata *_decodedMetadata;
}

+ (id)fetchRequest;
+ (id)entityName;
- (void).cxx_destruct;
- (id)seqNumber;
@property(readonly) WAPaymentTransactionCache *cache;
@property(copy, nonatomic) WAPaymentTransactionMetadata *decodedMetadata;
@property(readonly, nonatomic) UIColor *statusColor;
- (id)statusForImageWithSize:(struct CGSize)arg1;
- (id)statusForDisplayInSlice;
- (id)statusForDisplay;
- (id)receiverJIDForChat;
@property(readonly, nonatomic) NSString *transactionMonth;
@property(readonly, nonatomic) NSDate<WAServerDate> *expiryTimestamp;
@property(nonatomic) double amountForStanza;
@property(readonly, copy, nonatomic) NSString *amountWithCurrency;
@property(readonly, nonatomic, getter=isReplyable) BOOL replyable;
@property(readonly, nonatomic, getter=isCompleted) BOOL completed;
@property(readonly, nonatomic, getter=isSendable) BOOL sendable;
@property(readonly, nonatomic, getter=isFromMe) BOOL fromMe;
@property(readonly, nonatomic, getter=isToMe) BOOL toMe;
@property(readonly, nonatomic, getter=isP2P) BOOL p2p;
@property(retain, nonatomic) WAMessageID *messageID;

// Remaining properties
@property(nonatomic) long long amount_1000; // @dynamic amount_1000;
@property(copy, nonatomic) NSString *bankTransactionId; // @dynamic bankTransactionId;
@property(copy, nonatomic) NSString *credentialId; // @dynamic credentialId;
@property(copy, nonatomic) NSString *currency; // @dynamic currency;
@property(copy, nonatomic) NSString *errorCode; // @dynamic errorCode;
@property(copy, nonatomic) NSString *groupJID; // @dynamic groupJID;
@property(copy, nonatomic) NSString *messageStanzaId; // @dynamic messageStanzaId;
@property(copy, nonatomic) NSData *metadata; // @dynamic metadata;
@property(copy, nonatomic) NSString *receiverJID; // @dynamic receiverJID;
@property(copy, nonatomic) NSString *senderJID; // @dynamic senderJID;
@property(nonatomic) long long status; // @dynamic status;
@property(copy, nonatomic) NSDate<WAServerDate> *timestamp; // @dynamic timestamp;
@property(copy, nonatomic) NSString *transactionId; // @dynamic transactionId;
@property(nonatomic) long long type; // @dynamic type;

@end

