//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WAPaintBrushStrokeInterpolator : NSObject
{
    CDUnknownBlockType _handler;
    // Error parsing type: , name: _color
}

// Error parsing type for property color:
// Property attributes: T,R,N,V_color

- (void).cxx_destruct;
-     // Error parsing type: v20@0:4^8f12^16, name: addPaintBlobAtPosition:angle:size:
- (void)finalize;
- (BOOL)addPositionSample:(id)arg1 discardable:(BOOL)arg2;
-     // Error parsing type: @20@0:4^8f12@?16, name: initWithColor:pixelsPerUnit:handler:

@end

