//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSDate, NSString;
@protocol WAServerDate;

@interface WAPaymentTransactionMetadata : NSObject <NSSecureCoding, NSCopying>
{
    NSDate<WAServerDate> *_expiryTimestamp;
    NSString *_seqNumber;
    NSDate<WAServerDate> *_lastStatusTimestamp;
    long long _previousStatus;
}

+ (BOOL)supportsSecureCoding;
@property(nonatomic) long long previousStatus; // @synthesize previousStatus=_previousStatus;
@property(retain, nonatomic) NSDate<WAServerDate> *lastStatusTimestamp; // @synthesize lastStatusTimestamp=_lastStatusTimestamp;
@property(copy, nonatomic) NSString *seqNumber; // @synthesize seqNumber=_seqNumber;
@property(retain, nonatomic) NSDate<WAServerDate> *expiryTimestamp; // @synthesize expiryTimestamp=_expiryTimestamp;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isEmpty) BOOL empty;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

