//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MTLRenderPassDescriptor, NSArray, NSMutableArray, WAPaintBrushRenderer, WAWeakTimer;
@protocol MTLTexture, WAPaintCanvasLayerDelegate;

@interface WAPaintCanvasLayer : NSObject
{
    id <MTLTexture> _snapshotTexture;
    id <MTLTexture> _texture;
    MTLRenderPassDescriptor *_renderPassDescriptor;
    NSMutableArray *_renderers;
    WAWeakTimer *_redrawTimer;
    id <WAPaintCanvasLayerDelegate> _delegate;
    struct CGSize _size;
}

@property(readonly, nonatomic) NSArray *renderers; // @synthesize renderers=_renderers;
@property(readonly, nonatomic) id <MTLTexture> texture; // @synthesize texture=_texture;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(nonatomic) __weak id <WAPaintCanvasLayerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
-     // Error parsing type: c80@0:4@8^12^16^20{?=[3]}24o^@72o^I76, name: getRendererWithCommandQueue:atP0:p1:pMid:transformMatrix:renderer:index:
-     // Error parsing type: {?={?=III}{?=III}}16@0:4^8@12, name: regionWithPoint:inTexture:
- (void)checkNeedsRedraw:(id)arg1;
- (void)renderersDidChange;
- (id)notDeletedRenderers;
- (void)undoStroke:(id)arg1;
- (void)addSingleRendererStrokeIfNeeded:(id)arg1;
- (BOOL)containsRenderer:(id)arg1;
- (void)removeAllRenderers;
@property(readonly, nonatomic) WAPaintBrushRenderer *currentRenderer;
- (id)addNewRendererWithBrush:(id)arg1 effectValue:(float)arg2;
- (void)prepareForRenderingWithBrush:(id)arg1 effectValue:(float)arg2;
-     // Error parsing type: v96@0:4@8{?=[3]}12{?={CGSize=ff}{CGPoint=ff}f}60f80c84c88@92, name: renderInCommandBuffer:withTransformMatrix:transformInfo:fullCanvasAspectRatio:sinceLastSnapshot:snapshotWhenDone:beforeRendering:
- (id)renderPassDescriptorWithTexture:(id)arg1 loadAction:(unsigned int)arg2;
@property(readonly, nonatomic, getter=isEmpty) BOOL empty;
- (id)init;

@end

