//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface WAPBHighlyStructuredMessagePack_HighlyStructuredMessageTranslation_HighlyStructuredMessageElement : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *elementName; // @dynamic elementName;
@property(nonatomic) BOOL hasElementName; // @dynamic hasElementName;
@property(nonatomic) BOOL hasNamespace_p; // @dynamic hasNamespace_p;
@property(nonatomic) BOOL hasNumParams; // @dynamic hasNumParams;
@property(copy, nonatomic) NSString *namespace_p; // @dynamic namespace_p;
@property(nonatomic) unsigned int numParams; // @dynamic numParams;

@end

