//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSDate, NSError;

@interface WAPersistentRequestInput : NSObject <NSSecureCoding, NSCopying>
{
    NSDate *_retryUntil;
    NSDate *_executeAfter;
    int _maxRetryCount;
    int _currentRetryCount;
    NSError *_previousError;
}

+ (BOOL)supportsSecureCoding;
@property(retain, nonatomic) NSError *previousError; // @synthesize previousError=_previousError;
@property(nonatomic) int currentRetryCount; // @synthesize currentRetryCount=_currentRetryCount;
@property(nonatomic) int maxRetryCount; // @synthesize maxRetryCount=_maxRetryCount;
@property(retain, nonatomic) NSDate *executeAfter; // @synthesize executeAfter=_executeAfter;
@property(retain, nonatomic) NSDate *retryUntil; // @synthesize retryUntil=_retryUntil;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithRetryUntil:(id)arg1 executeAfter:(id)arg2 maxRetryCount:(int)arg3 currentRetryCount:(int)arg4 previousError:(id)arg5;
- (id)initWithRetryUntil:(id)arg1 executeAfter:(id)arg2 maxRetryCount:(int)arg3;
- (id)init;

@end

