//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIActivityIndicatorView, UIButton, UIImageView;
@protocol WAProfilePictureParallaxViewDelegate;

@interface WAProfilePictureParallaxView : UIView
{
    BOOL _displayingPlaceholder;
    BOOL _needsLoadPicture;
    UIView *_backgroundView;
    UIView *_verticalEdgeView;
    UIView *_dimmerView;
    UIActivityIndicatorView *_activityIndicator;
    float _centerOffset;
    BOOL _pictureFetchAllowed;
    BOOL _picturePlaceholderAllowed;
    id <WAProfilePictureParallaxViewDelegate> _delegate;
    NSString *_jid;
    UIButton *_editButton;
    UIImageView *_imageView;
    float _visibleHeight;
}

+ (void)initialize;
@property(nonatomic) float visibleHeight; // @synthesize visibleHeight=_visibleHeight;
@property(nonatomic) BOOL picturePlaceholderAllowed; // @synthesize picturePlaceholderAllowed=_picturePlaceholderAllowed;
@property(nonatomic) BOOL pictureFetchAllowed; // @synthesize pictureFetchAllowed=_pictureFetchAllowed;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIButton *editButton; // @synthesize editButton=_editButton;
@property(copy, nonatomic) NSString *jid; // @synthesize jid=_jid;
@property(nonatomic) __weak id <WAProfilePictureParallaxViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)resetTemporaryPicture;
- (void)showTemporaryPicture:(id)arg1;
- (void)hideActivityIndicator;
- (void)showActivityIndicator;
@property(nonatomic) BOOL showVerticalTrailingEdge;
- (void)reloadSelfAsTableHeaderView;
- (void)loadPlaceholderImage;
- (void)loadProfilePicture:(id)arg1;
- (void)detectFaceInImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)reloadPSAProfilePicture;
- (void)setImage:(id)arg1;
- (id)image;
@property(readonly, nonatomic) BOOL hasImage;
- (void)profilePictureChanged:(id)arg1;
- (void)reloadPictureAndRequestRefresh:(BOOL)arg1;
- (void)reloadPictureIfNeeded;
- (void)getFullsizePictureRequestDidComplete:(id)arg1;
- (void)handleReceivedFullsizeProfilePicture:(id)arg1;
@property(nonatomic) BOOL editButtonHidden;
@property(readonly, nonatomic) float defaultVisibleHeight;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)didMoveToSuperview;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

