//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSString, UIImage, UIImageView, WAButtonLabel;
@protocol WARoundButtonDelegate;

@interface WARoundButton : UIButton
{
    WAButtonLabel *_bottomLabel;
    UIImageView *_mask;
    UIImageView *_whiteImageView;
    UIImageView *_blackImageView;
    UIImageView *_blurredImageView;
    BOOL _pressed;
    BOOL _selectable;
    UIImage *_iconImage;
    id <WARoundButtonDelegate> _delegate;
    int _theme;
}

+ (id)button;
@property(nonatomic) int theme; // @synthesize theme=_theme;
@property(nonatomic) __weak id <WARoundButtonDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=isSelectable) BOOL selectable; // @synthesize selectable=_selectable;
@property(retain, nonatomic) UIImage *iconImage; // @synthesize iconImage=_iconImage;
- (void).cxx_destruct;
- (id)accessibilityValue;
- (void)sendAction:(SEL)arg1 to:(id)arg2 forEvent:(id)arg3;
- (void)setEnabled:(BOOL)arg1;
- (void)setSelected:(BOOL)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (void)updateButtonState;
- (void)setPressed:(BOOL)arg1;
@property(nonatomic) BOOL bottomLabelHidden;
@property(copy, nonatomic) NSString *bottomLabelText;
- (void)updateBlurredImage;
- (void)setCenter:(struct CGPoint)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

