//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSIndexSet, NSNumber, WASearchResultsController;

@protocol WASearchResultsControllerDelegate <NSObject>
- (void)searchResultsControllerDidReloadData:(WASearchResultsController *)arg1;
- (void)searchResultsControllerDidChangeContent:(WASearchResultsController *)arg1;
- (void)searchResultsController:(WASearchResultsController *)arg1 didDeleteSections:(NSIndexSet *)arg2;
- (void)searchResultsController:(WASearchResultsController *)arg1 didInsertSections:(NSIndexSet *)arg2;
- (void)searchResultsController:(WASearchResultsController *)arg1 didUpdateRowsAtIndexPaths:(NSArray *)arg2;
- (void)searchResultsController:(WASearchResultsController *)arg1 didDeleteRowsAtIndexPaths:(NSArray *)arg2;
- (void)searchResultsController:(WASearchResultsController *)arg1 didInsertRowsAtIndexPaths:(NSArray *)arg2;
- (void)searchResultsControllerWillChangeContent:(WASearchResultsController *)arg1;
- (BOOL)searchResultsControllerShouldReloadData:(WASearchResultsController *)arg1;
- (BOOL)searchResultsController:(WASearchResultsController *)arg1 shouldLoadAsynchronously:(unsigned int)arg2;

@optional
- (void)searchResultsController:(WASearchResultsController *)arg1 didCountSearchTermMatches:(NSNumber *)arg2;
@end

