//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface WASimpleOperationQueue : NSObject
{
    NSMutableArray *_pendingOperations;
    NSMutableArray *_runningOperations;
    unsigned int _maxConcurrentOperations;
}

@property(readonly, nonatomic) unsigned int maxConcurrentOperations; // @synthesize maxConcurrentOperations=_maxConcurrentOperations;
- (void).cxx_destruct;
- (void)runAvailableOperations;
- (id)filterOperations:(CDUnknownBlockType)arg1;
- (void)enumerateOperations:(CDUnknownBlockType)arg1;
- (id)removeAllOperations;
- (void)removeOperation:(id)arg1;
- (void)addOperations:(id)arg1;
- (void)addOperation:(id)arg1;
- (BOOL)isOperationRunning:(id)arg1;
@property(readonly, nonatomic) unsigned int count;
- (id)initWithMaxConcurrentOperations:(unsigned int)arg1;

@end

