//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WASQLObject.h"

@class WAJID;

@interface WASQLProgress : WASQLObject
{
    BOOL _completed;
    WAJID *_jid;
    int _value;
}

+ (float)overallProgressFromDB:(struct sqlite3 *)arg1;
+ (BOOL)updateOverallProgress:(float)arg1 inDB:(struct sqlite3 *)arg2;
+ (id)selectProgressForJID:(id)arg1 fromDB:(struct sqlite3 *)arg2;
+ (id)incompleteChatJIDsAfter:(id)arg1 limit:(unsigned int)arg2 fromDB:(struct sqlite3 *)arg3;
+ (id)tableName;
+ (BOOL)createTableIfNecessaryInDB:(struct sqlite3 *)arg1;
@property(readonly, nonatomic) BOOL completed; // @synthesize completed=_completed;
@property(readonly, nonatomic) int value; // @synthesize value=_value;
@property(readonly, nonatomic) WAJID *jid; // @synthesize jid=_jid;
- (void).cxx_destruct;
- (id)description;
- (BOOL)bindAllValuesToStatement:(id)arg1;
- (id)allValues;
- (BOOL)populateWithDictionary:(id)arg1;
- (id)initWithJID:(id)arg1 value:(int)arg2 completed:(BOOL)arg3;
- (id)initWithJID:(id)arg1;

@end

