//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WAStickerListTableViewCellDelegate-Protocol.h"

@class NSArray, NSString, UIActivityIndicatorView, UITableView, UIView;
@protocol WAStickerListHelper, WAStickerListTableViewControllerDelegate;

@interface WAStickerListTableViewController : WAViewController <UITableViewDataSource, UITableViewDelegate, WAStickerListTableViewCellDelegate>
{
    id <WAStickerListHelper> _helper;
    NSArray *_stickerPacks;
    UIActivityIndicatorView *_activityIndicatorView;
    UITableView *_tableView;
    UIView *_emptyScreenView;
    UIView *_errorScreenView;
    id <WAStickerListTableViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <WAStickerListTableViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateTableViewFromStickerListTableViewCell:(id)arg1;
- (BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)hideErrorScreenView;
- (void)hideEmptyScreenView;
- (void)hideTableView;
- (void)showErrorScreenView;
- (void)showEmptyScreenView;
- (void)showTableView;
- (void)getStickerPacks;
- (void)loadView;
- (void)reloadTableView:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithHelper:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

