//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSString, UIButton, UILabel, UIPanGestureRecognizer, UITableView, WAGrabHandleView, WAMessage;
@protocol WAStatusViewerSeenByViewDelegate;

@interface WAStatusViewerSeenByView : UIView <UITableViewDelegate, UITableViewDataSource, UIGestureRecognizerDelegate>
{
    UIView *_backgroundView;
    UIView *_headerSeparatorView;
    NSArray *_users;
    UITableView *_tableView;
    UILabel *_headerLabel;
    UILabel *_whiteHeaderLabel;
    WAGrabHandleView *_grabHandleView;
    UIButton *_forwardButton;
    UIButton *_removeButton;
    UIPanGestureRecognizer *_panGestureInTableView;
    BOOL _tableUpdateScheduled;
    WAMessage *_message;
    float _expandedPercentage;
    id <WAStatusViewerSeenByViewDelegate> _delegate;
}

@property(nonatomic) __weak id <WAStatusViewerSeenByViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) float expandedPercentage; // @synthesize expandedPercentage=_expandedPercentage;
@property(retain, nonatomic) WAMessage *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)handleMessageUpdated:(id)arg1;
- (void)handleMessageDeliveryStatusChanged:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)seenUsersForMessage:(id)arg1;
- (void)updateTable;
- (void)updatedMessage;
- (void)removeButtonTapped:(id)arg1;
- (void)forwardButtonTapped:(id)arg1;
- (void)handleDismissGesture:(id)arg1;
- (void)handlePanGesture:(id)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

