//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WAStatusHeaderViewDelegate-Protocol.h"
#import "WAStatusItemViewDelegate-Protocol.h"
#import "WAStatusViewerFooterViewDelegate-Protocol.h"

@class NSMapTable, NSString, UIImageView, WABubbleTextView, WAMessage, WAStatusHeaderView, WAStatusItemView, WAStatusProgressView, WAStatusViewerFooterView, WAStatusViewerSection;
@protocol WAStatusViewerSectionViewDelegate;

@interface WAStatusViewerSectionView : UIView <WAStatusItemViewDelegate, WAStatusHeaderViewDelegate, WAStatusViewerFooterViewDelegate>
{
    NSMapTable *_recycledViews;
    UIImageView *_gradientTopView;
    UIImageView *_gradientLeftView;
    WAStatusItemView *_itemView;
    WAStatusProgressView *_progressView;
    WAStatusHeaderView *_headerView;
    WAStatusViewerFooterView *_footerView;
    WABubbleTextView *_replySendingView;
    WAMessage *_lastDisplayedMessage;
    UIView *_dimmingView;
    float _lastLayoutWidth;
    BOOL _paused;
    BOOL _audioMuted;
    BOOL _headerHidden;
    BOOL _footerHidden;
    WAStatusViewerSection *_section;
    id <WAStatusViewerSectionViewDelegate> _delegate;
    float _bottomInset;
}

@property(nonatomic, getter=isFooterHidden) BOOL footerHidden; // @synthesize footerHidden=_footerHidden;
@property(nonatomic, getter=isHeaderHidden) BOOL headerHidden; // @synthesize headerHidden=_headerHidden;
@property(nonatomic, getter=isAudioMuted) BOOL audioMuted; // @synthesize audioMuted=_audioMuted;
@property(nonatomic, getter=isPaused) BOOL paused; // @synthesize paused=_paused;
@property(nonatomic) float bottomInset; // @synthesize bottomInset=_bottomInset;
@property(nonatomic) __weak id <WAStatusViewerSectionViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WAStatusViewerSection *section; // @synthesize section=_section;
- (void).cxx_destruct;
- (void)statusViewerFooterViewDidChangeSize:(id)arg1;
- (void)headerView:(id)arg1 didRequestAudioVolumeChange:(float)arg2;
- (void)headerViewDidTapMoreOptions:(id)arg1;
- (void)headerViewDidTapDismiss:(id)arg1;
- (void)statusItemView:(id)arg1 didSelectInteractiveAnnotation:(id)arg2;
- (void)statusItemView:(id)arg1 didRequestOpenGroupLink:(id)arg2;
- (void)statusItemViewDidEndLoading:(id)arg1;
- (void)statusItemViewDidBeginLoading:(id)arg1;
- (void)statusItemViewDidRequestDownload:(id)arg1;
- (void)statusItemViewDidEndPreventingAdvancing:(id)arg1;
- (void)statusItemViewDidBeginPreventingAdvancing:(id)arg1;
- (void)statusItemViewDidEndUserInteraction:(id)arg1;
- (void)statusItemViewDidBeginUserInteraction:(id)arg1;
- (BOOL)canStatusItemViewReportFinishPresenting:(id)arg1;
- (void)statusItemViewDidRequestDismissViewer:(id)arg1;
- (void)statusItemViewDidFinishPresenting:(id)arg1;
- (void)statusItemViewDidUpdateProgress:(id)arg1;
- (void)mediaDownloadDidFail:(id)arg1;
- (id)statusViewOfClass:(Class)arg1;
- (id)dequeueStatusItemViewForMessage:(id)arg1;
- (void)recycleStatusItemView:(id)arg1;
- (void)setItemView:(id)arg1;
- (void)loadItemViewForMessage:(id)arg1;
- (void)handleMessageUpdated:(id)arg1;
- (void)handleMessageDeliveryStatusChanged:(id)arg1;
- (id)footerSeenByButtonTextForMessage:(id)arg1;
- (void)reloadIfNeeded;
- (void)checkNeedsAdvanceToNextMessageIfNeeded;
@property(nonatomic, getter=isLeftGradientHidden) BOOL leftGradientHidden;
@property(readonly, nonatomic, getter=isHandlingPanGesture) BOOL handlingPanGesture;
@property(nonatomic) float captionAlpha;
@property(nonatomic, getter=isCaptionExpanded) BOOL captionExpanded;
@property(readonly, nonatomic) BOOL canExpandCaption;
- (void)setReplySendingViewHidden:(BOOL)arg1;
- (void)rewind;
@property(readonly, nonatomic) float footerHeight;
@property(readonly, nonatomic) float footerBaseHeight;
@property(nonatomic) struct CGAffineTransform footerArrowTransform;
@property(nonatomic) float footerArrowAlpha;
@property(nonatomic) float brightness;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

