//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WATextMessageHelper.h"

@interface WAWebPageMessageHelper : WATextMessageHelper
{
}

+ (id)stringRepresentationForNotificationForMessage:(id)arg1;
+ (BOOL)needsImageLoader;
- (float)blurredImageMaximumWidth;
- (id)smallImageForMessageImageLoaderWithInfo:(id)arg1;

@end

