//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMPPStanza.h"

@class NSDate, NSString;

@interface XMPPMessageStanza : XMPPStanza
{
    NSDate *_timeOfArrival;
}

+ (id)ciphertextTypeForString:(id)arg1;
+ (id)stringForCiphertextType:(unsigned int)arg1;
+ (void)xmppMessageType:(out unsigned int *)arg1 xmppMediaType:(out unsigned int *)arg2 fromWAMessageType:(int)arg3 mediaOrigin:(int)arg4 multiVCard:(BOOL)arg5 payment:(BOOL)arg6;
+ (id)stringForMediaType:(unsigned int)arg1;
+ (id)encNodeForCiphertextPayload:(id)arg1 withMediaType:(unsigned int)arg2 retryCount:(unsigned int)arg3 locationSharingEndDate:(id)arg4;
+ (id)outgoingMessageStanzaToJid:(id)arg1 messageId:(id)arg2 participant:(id)arg3 messageType:(int)arg4 mediaOrigin:(int)arg5 phash:(id)arg6 retryCount:(unsigned int)arg7 multicast:(BOOL)arg8 multiVCard:(BOOL)arg9 payment:(BOOL)arg10 textFromURL:(BOOL)arg11 numberFromURL:(BOOL)arg12 locationSharingEndDate:(id)arg13 broadcastListName:(id)arg14 broadcastListParticipants:(id)arg15 withFanoutCiphertextPayload:(id)arg16 commonCiphertextPayload:(id)arg17;
+ (id)outgoingMessageStanzaForWAMessage:(id)arg1 withParticipant:(id)arg2 retryCount:(unsigned int)arg3 qCount:(unsigned int)arg4 withFanoutCiphertextPayload:(id)arg5 commonCiphertextPayload:(id)arg6;
+ (id)outgoingMessageStanzaForSharedItem:(id)arg1 withFanoutCiphertextPayload:(id)arg2 commonCiphertextPayload:(id)arg3;
+ (unsigned int)typeForString:(id)arg1;
+ (id)stringForType:(unsigned int)arg1;
+ (id)stringsForTypes;
@property(retain, nonatomic) NSDate *timeOfArrival; // @synthesize timeOfArrival=_timeOfArrival;
- (void).cxx_destruct;
- (id)log;
- (id)vcard;
- (id)body;
- (id)media;
- (void)setMediaOrigin:(unsigned int)arg1;
@property(readonly, nonatomic) unsigned int mediaOrigin;
@property(nonatomic) unsigned int type;
- (void)setMulticast:(BOOL)arg1;
@property(readonly, nonatomic) BOOL multicast;
@property(readonly, copy, nonatomic) NSString *uniqueKey;
@property(readonly, nonatomic) BOOL broadcast;
- (id)initWithFromJID:(id)arg1 toJID:(id)arg2 type:(unsigned int)arg3;

@end

