//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMPPStanza.h"

@class NSString;

@interface XMPPPresenceStanza : XMPPStanza
{
}

+ (unsigned int)presenceForString:(id)arg1;
+ (id)stringForPresence:(unsigned int)arg1;
+ (id)stringsForPresences;
+ (id)stanzaWithPresence:(unsigned int)arg1 nickname:(id)arg2;
- (id)log;
@property(copy, nonatomic) NSString *nickname;
@property(nonatomic) unsigned int presence;
- (id)initWithPresence:(unsigned int)arg1 toJID:(id)arg2;

@end

