//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAActionSheetPresenter.h"

@class UIViewController, UIWindow;

@interface _WAActionSheetPresenterOS8 : WAActionSheetPresenter
{
    UIViewController *_alertController;
    UIViewController *_retainedControllerBeforePresentation;
    UIWindow *_window;
    UIWindow *_applicationWindow;
}

- (void).cxx_destruct;
- (void)addCancelButton;
- (void)addButtonWithTitle:(id)arg1 image:(id)arg2 useBoldText:(BOOL)arg3 handler:(CDUnknownBlockType)arg4;
- (void)addDestructiveButtonWithTitle:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)addButtonWithTitle:(id)arg1 image:(id)arg2 style:(unsigned int)arg3 handler:(CDUnknownBlockType)arg4 toActionSheetController:(id)arg5;
- (void)addButtonWithTitle:(id)arg1 style:(int)arg2 handler:(CDUnknownBlockType)arg3 toAlertController:(id)arg4;
- (void)dismissByCancellingWithAnimation:(BOOL)arg1;
- (void)didDismissByCancelling:(BOOL)arg1;
- (void)presentFromViewController:(id)arg1;
- (id)initWithTitle:(id)arg1 message:(id)arg2;

@end

