//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class WAURLSessionTask;

@interface _WADeferredTaskOperation : NSObject
{
    BOOL _isAddOperation;
    WAURLSessionTask *_task;
}

@property(retain, nonatomic) WAURLSessionTask *task; // @synthesize task=_task;
@property(nonatomic) BOOL isAddOperation; // @synthesize isAddOperation=_isAddOperation;
- (void).cxx_destruct;

@end

