//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_WASearchResultSection.h"

@interface _WAMessagesResultSection : _WASearchResultSection
{
    unsigned int _ftsCursor;
    unsigned int _ftsBatchLimit;
}

@property(nonatomic) unsigned int ftsBatchLimit; // @synthesize ftsBatchLimit=_ftsBatchLimit;
@property(nonatomic) unsigned int ftsCursor; // @synthesize ftsCursor=_ftsCursor;
- (Class)objectClass;
- (id)chatSessionFor:(id)arg1;
- (BOOL)isObjectValid:(id)arg1;

@end

