//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAStaticTableViewController.h"

#import "UISearchDisplayDelegate-Protocol.h"

@class NSString, UISearchDisplayController, WAServerStatus, WATableRow, WATableSection;

@interface DebugViewController : WAStaticTableViewController <UISearchDisplayDelegate>
{
    WATableRow *_rowCurrentHost;
    WATableRow *_rowServerIP;
    WATableRow *_rowChatDBSize;
    WATableRow *_rowContactsDBSize;
    WATableRow *_rowOpusSWB;
    WATableRow *_rowOpusFB;
    WATableRow *_rowDeleteOrphanedMessages;
    WATableRow *_rowSelectedRestorableCheckpoint;
    WATableRow *_rowPerformLocalbackupRestore;
    WATableSection *_sectionGeneral;
    WATableRow *_row3DTouchSettings;
    WAServerStatus *_pendingServerStatus;
    UISearchDisplayController *_menuSearchDisplayController;
    WATableSection *_searchSection;
}

- (void).cxx_destruct;
- (void)searchDisplayController:(id)arg1 willShowSearchResultsTableView:(id)arg2;
- (void)searchDisplayController:(id)arg1 didLoadSearchResultsTableView:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)xmppConnectionStateDidChange:(id)arg1;
- (void)reconnect;
- (void)reloadConnectionInfo;
- (void)setupTableView;
- (void)deselectActiveSearchCell;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

