//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAViewController.h"

#import "UIScrollViewDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"

@class ImageListScrollView, NSMutableArray, NSString, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UISearchBar;
@protocol ImageSearchControllerDelegate;

@interface ImageSearchController : WAViewController <UIScrollViewDelegate, UISearchBarDelegate>
{
    BOOL _dismissOnApplicationDidEnterBackground;
    UISearchBar *_searchBar;
    ImageListScrollView *_scrollView;
    UIActivityIndicatorView *_activityIndicator;
    UILabel *_labelNoResults;
    UIButton *_buttonLoadMore;
    UIImageView *_bingAttribution;
    NSMutableArray *_imageURLs;
    NSMutableArray *_sourceURLs;
    NSMutableArray *_thumbnailViews;
    UIImageView *_highlightedImageView;
    int _searchOffset;
    int _resultsCount;
    NSString *_preloadedSearchText;
    id <ImageSearchControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <ImageSearchControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *preloadedSearchText; // @synthesize preloadedSearchText=_preloadedSearchText;
- (void).cxx_destruct;
- (void)processImageSearchResponseData:(id)arg1 error:(id)arg2;
- (void)doSearch:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (void)cancelAction:(id)arg1;
- (void)clearAction:(id)arg1;
- (void)loadMoreAction:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)layoutScrollviewSubviews;
- (void)addSearchResults:(id)arg1;
- (void)selectMediaAtIndex:(unsigned int)arg1;
- (void)resetSearchResults;
- (void)showActivity:(BOOL)arg1;
- (void)wa_applicationDidEnterBackground;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

