//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSArray, NSString;

@interface WABizProfileData : NSManagedObject
{
}


// Remaining properties
@property(copy, nonatomic) NSString *address; // @dynamic address;
@property(copy, nonatomic) NSString *businessDescription; // @dynamic businessDescription;
@property(copy, nonatomic) NSString *canonicalVertical; // @dynamic canonicalVertical;
@property(copy, nonatomic) NSString *email; // @dynamic email;
@property(copy, nonatomic) NSString *jid; // @dynamic jid;
@property(nonatomic) int tag; // @dynamic tag;
@property(copy, nonatomic) NSString *vertical; // @dynamic vertical;
@property(copy, nonatomic) NSArray *websites; // @dynamic websites;
@end

