//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAViewController.h"

@class NSNumber, NSTimer, UIButton, UILabel, UIView, WAChatStorage, WACircularProgressView;
@protocol WAChatDatabaseMigrationViewControllerDelegate;

@interface WAChatDatabaseMigrationViewController : WAViewController
{
    NSTimer *_progressTimer;
    double _estimatedMigrationTime;
    unsigned long long _databaseSize;
    double _migrationStartTime;
    NSNumber *_migrationStatus;
    BOOL _excessiveMigrationTimeLogUploaded;
    BOOL _needsMigration;
    WAChatStorage *_chatStorage;
    id <WAChatDatabaseMigrationViewControllerDelegate> _delegate;
    UIView *_viewMigrationProgress;
    UILabel *_labelOptimizingWhatsApp;
    WACircularProgressView *_circularProgressView;
    UILabel *_labelProgress;
    UIView *_viewNoSpace;
    UILabel *_labelNoSpace;
    UIButton *_buttonTryAgain;
}

+ (double)estimatedMigrationTimeForDatabaseSize:(unsigned long long)arg1;
@property(retain, nonatomic) UIButton *buttonTryAgain; // @synthesize buttonTryAgain=_buttonTryAgain;
@property(retain, nonatomic) UILabel *labelNoSpace; // @synthesize labelNoSpace=_labelNoSpace;
@property(retain, nonatomic) UIView *viewNoSpace; // @synthesize viewNoSpace=_viewNoSpace;
@property(retain, nonatomic) UILabel *labelProgress; // @synthesize labelProgress=_labelProgress;
@property(retain, nonatomic) WACircularProgressView *circularProgressView; // @synthesize circularProgressView=_circularProgressView;
@property(retain, nonatomic) UILabel *labelOptimizingWhatsApp; // @synthesize labelOptimizingWhatsApp=_labelOptimizingWhatsApp;
@property(retain, nonatomic) UIView *viewMigrationProgress; // @synthesize viewMigrationProgress=_viewMigrationProgress;
@property(nonatomic) __weak id <WAChatDatabaseMigrationViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) WAChatStorage *chatStorage; // @synthesize chatStorage=_chatStorage;
- (void).cxx_destruct;
- (void)tryAgain:(id)arg1;
- (void)updateProgress:(id)arg1;
- (void)didFinishMigrationWithStatus:(BOOL)arg1;
- (void)reallyPerformMigration;
- (void)postLaunchAppNotificationIfNeeded;
- (void)migrateIfPossible;
- (void)setNeedsMigration;
- (void)applicationDidResume:(id)arg1;
- (void)wa_applicationDidBecomeActive;
- (BOOL)hasSufficientDiskSpaceForMigration;
- (long long)requiredDiskSpace;
- (int)preferredStatusBarStyle;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithChatStorage:(id)arg1;

@end

