//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSLayoutConstraint, UIButton, UILabel;
@protocol WAChangeNumberPersistentNotificationViewDelegate;

@interface WAChangeNumberPersistentNotificationView : UIView
{
    UILabel *_textLabel;
    UIButton *_dismissButton;
    UIView *_borderView;
    NSLayoutConstraint *_widthConstraint;
    NSLayoutConstraint *_heightConstraint;
    NSLayoutConstraint *_buttonHeightConstraint;
    NSLayoutConstraint *_leadingInset;
    NSLayoutConstraint *_trailingInset;
    NSLayoutConstraint *_textToButtonConstraint;
    BOOL _tapEnabled;
    id <WAChangeNumberPersistentNotificationViewDelegate> _delegate;
}

@property(nonatomic) __weak id <WAChangeNumberPersistentNotificationViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL tapEnabled; // @synthesize tapEnabled=_tapEnabled;
- (void).cxx_destruct;
- (void)viewWasTapped:(id)arg1;
- (void)dismiss:(id)arg1;
- (void)updateText:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (float)maxTextLabelWidthForSuperviewWidth:(float)arg1;
- (void)fontSizeDidChange:(id)arg1;
- (void)deviceOrientationDidChange:(id)arg1;
- (void)updateFontAndDismissButtonHeight;
- (void)updateInsets;
- (void)setupConstraints;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

