//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

#import "WAIndexableManagedObject-Protocol.h"

@class NSDate, NSManagedObjectID, NSSet, NSString, WAChatSessionSavedReply, WAChatSessionTransaction, WAGroupInfo, WAMessage;
@protocol WAServerDate;

@interface WAChatSession : NSManagedObject <WAIndexableManagedObject>
{
    unsigned int _statusMessageCount;
    WAChatSessionSavedReply *_savedReply;
    WAChatSessionTransaction *_transaction;
    int _change;
    BOOL _suppressCreationOfNextGroupPictureChangeEvent;
}

+ (id)earliestPinnedMessageDate;
+ (id)commaSeparatedListOfContactNames:(id)arg1 limit:(unsigned int)arg2;
+ (id)listOfContactNamesForContacts:(id)arg1 onlyMatchingJIDs:(id)arg2 prioritizingContactsWithJIDs:(id)arg3 unsorted:(BOOL)arg4 verifiedBadgePlaceholder:(id)arg5;
+ (id)firstNamesOfContactsInTheList:(id)arg1 limit:(unsigned int)arg2 unsorted:(BOOL)arg3;
+ (id)firstNamesOfContactsInTheList:(id)arg1 limit:(unsigned int)arg2;
+ (id)participantsHashForJIDs:(id)arg1;
+ (short)sessionTypeFromJID:(id)arg1;
+ (id)labelForSaveToCameraRollSetting:(int)arg1 preferCompactText:(BOOL)arg2;
+ (unsigned int)maximumListNameLength;
+ (id)allDeletedChatSessionIDsInContext:(id)arg1 objectIDsOnly:(BOOL)arg2;
+ (void)resetGroupCreatorOrAdminKnownCache;
+ (id)groupCreatorOrAdminKnownCache;
+ (id)managedObjectContextForJID:(id)arg1;
@property(nonatomic) BOOL suppressCreationOfNextGroupPictureChangeEvent; // @synthesize suppressCreationOfNextGroupPictureChangeEvent=_suppressCreationOfNextGroupPictureChangeEvent;
- (void).cxx_destruct;
- (BOOL)validateWebClientPinDate:(id)arg1 defaultValue:(BOOL)arg2;
@property(retain, nonatomic) NSDate *webClientPinDate;
- (id)storedWebClientPinDate;
- (int)getLastMessageYear;
- (int)getPinnedYears;
- (id)realLastMessageDate;
- (BOOL)isPinned;
- (void)unpin;
- (void)pinToPosition:(unsigned int)arg1;
- (void)updateStatusRanking;
- (id)firstNamesOfActiveGroupMembersWithJIDs:(id)arg1 limit:(int)arg2 listFirst:(id)arg3 verifiedBadgePlaceholder:(id)arg4;
- (id)firstNamesOfActiveGroupMembers;
- (unsigned int)numberOfActiveGroupMembers;
@property(readonly, nonatomic) NSSet *activeGroupMemberJIDs;
@property(readonly, nonatomic) NSSet *activeGroupMembers;
- (void)setSaveToCameraRollSetting:(int)arg1 allowExternalSideEffects:(BOOL)arg2;
@property(readonly, nonatomic) int saveToCameraRollSetting;
@property(readonly, nonatomic) BOOL shouldAutoSaveMediaToCameraRoll;
- (BOOL)hasLastMessageSameIdentityAsMessageID:(id)arg1;
@property(readonly, nonatomic) WAMessage *lastMessageForChatList;
@property(readonly, nonatomic) BOOL requiresFetchForChatListLastMessage;
@property(copy, nonatomic) NSString *savedInput; // @dynamic savedInput;
- (id)participantsHash;
- (void)setPartnerName:(id)arg1 allowExternalSideEffects:(BOOL)arg2;
@property(nonatomic) int messageCounter; // @dynamic messageCounter;
- (void)setUnreadCount:(int)arg1 allowExternalSideEffects:(BOOL)arg2;
- (void)setContactJID:(id)arg1 allowExternalSideEffects:(BOOL)arg2;
@property(readonly, nonatomic, getter=isUnknownContact) BOOL unknownContact;
@property(readonly, nonatomic) unsigned int maxParticipants;
@property(readonly, nonatomic, getter=isReadonlyGroup) BOOL readonlyGroup;
@property(readonly, nonatomic, getter=isOutgoingStatusChat) BOOL outgoingStatusChat;
@property(readonly, nonatomic, getter=isBroadcastList) BOOL broadcastList;
@property(readonly, nonatomic, getter=isGroupChat) BOOL groupChat;
@property(readonly, nonatomic, getter=isIncomingStatusChat) BOOL incomingStatusChat;
@property(readonly, nonatomic, getter=isIndividualChat) BOOL individualChat;
@property(readonly, nonatomic, getter=isContactBlocked) BOOL contactBlocked;
@property(readonly, nonatomic, getter=isBusinessChat) BOOL businessChat;
@property(nonatomic, getter=isVerified) BOOL verified;
@property(nonatomic) BOOL vCardMatchDeclined;
@property(nonatomic, getter=isEligibleForGhostMessageUpdate) BOOL eligibleForGhostMessageUpdate;
- (void)setLocationSharingEndDate:(id)arg1 allowExternalSideEffects:(BOOL)arg2;
- (BOOL)testFlagBit:(int)arg1;
- (void)clearFlagBit:(int)arg1;
- (void)setFlagBit:(int)arg1;
- (void)updatePrimitiveLastMessageDate:(id)arg1;
@property(retain, nonatomic) NSDate<WAServerDate> *lastMessageDate; // @dynamic lastMessageDate;
@property(nonatomic) BOOL archived; // @dynamic archived;
@property(nonatomic) BOOL hidden; // @dynamic hidden;
- (void)didTurnIntoFault;
- (void)awakeFromFetch;
- (void)promptToChangeSaveToCameraRollSettingFromViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updateSortIndexOfMessage:(id)arg1;
- (void)prepareGroupInfo;
- (void)showEmptyChatHistoryAlertViewFromViewController:(id)arg1;
- (void)resetLastMessage;
- (void)generateNewWebModifyTag;
@property(readonly, nonatomic) NSString *webModifyTag;
@property(readonly, nonatomic) NSString *nameForWebClient;
- (id)groupMemberWithJID:(id)arg1;
- (id)sortedGroupMembersIncludingNonActive:(BOOL)arg1;
@property(readonly, nonatomic, getter=isBroadcastListJIDValid) BOOL broadcastListJIDValid;
- (void)promptUserToAttachMediaToChatHistoryFromViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)deleteConfirmationText;
- (unsigned int)countOfPendingMessages;
- (BOOL)currentUserCanMessageGroup;
- (BOOL)currentUserCanEditGroup;
- (BOOL)currentUserIsAdmin;
- (BOOL)isChatReadable;
- (BOOL)isGroupCreatorOrAdminKnown;
@property(readonly, nonatomic, getter=isSuspicious) BOOL suspicious;
@property(copy, nonatomic) WAChatSessionSavedReply *savedReply;
- (void)updateStatusParticipants;
- (id)internalQueryOutgoingPendingMessageCounts;
- (id)queryOutgoingPendingMessageCounts;
- (unsigned int)queryCompletedStatusMessageCount;
@property(readonly, nonatomic) unsigned int statusMessageCount;
- (void)updateStatusMessageCountWithPending:(id)arg1;
- (void)provideStatusMessageCount:(unsigned int)arg1;
- (void)invalidateStatusMessageCount;
- (id)statusBeforeSort:(int)arg1 fetchLimit:(unsigned int)arg2 hasMore:(char *)arg3 mostRecent:(BOOL)arg4;
- (id)oldestStatusBeforeSort:(int)arg1 fetchLimit:(unsigned int)arg2 hasMore:(char *)arg3;
- (id)newestStatusBeforeSort:(int)arg1 fetchLimit:(unsigned int)arg2 hasMore:(char *)arg3;
- (id)statusPredicateByAdding:(id)arg1;
- (id)statusPredicateByAdding:(id)arg1 deletionTypes:(id)arg2;
- (id)statusFilterForDeletionType:(short)arg1;
@property(readonly, nonatomic) short completedDeletionType;
@property(readonly, nonatomic) short pendingDeletionType;
- (int)countOfMessagesAfterSort:(int)arg1 limit:(int)arg2;
- (int)countOfEligibleForUnreadMessagesAfterSort:(int)arg1;
- (int)validSortBeforeSort:(int)arg1 offset:(int)arg2;
- (int)earliestUnreadSortWithOffset:(int)arg1;
@property(readonly, nonatomic) int earliestUnreadSort;
@property(readonly, nonatomic) int mostRecentReadSort;
- (unsigned int)numberOfStarredMessages;
- (BOOL)containsDownloadedMedia;
- (id)pendingGhostMessagesWithStorage:(id)arg1;
- (id)ghostMessagesWithStorage:(id)arg1;
- (BOOL)containsOutgoingMessages;
- (BOOL)containsUserMessages;
- (id)basePredicateForMessagesByAdding:(id)arg1;
@property(readonly, nonatomic) WAChatSessionTransaction *transaction;
@property(readonly, nonatomic, getter=isActive) BOOL active;
@property(readonly, nonatomic, getter=isValid) BOOL valid;
- (id)lastIncomingMessagesForSpamReporting;
- (id)messageWithStanzaID:(id)arg1 isFromMe:(BOOL)arg2;
- (id)messageWithStanzaID:(id)arg1 author:(id)arg2;
- (id)messageWithStanzaID:(id)arg1 participant:(id)arg2 isFromMe:(BOOL)arg3;
- (id)messagesWithStanzaID:(id)arg1;

// Remaining properties
@property(nonatomic) int contactABID; // @dynamic contactABID;
@property(copy, nonatomic) NSString *contactIdentifier; // @dynamic contactIdentifier;
@property(copy, nonatomic) NSString *contactJID; // @dynamic contactJID;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(copy, nonatomic) NSString *eTag; // @dynamic eTag;
@property(nonatomic) int flags; // @dynamic flags;
@property(retain, nonatomic) WAGroupInfo *groupInfo; // @dynamic groupInfo;
@property(copy, nonatomic) NSSet *groupMembers; // @dynamic groupMembers;
@property(readonly) unsigned int hash;
@property(nonatomic) int identityVerificationEpoch; // @dynamic identityVerificationEpoch;
@property(nonatomic) short identityVerificationState; // @dynamic identityVerificationState;
@property(retain, nonatomic) WAMessage *lastMessage; // @dynamic lastMessage;
@property(retain, nonatomic) NSDate<WAServerDate> *locationSharingEndDate; // @dynamic locationSharingEndDate;
@property(readonly, nonatomic) NSManagedObjectID *objectID;
@property(copy, nonatomic) NSString *partnerName; // @dynamic partnerName;
@property(nonatomic) BOOL removed; // @dynamic removed;
@property(nonatomic) short sessionType; // @dynamic sessionType;
@property(nonatomic) short spotlightStatus; // @dynamic spotlightStatus;
@property(readonly) Class superclass;
@property(readonly, nonatomic) int unreadCount; // @dynamic unreadCount;

@end

