//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSIndexPath, NSMutableArray, NSSet, WAMessage;
@protocol WAChatMessagesControllerDelegate;

@interface WAChatMessagesController : NSObject
{
    NSMutableArray *_sections;
    unsigned int _bottomPanelMode;
    BOOL _createsAlbums;
    id <WAChatMessagesControllerDelegate> _delegate;
    NSSet *_highlightedTerms;
    unsigned int _cellDataStyle;
}

@property(readonly, nonatomic) BOOL createsAlbums; // @synthesize createsAlbums=_createsAlbums;
@property(readonly, nonatomic) unsigned int cellDataStyle; // @synthesize cellDataStyle=_cellDataStyle;
@property(copy, nonatomic) NSSet *highlightedTerms; // @synthesize highlightedTerms=_highlightedTerms;
@property(readonly, nonatomic) NSArray *sections; // @synthesize sections=_sections;
@property(nonatomic) __weak id <WAChatMessagesControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isContentTrusted) BOOL contentTrusted;
- (void)updateBottomPanelMode;
- (void)updateBottomPanelCellIfNeeded;
- (void)prependMessages:(id)arg1 animated:(BOOL)arg2 configurationBlock:(CDUnknownBlockType)arg3;
- (BOOL)appendMessages:(id)arg1 firstUnreadMessage:(id)arg2 updateMessages:(id)arg3 totalUnreadCount:(int)arg4 searchResultMessageIDs:(id)arg5 dividerBehavior:(unsigned int)arg6 createAlbumsIfNeeded:(BOOL)arg7 didSkipCreatingAlbums:(char *)arg8 animated:(BOOL)arg9 configurationBlock:(CDUnknownBlockType)arg10;
- (void)rebuildSectionsAsNeeded;
- (void)clearSearchResultIndicators;
- (id)messagesSeparatedByRevokedMessagesFromMessages:(id)arg1;
- (void)deleteChatCellDataObjects:(id)arg1 whileUpdatingChatCellDataObjects:(id)arg2 skipAlbumProcessing:(BOOL)arg3 animated:(BOOL)arg4;
- (void)updateCellDataForMessages:(id)arg1 animated:(BOOL)arg2;
- (unsigned int)removeInvalidMessagesAnimated:(BOOL)arg1;
- (int)evictMessagesKeepingChatCellDataObjects:(id)arg1 evictEarliest:(BOOL)arg2 animated:(BOOL)arg3;
@property(readonly, nonatomic) WAMessage *lastMessage;
@property(readonly, nonatomic) WAMessage *firstMessage;
- (void)enumerateChatCellDataUsingBlock:(CDUnknownBlockType)arg1;
- (void)removeUnreadDividerWithAnimation:(BOOL)arg1;
- (id)upgradePlaceholderCellDataForMessages:(id)arg1;
- (id)chatCellDataForMessage:(id)arg1;
- (id)allUnsentMessagesOnSameDateAsMessage:(id)arg1;
- (void)removeChatCellDataAtIndexPath:(id)arg1;
- (id)indexPathOfChatCellData:(id)arg1;
- (id)indexPathOfMessage:(id)arg1;
- (id)chatCellDataAtIndexPath:(id)arg1;
@property(readonly, nonatomic) NSIndexPath *bottomMostIndexPath;
- (void)removeAllMessages;
- (id)titleForSection:(int)arg1;
- (int)numberOfRowsInSection:(int)arg1;
- (int)numberOfSections;
@property(readonly, nonatomic, getter=isEmpty) BOOL empty;
@property(readonly, nonatomic) NSIndexPath *bottomPanelCellIndexPath;
@property(readonly, nonatomic) NSIndexPath *dividerIndexPath;
@property(readonly, nonatomic) int cellDataCount;
@property(readonly, nonatomic) int messageCount;
- (id)initWithOptions:(unsigned int)arg1;

@end

