//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAPictureContainerViewController.h"

#import "ABDisabledControllerDelegate-Protocol.h"
#import "ABPeoplePickerNavigationControllerDelegate-Protocol.h"
#import "CNContactPickerDelegate-Protocol.h"
#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WAContactCardItemTableViewCellDelegate-Protocol.h"
#import "WAContactEditViewControllerDelegate-Protocol.h"
#import "WAShareContactViewControllerDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, WAAggregateCallEvent, WABizProfile, WAContact, WALocationData, WAMediaManager, WATableRow, WATableSection;

@interface WAContactViewController : WAPictureContainerViewController <UITableViewDelegate, UITableViewDataSource, ABDisabledControllerDelegate, ABPeoplePickerNavigationControllerDelegate, CNContactPickerDelegate, WAShareContactViewControllerDelegate, WAContactCardItemTableViewCellDelegate, WAContactEditViewControllerDelegate, MFMailComposeViewControllerDelegate>
{
    NSMutableArray *_sections;
    WATableSection *_sectionContactName;
    WATableRow *_rowContactName;
    WATableRow *_rowAbout;
    WATableSection *_sectionCallEvents;
    WATableRow *_rowCallEvents;
    WATableSection *_sectionUnkownContactActions;
    WATableRow *_rowContactCards;
    WATableRow *_rowCreateNewContact;
    WATableRow *_rowAddToExistingContact;
    WATableSection *_sectionMedia;
    WATableRow *_rowMediaStripe;
    WATableRow *_rowMediaLinksDocs;
    WATableRow *_rowStarredMessages;
    WATableRow *_rowChatHistory;
    WATableRow *_rowChatSearch;
    WAMediaManager *_mediaManager;
    int _numberOfStarredMessages;
    WATableSection *_sectionSettings;
    WATableRow *_rowMute;
    WATableRow *_rowNotificationTone;
    WATableRow *_rowSaveIncoming;
    WATableRow *_rowEncryptionStatus;
    int _numberOfGroupsInCommon;
    WATableSection *_sectionGroupsInCommon;
    WATableRow *_rowGroupsInCommon;
    WATableSection *_sectionContactDetails;
    WATableSection *_sectionActions;
    WATableRow *_rowExportChat;
    WATableRow *_rowShareContact;
    WATableRow *_rowClearChat;
    WATableSection *_sectionLiveLocation;
    WATableRow *_rowLiveLocation;
    BOOL _currentUserIsSharingLocation;
    BOOL _partnerIsSharingLocation;
    WATableSection *_sectionBlockContact;
    WATableRow *_rowBlockUnblockContact;
    WATableRow *_rowReportSpam;
    NSArray *_vCardSuggestions;
    BOOL _ignoreBlockedContactListNotifications;
    WABizProfile *_bizProfile;
    WATableSection *_sectionBizName;
    WATableRow *_rowBizName;
    WATableSection *_sectionBizInfo;
    WATableRow *_rowBizEmail;
    WATableRow *_rowBizInfo;
    WATableRow *_rowBizVertical;
    NSMutableArray *_rowBizWebsites;
    WATableRow *_rowBizAddress;
    WALocationData *_bizLocationData;
    WATableSection *_sectionBizSocial;
    NSMutableArray *_rowBizSocialProfiles;
    BOOL _chatContainsMessages;
    WAAggregateCallEvent *_aggregateCallEvent;
    WAContact *_contact;
}

@property(nonatomic) BOOL chatContainsMessages; // @synthesize chatContainsMessages=_chatContainsMessages;
@property(retain, nonatomic) WAContact *contact; // @synthesize contact=_contact;
@property(retain, nonatomic) WAAggregateCallEvent *aggregateCallEvent; // @synthesize aggregateCallEvent=_aggregateCallEvent;
- (void).cxx_destruct;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)updateBizSocialRow:(id)arg1 withSocialProfile:(id)arg2;
- (void)updateBizEmailRowWithProfile:(id)arg1;
- (void)updateBizWebsiteRow:(id)arg1 withURL:(id)arg2;
- (void)updateBizSocialSectionWithProfile:(id)arg1;
- (void)updateBizAddressRowWithProfile:(id)arg1;
- (void)updateBizInfoRowWithProfile:(id)arg1;
- (void)updateBizInfoSectionWithProfile:(id)arg1;
- (void)updateBizSectionsWithProfile:(id)arg1;
- (BOOL)addBizSocialProfilesWithProfile:(id)arg1;
- (BOOL)addBizWebsitesWithProfile:(id)arg1;
- (BOOL)removeBizSectionsIfNeeded;
- (void)createBizInfoSection;
- (BOOL)addBizSectionsIfNeeded;
- (void)fetchBizProfileIfNeeded;
- (void)bizProfileDidUpdate:(id)arg1;
- (void)contactsStorageDidUpdateContacts:(id)arg1;
- (void)transactionDidProcessMessages:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)rowAtIndexPath:(id)arg1;
- (void)setupTableView;
- (void)deleteRow:(id)arg1 updateTableView:(BOOL)arg2;
- (void)insertRow:(id)arg1 atIndexPath:(id)arg2 updateTableView:(BOOL)arg3;
- (void)deleteSection:(id)arg1 updateTableView:(BOOL)arg2;
- (void)insertSection:(id)arg1 atIndex:(int)arg2 updateTableView:(BOOL)arg3;
- (id)addSection;
- (void)addIcon:(id)arg1 toTableViewCell:(id)arg2;
- (void)contactEditControllerDidCancel:(id)arg1;
- (void)contactEditControllerDidSave:(id)arg1;
- (void)editAction:(id)arg1;
- (void)messageButtonTappedInContactCardItemCell:(id)arg1;
- (void)voiceCallButtonTappedInContactCardItemCell:(id)arg1;
- (void)videoCallButtonTappedInContactCardItemCell:(id)arg1;
- (void)callContactWithJID:(id)arg1 withVideo:(BOOL)arg2;
- (void)askToUnblockContactBeforeCalling;
- (void)messageContactWithJID:(id)arg1;
- (void)promptToCallOrMessageJID:(id)arg1 phoneNumber:(id)arg2;
- (void)updateNavigationBar;
- (void)reloadContactDetailsSectionAndUpdateTableView:(BOOL)arg1;
- (void)viewLocationWithData:(id)arg1;
- (BOOL)showContactDetailsSection;
- (void)viewContactDetails;
- (void)updateAppearanceOfAboutRow;
- (void)updateAppearanceOfContactNameRow;
- (void)reloadDataWithContact:(id)arg1 andUpdateUI:(BOOL)arg2;
- (void)reloadDataRefetchingCurrentContact;
- (void)blockedContactsListUpdated:(id)arg1;
- (void)blockedContactsListDidChange;
- (void)updateBlockUnblockRowAppearance;
- (void)promptToReportSpamAndBlockFromBlockDialog:(BOOL)arg1;
- (void)promptToBlockOrUnblockContact;
- (void)blockContactAndReportSpam:(BOOL)arg1 fromBlockDialog:(BOOL)arg2;
- (void)unblockContact;
- (BOOL)contactIsBlocked;
- (void)setLiveLocationSectionVisible:(BOOL)arg1 updateTableView:(BOOL)arg2;
- (void)locationSharingEndDateChanged:(id)arg1;
- (void)locationSharingParticipantsChanged:(id)arg1;
- (void)viewLocations;
- (BOOL)showLiveLocation;
- (void)updateLiveLocationIndication;
- (void)updateLiveLocationSenders;
- (void)reportClearChatAction;
- (void)updateAppearanceOfChatHistoryActionCells;
- (void)clearChat;
- (void)exportChat;
- (id)shareContactViewControllerConfirmationButtonTitle:(id)arg1;
- (void)shareContactViewControllerDidCancel:(id)arg1;
- (void)shareContactViewController:(id)arg1 didFinishWithVCard:(id)arg2;
- (void)shareContact;
- (BOOL)showShareContactRow;
- (void)invalidateNumberOfGroupsInCommon;
- (void)loadNumberOfGroupsInCommonIfNeededAndUpdateSections:(BOOL)arg1 updateTableView:(BOOL)arg2;
- (void)updateGroupsInCommonRowIndication;
- (void)viewGroupsInCommon;
- (void)showIdentityVerificationScreen;
- (void)promptToChangeSaveIncomingMediaSettings;
- (void)updateSaveIncomingMediaSettingIndication;
- (void)updateNotificationToneIndication;
- (void)promptToSelectCustomNotificationTone;
- (void)updateMuteIndication;
- (void)updateMuteTimeoutWithDate:(id)arg1;
- (void)promptToMuteOrUnmuteChat;
- (void)jumpToInChatSearch;
- (void)viewChatHistory;
- (void)updateStarredMessagesCountIndication;
- (void)loadNumberOfStarredMessagesIfNecessary;
- (void)invalidateNumberOfStarredMessages;
- (void)viewStarredMessages;
- (void)updateMediaCountIndication;
- (void)viewAllMedia;
- (void)loadMediaManagedIfNeeded;
- (void)abDisabledViewControllerDidCancel:(id)arg1;
- (void)presentDisabledAddressBookViewController;
- (void)peoplePickerNavigationControllerDidCancel:(id)arg1;
- (void)peoplePickerNavigationController:(id)arg1 didSelectPerson:(void *)arg2;
- (BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2;
- (void)contactPicker:(id)arg1 didSelectContact:(id)arg2;
- (void)contactPickerDidCancel:(id)arg1;
- (void)addUnknownContactDataToExistingContact;
- (void)saveUnknownContactDataAsNewContact;
- (void)presentEditAndSaveScreenForContact:(id)arg1;
- (void)setSuggestedContactCards:(id)arg1;
- (void)updateAppearanceOfContactCardsRow;
- (void)viewContactCards;
- (void)wa_fontSizeDidChange;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithContact:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

