//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAAutoMigratingStorage.h"

#import "WAContactLookupProvider-Protocol.h"
#import "WAPersistentRequestManagerRegistering-Protocol.h"

@class NSLock, NSMutableDictionary, NSObject, NSString, WAContactSpotlightIndexer;
@protocol OS_dispatch_queue, WAContactsStorageDelegate;

@interface WAContactsStorage : WAAutoMigratingStorage <WAContactLookupProvider, WAPersistentRequestManagerRegistering>
{
    WAContactSpotlightIndexer *_spotlightIndexer;
    NSString *_eTag;
    BOOL _needsRefreshContacts;
    BOOL _needsRefreshStatus;
    BOOL _contactsAvailable;
    NSMutableDictionary *_existResults;
    NSObject<OS_dispatch_queue> *_contactsSerialQueue;
    id <WAContactsStorageDelegate> _delegate;
    NSLock *_addressBookMutationLock;
    int _approxCountOfContactsBeingUpdated;
}

+ (BOOL)useMainQueueDatabaseConcurrencyType;
+ (BOOL)useContactsFramework;
+ (long)internalFetchAuthorizationStatus;
+ (BOOL)contactsAccessRequestNecessary;
+ (BOOL)contactsAccessAuthorized;
+ (void)initialize;
+ (void)sendEmailInvitationTo:(id)arg1 showIn:(id)arg2;
+ (id)variantsForPhoneNumber:(id)arg1;
@property int approxCountOfContactsBeingUpdated; // @synthesize approxCountOfContactsBeingUpdated=_approxCountOfContactsBeingUpdated;
@property(readonly, nonatomic) NSLock *addressBookMutationLock; // @synthesize addressBookMutationLock=_addressBookMutationLock;
@property(nonatomic) __weak id <WAContactsStorageDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)registerHandlersForPersistentRequestManager:(id)arg1;
- (id)sharedObjectKeyForPersistentRequestManager:(id)arg1;
- (id)normalizedPhoneNumbersForContactWithIdentifier:(id)arg1;
- (id)phoneNumberMapForContacts:(id)arg1;
- (void)fetchAboutTextForContact:(id)arg1;
- (id)aboutTextForJID:(id)arg1;
- (id)anyABContactForJID:(id)arg1;
- (BOOL)addressBookContainsAnyJID:(id)arg1;
- (BOOL)addressBookContainsJID:(id)arg1;
- (id)allWhatsAppableContacts;
- (id)predicateForFetchingSidelistContacts;
- (id)predicateForFetchingAddressBookContacts;
- (void)performSeriallyOnQueue:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)managedObjectContext;
@property(readonly, nonatomic) BOOL contactsAvailable;
- (id)initWithModelName:(id)arg1 storeURL:(id)arg2 blacklistBackup:(BOOL)arg3;
- (id)init;
- (id)statusRecipients;
- (void)fetchAllContactsWithEmailAddresses:(CDUnknownBlockType)arg1;
- (id)internalFetchAllContactsWithEmailAddresses;
- (id)emailsFromAddressBookForContacts:(id)arg1;
- (id)emailsFromContactStoreForContacts:(id)arg1;
- (void)fetchAllContactsWithPhoneNumbers:(CDUnknownBlockType)arg1;
- (id)internalFetchAllContactsWithPhoneNumbers;
- (id)allContactsWithOptions:(int)arg1;
- (id)allContactsSectionsForJIDs:(id)arg1;
- (id)allContactsInSectionsWithOptions:(int)arg1;
- (id)jidsToExcludeForOptions:(int)arg1;
- (id)contactSectionsFromSectionMap:(id)arg1;
- (id)contactsMapMatchingOrExcludingJIDs:(BOOL)arg1 inSet:(id)arg2;
- (void)processResultsOfFullSync:(BOOL)arg1 listContacts:(id)arg2 sidelistContacts:(id)arg3 statusEntries:(id)arg4;
- (id)allContactsMatchingPhoneNumbers:(id)arg1 inContext:(id)arg2;
- (id)sidelistJIDsMatchingHash:(id)arg1;
- (id)allSidelistContactsInContext:(id)arg1;
- (id)unsyncedSidelistJIDsFromJIDs:(id)arg1;
- (id)processContactAddedNotificationWithHash:(id)arg1;
- (id)statusTimestampsForWhatsAppIDs:(id)arg1;
- (id)phoneNumbersForFullSync:(BOOL)arg1;
- (void)processIncomingStatusNotification:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) WAContactSpotlightIndexer *spotlightIndexer;
- (void)refreshETag;
@property(readonly, copy, nonatomic) NSString *eTag;
- (void)setExistStatus:(id)arg1 forJID:(id)arg2;
- (id)existStatusForJID:(id)arg1;
- (void)refreshExistStatusForJID:(id)arg1;
- (void)checkPhoneNumberWhatsAppable:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)statusFetchFailedWithError:(id)arg1;
- (void)statusFetchFinishedWithResults:(id)arg1;
- (BOOL)mergeStatusV2Results:(id)arg1 intoContext:(id)arg2;
- (id)inNetworkContactsForJIDs:(id)arg1 inContext:(id)arg2;
- (void)requestStatusMessagesForJIDs:(id)arg1;
- (void)requestStatusMessagesForAllContactsIfNeeded;
- (void)markJIDAsOutOfNetwork:(id)arg1;
- (void)setAboutText:(id)arg1 withTimestamp:(id)arg2 forJID:(id)arg3;
- (id)inNetworkContactsForJID:(id)arg1 inContext:(id)arg2;
- (id)aboutTextForJIDs:(id)arg1;
- (id)addressBookPhoneNumberForJID:(id)arg1;
- (id)refetchDataForContact:(id)arg1;
- (id)contactsWithLegacyIdentifier:(int)arg1 inContext:(id)arg2;
- (id)contactsWithIdentifier:(id)arg1 inContext:(id)arg2;
- (id)whatsAppAbleContactsWithABID:(int)arg1;
- (id)contactsWithLegacyIdentifiers:(id)arg1 inContext:(id)arg2;
- (id)contactsWithIdentifiers:(id)arg1 inContext:(id)arg2;
- (id)allContactsDeduped;
- (unsigned int)numberOfContacts;
- (id)reloadDataFromABRecord:(void *)arg1 whatsAppID:(id)arg2;
- (id)reloadDataFromCNContact:(id)arg1 whatsAppID:(id)arg2;
- (id)reloadDataFromContactCreatedInApp:(id)arg1 whatsAppID:(id)arg2;
- (id)reloadDataFromContactProxyObject:(id)arg1 managedObjectContext:(id)arg2 usingExistingContacts:(id)arg3 uniqueContactKeys:(id)arg4 returningNewContacts:(out id *)arg5 returningContactsWithUpdatedNames:(out id *)arg6;
- (id)addNewContactFromContactProxy:(id)arg1 inContext:(id)arg2;
- (id)identifiersFromAddressBook:(void *)arg1;
- (id)identifiersFromContactStore:(id)arg1;
- (void)reloadContactsWithCompletion:(CDUnknownBlockType)arg1;
- (void)notifyUpdatedStatusIfNecessary;
- (void)notifyUpdatedContactsIfNecessary;
- (void)deleteDatabase;
- (void)handleDatabaseContext:(id)arg1 saveError:(id)arg2;
- (BOOL)saveDatabase:(id *)arg1;
- (BOOL)willSaveDatabaseContext:(id)arg1;
- (void)performAfterInit;
- (BOOL)migrateDataIntoContacts:(id)arg1;
- (id)knownJIDsFromJIDs:(id)arg1 registeredUsersOnly:(BOOL)arg2;
- (id)bestJIDForPhoneNumber:(id)arg1;
- (void)withContactForWhatsAppID:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)contactsForJIDs:(id)arg1;
- (id)addressBookContactsForJIDs:(id)arg1 inContext:(id)arg2;
- (id)contactForJID:(id)arg1;
- (id)bestContactForWhatsAppID:(id)arg1 inContext:(id)arg2;
- (id)bestContactForWhatsAppID:(id)arg1;
- (id)bestContactFromContacts:(id)arg1;
- (id)allContactsWithWhatsAppIDs:(id)arg1 inContext:(id)arg2;
- (id)intentRecipientsForJIDs:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

