//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSString, UIImage, UITapGestureRecognizer, UIView, WAAutoPlayVideoPlayerView, WAEditableImageCompositeView, WAMediaPlayer, WAPaintCanvas, WAPaintCanvasView;
@protocol WAEditableImageScrollViewEditingDelegate;

@interface WAEditableImageScrollView : UIScrollView <UIScrollViewDelegate, UIGestureRecognizerDelegate>
{
    float _fillToBoundsScale;
    BOOL _needsAdjustZoomScale;
    BOOL _needsSetZoomScale;
    BOOL _isScrollingInteractively;
    WAEditableImageCompositeView *_compositeView;
    UITapGestureRecognizer *_singleTapGesture;
    BOOL _paintingEnabled;
    BOOL _receivesTouchesBeyondBounds;
    BOOL _resetsZoomScaleOnBoundsChange;
    id <WAEditableImageScrollViewEditingDelegate> _editingDelegate;
    float _targetZoomScale;
    unsigned int _minimumZoomMode;
}

@property(nonatomic) BOOL resetsZoomScaleOnBoundsChange; // @synthesize resetsZoomScaleOnBoundsChange=_resetsZoomScaleOnBoundsChange;
@property(nonatomic) unsigned int minimumZoomMode; // @synthesize minimumZoomMode=_minimumZoomMode;
@property(nonatomic) BOOL receivesTouchesBeyondBounds; // @synthesize receivesTouchesBeyondBounds=_receivesTouchesBeyondBounds;
@property(nonatomic) float targetZoomScale; // @synthesize targetZoomScale=_targetZoomScale;
@property(nonatomic, getter=isPaintingEnabled) BOOL paintingEnabled; // @synthesize paintingEnabled=_paintingEnabled;
@property(readonly, nonatomic) UIView *compositeView; // @synthesize compositeView=_compositeView;
@property(nonatomic) __weak id <WAEditableImageScrollViewEditingDelegate> editingDelegate; // @synthesize editingDelegate=_editingDelegate;
- (void).cxx_destruct;
- (void)destroyMediaPlayerElements;
@property(nonatomic, getter=isAutoPlayViewHidden) BOOL autoPlayViewHidden;
@property(readonly, nonatomic) WAAutoPlayVideoPlayerView *autoPlayView;
@property(readonly, nonatomic) WAMediaPlayer *mediaPlayer;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(float)arg3;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (void)scrollViewDidZoom:(id)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)handleSingleTap:(id)arg1;
- (void)configureZooming;
- (void)calculateFillToBoundsScale:(out float *)arg1 minimumZoomScale:(out float *)arg2 maximumZoomScale:(out float *)arg3 forImageSize:(struct CGSize)arg4;
- (struct CGRect)zoomRectForScale:(float)arg1 withCenter:(struct CGPoint)arg2;
- (void)relayoutAlongsideLayerAnimation;
- (void)toggleZoomInOutAtPoint:(struct CGPoint)arg1;
- (void)zoomOutWithAnimation:(BOOL)arg1;
- (void)prepareForReuse;
@property(readonly, nonatomic) WAPaintCanvasView *paintCanvasView;
@property(retain, nonatomic) WAPaintCanvas *paintCanvas;
@property(retain, nonatomic) UIImage *overlayImage;
@property(readonly, nonatomic) UIImage *compositeViewSnapshotImage;
@property(retain, nonatomic) UIImage *image;
- (void)layoutSubviews;
- (void)setNeedsAdjustZoomScale;
- (void)setContentSize:(struct CGSize)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

