//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSURL, WAMessage;

@interface WAGIFAsset : NSObject
{
    BOOL _isfullPreviewable;
    NSURL *_previewURL;
    NSURL *_fullGIFURL;
    NSURL *_fullVideoURL;
    NSURL *_thumbnailURL;
    WAMessage *_originalMessage;
    float _widthRatio;
    NSNumber *_provider;
    struct CGSize _size;
}

+ (id)localCacheFileNameForURL:(id)arg1 extension:(id)arg2;
+ (struct CGSize)sizeFromGIPHYDictionary:(id)arg1;
+ (id)thumbnailPreviewURLFromGIPHYDictionary:(id)arg1 size:(struct CGSize)arg2;
+ (id)smallPreviewURLFromGIPHYDictionary:(id)arg1 size:(struct CGSize)arg2;
+ (id)previewURLFromGIPHYDictionary:(id)arg1 size:(struct CGSize)arg2;
+ (id)stillPathForPath:(id)arg1;
+ (id)smallPathForPath:(id)arg1;
+ (id)notPreferredPreviewStringForSize:(struct CGSize)arg1;
+ (id)preferredPreviewStringForSize:(struct CGSize)arg1;
@property(readonly, nonatomic) NSNumber *provider; // @synthesize provider=_provider;
@property(nonatomic) float widthRatio; // @synthesize widthRatio=_widthRatio;
@property(readonly, nonatomic) BOOL isfullPreviewable; // @synthesize isfullPreviewable=_isfullPreviewable;
@property(readonly, nonatomic) struct CGSize size; // @synthesize size=_size;
@property(readonly, nonatomic) WAMessage *originalMessage; // @synthesize originalMessage=_originalMessage;
@property(readonly, copy, nonatomic) NSURL *thumbnailURL; // @synthesize thumbnailURL=_thumbnailURL;
@property(readonly, copy, nonatomic) NSURL *fullVideoURL; // @synthesize fullVideoURL=_fullVideoURL;
@property(readonly, copy, nonatomic) NSURL *fullGIFURL; // @synthesize fullGIFURL=_fullGIFURL;
@property(readonly, copy, nonatomic) NSURL *previewURL; // @synthesize previewURL=_previewURL;
- (void).cxx_destruct;
- (id)initWithSize:(struct CGSize)arg1 previewURL:(id)arg2 thumbnailURL:(id)arg3 fullVideoURL:(id)arg4 provider:(id)arg5 fullPreviewable:(BOOL)arg6 fullGIFURL:(id)arg7 widthRatio:(float)arg8;
- (id)initWithMessage:(id)arg1;
- (void)_generateSendMediaItemFromGIFAssetWithCompletion:(CDUnknownBlockType)arg1;
- (void)_generateSendMediaItemFromStarredMessageWithCompletion:(CDUnknownBlockType)arg1;
- (void)generatePreparedSendMediaItemWithCompletion:(CDUnknownBlockType)arg1;
- (void)generateSendMediaItemWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithTenorJSON:(id)arg1;
- (id)initWithGIPHYJSON:(id)arg1;

@end

