//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WADigitalClockStamp.h"

@interface WAGrayDigitalClockStamp : WADigitalClockStamp
{
}

- (Class)nextContentStampClass;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)initWithDigitColor:(id)arg1 aspectRatio:(struct CGSize)arg2 clockColor:(id)arg3 lineColor:(id)arg4 fontSize:(float)arg5 periodFractionOfTimeFontSize:(float)arg6 clockCornerRadiusFractionOfHeight:(float)arg7 lineWidthFractionOfHeight:(float)arg8 lineCornerRadiusFractionOfHeight:(float)arg9 lineInsetFractionOfHeight:(float)arg10;
- (id)initWithContentStamp:(id)arg1;

@end

