//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@class TextBlock, TextMessage, UIColor;
@protocol WALinkLabelDelegate;

@interface WALinkLabel : UILabel
{
    TextBlock *_selectedTextBlock;
    TextMessage *_message;
    BOOL _underlineLinks;
    id <WALinkLabelDelegate> _delegate;
    UIColor *_linkColor;
    UIColor *_linkColorHighlighted;
    struct UIEdgeInsets _contentInset;
}

@property(nonatomic) BOOL underlineLinks; // @synthesize underlineLinks=_underlineLinks;
@property(retain, nonatomic) UIColor *linkColorHighlighted; // @synthesize linkColorHighlighted=_linkColorHighlighted;
@property(retain, nonatomic) UIColor *linkColor; // @synthesize linkColor=_linkColor;
@property(nonatomic) struct UIEdgeInsets contentInset; // @synthesize contentInset=_contentInset;
@property(nonatomic) __weak id <WALinkLabelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)setTextAlignment:(int)arg1;
- (void)setTextColor:(id)arg1;
- (void)setFont:(id)arg1;
- (void)setText:(id)arg1;
- (void)openURL;
- (void)highlightURL:(BOOL)arg1;
- (void)sizeFontToFit;
- (id)initWithFrame:(struct CGRect)arg1;

@end

