//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAContentStamp.h"

@class NSString, UIImage;

@interface WALocationStamp : WAContentStamp
{
    NSString *_name;
    NSString *_subtitle;
    UIImage *_icon;
    struct CLLocationCoordinate2D _coordinate;
}

@property(readonly, nonatomic) struct CLLocationCoordinate2D coordinate; // @synthesize coordinate=_coordinate;
@property(readonly, nonatomic) UIImage *icon; // @synthesize icon=_icon;
@property(readonly, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (float)minimumHeight;
- (void)addMetadataToDictionary:(id)arg1 frame:(struct CGRect)arg2 angle:(float)arg3;
- (struct UIEdgeInsets)capInsetsForImageOfHeight:(float)arg1;
- (struct UIEdgeInsets)insetsForImageOfHeight:(float)arg1;
@property(readonly, nonatomic) float naturalHeight;
- (id)backgroundImageWithHeight:(float)arg1;
- (void)copyRefinementFrom:(id)arg1;
- (void)refineWithCompletion:(CDUnknownBlockType)arg1;
- (struct CGSize)aspectRatio;
- (id)uniqueIdentifier;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithName:(id)arg1 icon:(id)arg2 subtitle:(id)arg3 coordinate:(struct CLLocationCoordinate2D)arg4;

@end

