//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MKAnnotation-Protocol.h"
#import "WALocationDataSource-Protocol.h"

@class CLLocation, MKPlacemark, NSDate, NSDictionary, NSManagedObjectID, NSString, UIImage;
@protocol WADeviceDate;

@interface WALocationData : NSObject <MKAnnotation, WALocationDataSource>
{
    UIImage *_contactImage;
    double _expectedTravelTime;
    NSDate<WADeviceDate> *_directionsResponseTimestamp;
    BOOL _showDistance;
    BOOL _showTimestamp;
    BOOL _directionsRequestInProgress;
    CLLocation *_location;
    NSDictionary *_addressComponents;
    CLLocation *_baseLocation;
    NSString *_contactName;
    MKPlacemark *_placemark;
    NSDate *_timestamp;
    NSManagedObjectID *_messageObjectID;
}

@property(nonatomic) BOOL directionsRequestInProgress; // @synthesize directionsRequestInProgress=_directionsRequestInProgress;
@property(nonatomic) BOOL showTimestamp; // @synthesize showTimestamp=_showTimestamp;
@property(nonatomic) BOOL showDistance; // @synthesize showDistance=_showDistance;
@property(retain, nonatomic) NSManagedObjectID *messageObjectID; // @synthesize messageObjectID=_messageObjectID;
@property(retain, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) MKPlacemark *placemark; // @synthesize placemark=_placemark;
@property(copy, nonatomic) NSString *contactName; // @synthesize contactName=_contactName;
@property(retain, nonatomic) CLLocation *baseLocation; // @synthesize baseLocation=_baseLocation;
@property(readonly, nonatomic) NSDictionary *addressComponents; // @synthesize addressComponents=_addressComponents;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
- (void).cxx_destruct;
- (id)locationsWithCoordinate:(struct CLLocationCoordinate2D)arg1;
- (id)locationDataAtIndex:(int)arg1;
- (unsigned int)numberOfLocations;
- (BOOL)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSString *subtitle;
@property(readonly, copy, nonatomic) NSString *title;
@property(readonly, nonatomic) struct CLLocationCoordinate2D coordinate;
@property(nonatomic) double expectedTravelTime;
@property(readonly, nonatomic) UIImage *contactImage;
- (id)initWithAddressComponents:(id)arg1;
- (id)initWithCoordinate:(struct CLLocationCoordinate2D)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

