//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WamEvent.h"

@interface WamEventStatusReply : WamEvent
{
    double _status_session_id;
    double _status_reply_result;
}

@property(nonatomic) double status_reply_result; // @synthesize status_reply_result=_status_reply_result;
@property(nonatomic) double status_session_id; // @synthesize status_session_id=_status_session_id;
- (void)serializeFields;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)clear;
- (id)init;

@end

