//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WAStreamingMediaLoaderPlaybackDelegate-Protocol.h"

@class AVPlayer, AVPlayerItem, AVVideoComposition, NSDate, NSError, NSObject, NSString, UIImage, WAAudioActivity, WACropAwareImageView, WAExactTimer, WAMediaPlayerPlayButtonView, WamEventVideoPlay, _WAPlayerView;
@protocol OS_dispatch_group, WADeviceDate, WAMediaPlayerDelegate;

@interface WAMediaPlayer : UIView <WAStreamingMediaLoaderPlaybackDelegate>
{
    AVPlayer *_player;
    _WAPlayerView *_playerView;
    id _timeObserver;
    float _playerRateBeforeScrubbing;
    CDStruct_1b6d18a9 _desiredSeekTime;
    WAMediaPlayerPlayButtonView *_playButtonView;
    struct CGRect _frameForPlayButtonSnapshot;
    BOOL _showPlayButtonOnReady;
    WAAudioActivity *_playbackActivity;
    BOOL _playButtonNormallyVisible;
    NSObject<OS_dispatch_group> *_seekDispatchGroup;
    WamEventVideoPlay *_pendingPlayEvent;
    double _totalPlaybackTime;
    double _lastPlaybackStartTime;
    double _lastBufferingStartTime;
    double _initialBufferingDuration;
    BOOL _needsResumePlaybackOnBecomeActive;
    BOOL _didPlayToEndTime;
    WAExactTimer *_bufferingRestartTimer;
    unsigned int _streamingAttemptCount;
    NSDate<WADeviceDate> *_lastStreamingAttemptCountIncrement;
    BOOL _stopPlaybackOnEmptyBuffer;
    BOOL _seekInProgress;
    BOOL _alwaysShowPlayButtonOnPause;
    BOOL _suppressPlayButton;
    BOOL _reportsStats;
    BOOL _managesAudioSession;
    BOOL _autoRewinds;
    BOOL _stopsOnFailedStreaming;
    BOOL _audioMuted;
    BOOL _resumesAutomaticallyWhenActive;
    BOOL _scrubbingInProgress;
    BOOL _fromMe;
    unsigned int _status;
    id <WAMediaPlayerDelegate> _delegate;
    float _playbackRate;
    NSError *_error;
    WACropAwareImageView *_posterImageView;
    AVPlayerItem *_playerItem;
    float _audioVolume;
    int _fileSize;
    CDStruct_1b6d18a9 _playbackStartTime;
    CDStruct_1b6d18a9 _maxDuration;
}

@property(nonatomic) int fileSize; // @synthesize fileSize=_fileSize;
@property(nonatomic, getter=isFromMe) BOOL fromMe; // @synthesize fromMe=_fromMe;
@property(readonly, nonatomic) BOOL scrubbingInProgress; // @synthesize scrubbingInProgress=_scrubbingInProgress;
@property(nonatomic) CDStruct_1b6d18a9 maxDuration; // @synthesize maxDuration=_maxDuration;
@property(readonly, nonatomic) UIView *playButtonView; // @synthesize playButtonView=_playButtonView;
@property(readonly, nonatomic) BOOL resumesAutomaticallyWhenActive; // @synthesize resumesAutomaticallyWhenActive=_resumesAutomaticallyWhenActive;
@property(nonatomic, getter=isAudioMuted) BOOL audioMuted; // @synthesize audioMuted=_audioMuted;
@property(nonatomic) float audioVolume; // @synthesize audioVolume=_audioVolume;
@property(readonly, nonatomic) BOOL stopsOnFailedStreaming; // @synthesize stopsOnFailedStreaming=_stopsOnFailedStreaming;
@property(readonly, nonatomic) BOOL autoRewinds; // @synthesize autoRewinds=_autoRewinds;
@property(readonly, nonatomic) BOOL managesAudioSession; // @synthesize managesAudioSession=_managesAudioSession;
@property(readonly, nonatomic) BOOL reportsStats; // @synthesize reportsStats=_reportsStats;
@property(nonatomic) BOOL suppressPlayButton; // @synthesize suppressPlayButton=_suppressPlayButton;
@property(nonatomic) BOOL alwaysShowPlayButtonOnPause; // @synthesize alwaysShowPlayButtonOnPause=_alwaysShowPlayButtonOnPause;
@property(nonatomic) CDStruct_1b6d18a9 playbackStartTime; // @synthesize playbackStartTime=_playbackStartTime;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(readonly, nonatomic) WACropAwareImageView *posterImageView; // @synthesize posterImageView=_posterImageView;
@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
@property(readonly, nonatomic) BOOL seekInProgress; // @synthesize seekInProgress=_seekInProgress;
@property(nonatomic) float playbackRate; // @synthesize playbackRate=_playbackRate;
@property(nonatomic) __weak id <WAMediaPlayerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned int status; // @synthesize status=_status;
- (void).cxx_destruct;
- (id)accessibilityHint;
- (struct CGRect)accessibilityFrame;
- (BOOL)accessibilityActivate;
- (void)submitVideoPlayEvent;
- (void)prepareVideoPlayEventIfNeeded;
- (void)stop;
- (BOOL)stopPlaybackOnEmptyBuffer;
- (void)setStopPlaybackOnEmptyBuffer:(BOOL)arg1;
- (id)lastStreamingAttemptCountIncrement;
- (void)setLastStreamingAttemptCountIncrement:(id)arg1;
- (unsigned int)streamingAttemptCount;
- (void)setStreamingAttemptCount:(unsigned int)arg1;
- (id)snapshotImage;
- (void)performBlockAfterSeeking:(CDUnknownBlockType)arg1;
- (void)seekToTime:(CDStruct_1b6d18a9)arg1 tolerance:(CDStruct_1b6d18a9)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)internalSeekWithTolerance:(CDStruct_1b6d18a9)arg1;
- (void)seekToTime:(CDStruct_1b6d18a9)arg1 tolerance:(CDStruct_1b6d18a9)arg2;
- (void)seekToTime:(CDStruct_1b6d18a9)arg1;
- (void)endScrubbing;
- (void)beginScrubbing;
- (BOOL)isEnoughBufferedToPlay;
- (BOOL)isStreamable;
@property(readonly, nonatomic, getter=isReadyToPlay) BOOL readyToPlay;
@property(readonly, nonatomic, getter=isPlaying) BOOL playing;
@property(readonly, nonatomic) struct CGSize presentationSize;
- (CDStruct_1b6d18a9)limitToMaxDuration:(CDStruct_1b6d18a9)arg1;
@property(readonly, nonatomic) CDStruct_1b6d18a9 duration;
@property(readonly, nonatomic) CDStruct_1b6d18a9 currentTime;
- (void)rewind;
- (BOOL)playInitiatedByAutoPlay:(BOOL)arg1;
- (void)pause;
- (void)updatePlayButtonAlphaWithAnimation:(BOOL)arg1;
- (BOOL)isPlayButtonHidden;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)playerItemDidPlayToEndTime:(id)arg1;
- (void)playerItemDidBecomeReadyToPlay;
- (void)playerDidChangeCurrentTime;
- (void)removeTimeObserverFromPlayer;
- (void)addTimeObserverToPlayer;
- (void)playerDidChangeState;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)endAudioActivityIfNeeded;
- (void)restartBuffering;
- (void)scheduleBufferingRestart;
@property(retain, nonatomic) UIImage *posterImage;
- (void)playButtonTapped:(id)arg1;
- (void)setInitialPosterImage:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(retain, nonatomic) AVVideoComposition *playerItemVideoComposition;
@property(copy, nonatomic) NSString *videoGravity;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 options:(unsigned int)arg2;
- (void)loaderRequestSucceeded:(id)arg1;
- (void)loader:(id)arg1 requestFailedWithError:(id)arg2;
- (BOOL)loaderShouldLoadPlaybackResource:(id)arg1;
- (void)handleMediaStreaming;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

