//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALAsset, NSData, NSDate, NSURL, PHAsset, PHFetchResult, UIImage, WACloudMediaDownloadRequest;
@protocol OS_dispatch_group;

@interface WAMediaPickerAsset : NSObject
{
    id _localIdentifier;
    ALAsset *_alAsset;
    UIImage *_alImage;
    UIImage *_alHighResolutionImage;
    BOOL _isFetchingALImage;
    PHFetchResult *_fetchResult;
    unsigned int _index;
    int _imageDownloadRequestID;
    BOOL _requestInvokedProgressHandler;
    BOOL _livePhotoSelectedAsVideo;
    NSObject<OS_dispatch_group> *_downloadDispatchGroup;
    WACloudMediaDownloadRequest *_cloudMediaDownloadRequest;
    BOOL _selected;
    id _info;
}

+ (void)stopCachingThumbnailsOfPixelSize:(struct CGSize)arg1 forPHAssets:(id)arg2;
+ (void)startCachingThumbnailsOfPixelSize:(struct CGSize)arg1 forPHAssets:(id)arg2;
+ (void)requestFullResolutionImageWithIdentifierOrURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (id)thumbnailImageOfPixelSize:(struct CGSize)arg1 forAsset:(id)arg2;
+ (void)photoLibraryDidChange:(id)arg1;
+ (void)cancelImageRequest:(int)arg1;
+ (id)thumbnailCachingImageManager;
+ (struct CGSize)defaultCachedThumbnailSizeInPixels;
+ (void)initialize;
@property(readonly, nonatomic) id info; // @synthesize info=_info;
@property(nonatomic, getter=isLivePhotoSelectedAsVideo) BOOL livePhotoSelectedAsVideo; // @synthesize livePhotoSelectedAsVideo=_livePhotoSelectedAsVideo;
@property(nonatomic, getter=isSelected) BOOL selected; // @synthesize selected=_selected;
- (void).cxx_destruct;
- (void)performBlockWhenContentIsAvailable:(CDUnknownBlockType)arg1;
- (void)unloadDownloadedMedia;
@property(readonly, copy, nonatomic) NSData *GIFData;
@property(readonly, copy, nonatomic) UIImage *highResolutionImage;
@property(readonly, copy, nonatomic) UIImage *image;
@property(readonly, copy, nonatomic) NSURL *mediaURL;
- (void)downloadProgressDidFinish;
- (void)downloadProgressDidChange;
- (void)cancelDownloadMediaIfNeeded;
- (void)downloadMediaIfNeededPhotosKit;
- (void)downloadMediaIfNeededAssetsLibrary;
- (void)downloadMediaIfNeeded;
@property(readonly, nonatomic) float downloadProgress;
@property(readonly, nonatomic, getter=isContentAvailable) BOOL contentAvailable;
@property(readonly, nonatomic, getter=isDownloadCancelled) BOOL downloadCancelled;
@property(readonly, nonatomic, getter=isDownloading) BOOL downloading;
- (void)preloadOniOS7;
- (id)alAssetThumbnail;
- (void)requestWallpaperImageWithCompletionHandler:(CDUnknownBlockType)arg1;
- (int)requestCachedImageWithPixelSize:(struct CGSize)arg1 resultHandler:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) struct CGSize aspectRatio;
@property(readonly, nonatomic) NSDate *date;
@property(readonly, nonatomic) double duration;
@property(readonly, nonatomic) PHAsset *phAsset;
@property(readonly, nonatomic) unsigned int mediaSubtypes;
@property(readonly, nonatomic, getter=isUsable) BOOL usable;
@property(readonly, nonatomic) BOOL isLivePhoto;
- (BOOL)isGIF;
- (void)isGIFWithResultHandler:(CDUnknownBlockType)arg1;
- (BOOL)isVideo;
- (BOOL)isLocalIdentifierAvailable;
@property(readonly, nonatomic) id localIdentifier;
- (id)identifierForLogging;
- (void)updatePHFetchResult:(id)arg1 index:(unsigned int)arg2;
- (id)initWithPHFetchResult:(id)arg1 index:(unsigned int)arg2;
- (id)initWithALAsset:(id)arg1;

@end

