//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAMessageContainerSlice.h"

@class NSLayoutManager, NSString, NSTextContainer, NSTextStorage;

@interface WAMessageDocumentSlice : WAMessageContainerSlice
{
    NSString *_MIMEType;
    NSString *_fileExtension;
    NSTextStorage *_textStorage;
    NSTextContainer *_textContainer;
    NSLayoutManager *_layoutManager;
    struct CGRect _textRect;
    NSTextStorage *_iconTextStorage;
    NSTextContainer *_iconTextContainer;
    NSLayoutManager *_iconLayoutManager;
    struct CGRect _iconTextRect;
    BOOL _hasThumbnail;
    BOOL _mayShowProgressView;
    float _metadataSectionHeight;
}

+ (Class)viewClass;
@property(readonly, nonatomic) float metadataSectionHeight; // @synthesize metadataSectionHeight=_metadataSectionHeight;
@property(readonly, nonatomic) BOOL mayShowProgressView; // @synthesize mayShowProgressView=_mayShowProgressView;
@property(readonly, nonatomic) BOOL hasThumbnail; // @synthesize hasThumbnail=_hasThumbnail;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *iconImageName;
- (void)drawMetadataInCurrentContext;
- (void)internalFitToWidth:(float)arg1;
- (BOOL)showsMedia;
- (id)initWithMessages:(id)arg1 metrics:(CDStruct_c67131ad)arg2;

@end

