//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAMediaUploadOperationBase.h"

#import "NSStreamDelegate-Protocol.h"
#import "NSURLConnectionDelegate-Protocol.h"
#import "NSURLSessionDataDelegate-Protocol.h"
#import "NSURLSessionTaskDelegate-Protocol.h"

@class NSData, NSDate, NSInputStream, NSMutableData, NSOutputStream, NSString, NSURLSessionTask, NSURLSessionTaskMetrics, WAMediaCipher, WAMediaEncUploadSessionWrapper;
@protocol WAServerDate;

@interface WAMediaStreamUploadOperation : WAMediaUploadOperationBase <NSStreamDelegate, NSURLSessionTaskDelegate, NSURLSessionDataDelegate, NSURLConnectionDelegate>
{
    NSString *_fileName;
    BOOL _isExecuting;
    BOOL _isFinished;
    NSString *_uploadURL;
    NSString *_uploadIp;
    NSString *_uploadHost;
    NSMutableData *_receiveData;
    WAMediaCipher *_mediaCipher;
    NSDate<WAServerDate> *_startDate;
    BOOL _mediaComplete;
    BOOL _streamingCancelled;
    int _uploadPhase;
    int _waitCount;
    BOOL _didSendDataSuccessfully;
    unsigned int _retryCount;
    WAMediaEncUploadSessionWrapper *_sessionWrapper;
    NSURLSessionTaskMetrics *_taskMetrics;
    double _uploadURLFetchTime;
    double _uploadStartTime;
    double _lastWriteTime;
    double _responseWait;
    unsigned int _bytesWritten;
    BOOL _streamHasSpaceAvailable;
    NSString *_streamingHash;
    NSURLSessionTask *_uploadTask;
    NSData *_bodyPrefixData;
    NSData *_bodyFileData;
    NSData *_bodySuffixData;
    NSOutputStream *_producerStream;
    NSInputStream *_consumerStream;
    const char *_currentBuffer;
    unsigned int _bufferOffset;
    unsigned int _bufferLimit;
    unsigned int _fileOffset;
    NSString *_mediaLocalPath;
}

@property(nonatomic) BOOL streamHasSpaceAvailable; // @synthesize streamHasSpaceAvailable=_streamHasSpaceAvailable;
@property(copy, nonatomic) NSString *mediaLocalPath; // @synthesize mediaLocalPath=_mediaLocalPath;
@property(nonatomic) unsigned int fileOffset; // @synthesize fileOffset=_fileOffset;
@property(nonatomic) unsigned int bufferLimit; // @synthesize bufferLimit=_bufferLimit;
@property(nonatomic) unsigned int bufferOffset; // @synthesize bufferOffset=_bufferOffset;
@property(nonatomic) const char *currentBuffer; // @synthesize currentBuffer=_currentBuffer;
@property(retain, nonatomic) NSInputStream *consumerStream; // @synthesize consumerStream=_consumerStream;
@property(retain, nonatomic) NSOutputStream *producerStream; // @synthesize producerStream=_producerStream;
@property(copy, nonatomic) NSData *bodySuffixData; // @synthesize bodySuffixData=_bodySuffixData;
@property(copy, nonatomic) NSData *bodyFileData; // @synthesize bodyFileData=_bodyFileData;
@property(copy, nonatomic) NSData *bodyPrefixData; // @synthesize bodyPrefixData=_bodyPrefixData;
@property(retain, nonatomic) NSURLSessionTask *uploadTask; // @synthesize uploadTask=_uploadTask;
@property(copy, nonatomic) NSString *streamingHash; // @synthesize streamingHash=_streamingHash;
- (void).cxx_destruct;
- (BOOL)setStateForFallbackRetry;
- (id)recipientsRefs;
- (id)postBoundary;
- (void)stream:(id)arg1 handleEvent:(unsigned int)arg2;
- (void)processNextUploadChunk;
- (void)uploadRequestFailedWithError:(id)arg1;
- (void)uploadRequestFinishedWithResult:(id)arg1;
- (void)encUploadRequestFinishedWithResult:(id)arg1;
- (void)handleUploadTaskCompletedSuccessfully;
- (void)handleUploadTaskFailedWithError:(id)arg1;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 task:(id)arg2 didFinishCollectingMetrics:(id)arg3;
- (void)URLSession:(id)arg1 task:(id)arg2 didSendBodyData:(long long)arg3 totalBytesSent:(long long)arg4 totalBytesExpectedToSend:(long long)arg5;
- (void)URLSession:(id)arg1 task:(id)arg2 willPerformHTTPRedirection:(id)arg3 newRequest:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)URLSession:(id)arg1 task:(id)arg2 didReceiveChallenge:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)URLSession:(id)arg1 task:(id)arg2 needNewBodyStream:(CDUnknownBlockType)arg3;
- (void)reportFieldStatsWithResult:(int)arg1 error:(id)arg2;
- (id)uploadError;
- (id)cancelSuffixData;
- (id)suffixData;
- (id)mediaPath;
- (BOOL)shouldProceed;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (void)finish;
- (void)closeStreams;
- (void)startHTTPUploadToIp:(id)arg1;
- (void)reallyStartUpload;
- (void)cancelStreaming;
- (void)start;
- (void)dealloc;
- (void)assignMessage:(id)arg1 delegate:(id)arg2;
- (id)initWithMediaLocalPath:(id)arg1 urlSessionWrapper:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

