//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAMessageContainerSliceView.h"

@class UIImageView, WAMessageStickerSlice;

@interface WAMessageStickerSliceView : WAMessageContainerSliceView
{
    UIImageView *_imageView;
}

+ (BOOL)pairsWithQuickForwardButton;
+ (BOOL)isUserInteractionEnabled;
+ (BOOL)needsProgressView;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)reloadSliceAfterChange:(unsigned int)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, nonatomic) WAMessageStickerSlice *slice; // @dynamic slice;

@end

