//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, WAMediaKey, _WAMediaSidecarGenerator;

@interface WAMediaCipher2 : NSObject
{
    BOOL _complete;
    unsigned int _operation;
    struct _CCCryptor *_aesRef;
    struct CC_SHA256state_st _plaintextHashCtx;
    struct CC_SHA256state_st _ciphertextHashCtx;
    CDStruct_43cfb2c2 _hmacCtx;
    _WAMediaSidecarGenerator *_sidecarGenerator;
    WAMediaKey *_mediaKey;
    NSData *_plaintextHash;
    NSData *_ciphertextAndTruncatedMacHash;
    NSData *_hmac;
}

+ (BOOL)decryptMediaFileAtPath:(id)arg1 toPath:(id)arg2 withMediaKey:(id)arg3 plaintextHash:(out id *)arg4 ciphertextHash:(out id *)arg5;
+ (id)mediaCipherAfterEncryptingWithMediaKey:(id)arg1 fromFileURL:(id)arg2;
+ (id)mediaCipherWithMediaKey:(id)arg1 encrypt:(BOOL)arg2 withFileReader:(id)arg3 seekToOffset:(unsigned int)arg4 readBuffer:(id)arg5 writeBuffer:(id)arg6;
@property(readonly, nonatomic) BOOL complete; // @synthesize complete=_complete;
@property(readonly, nonatomic) NSData *hmac; // @synthesize hmac=_hmac;
@property(readonly, nonatomic) NSData *ciphertextAndTruncatedMacHash; // @synthesize ciphertextAndTruncatedMacHash=_ciphertextAndTruncatedMacHash;
@property(readonly, nonatomic) NSData *plaintextHash; // @synthesize plaintextHash=_plaintextHash;
@property(readonly, nonatomic) WAMediaKey *mediaKey; // @synthesize mediaKey=_mediaKey;
- (void).cxx_destruct;
- (unsigned long)outputLengthForInputLength:(unsigned long)arg1 final:(BOOL)arg2;
- (void)updateAdditionalResultsWithPlaintextIn:(const void *)arg1 plaintextLength:(unsigned long)arg2 ciphertextIn:(const void *)arg3 ciphertextLength:(unsigned long)arg4 final:(BOOL)arg5;
- (BOOL)finalizeWithDataOut:(void *)arg1 dataOutAvailable:(unsigned long)arg2 dataOutMoved:(unsigned int *)arg3;
- (BOOL)updateWithDataIn:(const void *)arg1 dataInLength:(unsigned long)arg2 dataOut:(void *)arg3 dataOutLength:(unsigned long)arg4 dataOutMoved:(unsigned int *)arg5;
@property(readonly, nonatomic) NSData *sidecar;
- (void)dealloc;
- (id)initWithMediaKey:(id)arg1 encrypt:(BOOL)arg2;
- (BOOL)seekToOffset:(unsigned int)arg1 withFileReader:(id)arg2 usingReadBuffer:(id)arg3 andWriteBuffer:(id)arg4;

@end

