//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WASimpleOperation-Protocol.h"

@class NSData, NSDate, NSError, NSString, WAMMSBaseTask, WAMMSMediaTransferOperationAsset, WAMMSMediaUploadOperationRequest, WAMMSTaskDescription, WAMMSTaskSession, WAMediaCipher2, WAMediaKey, WamEventMediaUpload;
@protocol OS_dispatch_queue, WADeviceDate, WAMMSMediaUploadOperationDelegate;

@interface WAMMSMediaUploadOperation : NSObject <WASimpleOperation>
{
    WAMMSMediaUploadOperationRequest *_request;
    unsigned int _currentRetryCount;
    WAMMSTaskSession *_taskSession;
    NSObject<OS_dispatch_queue> *_queue;
    id <WAMMSMediaUploadOperationDelegate> _delegate;
    NSDate<WADeviceDate> *_queuedTime;
    WAMMSBaseTask *_currentTask;
    NSData *_fakeStreamingHash;
    unsigned int _uploadType;
    BOOL _finishedStreaming;
    NSError *_error;
    BOOL _isTerminalError;
    // Error parsing type: AI, name: _currentPhase
    WAMediaCipher2 *_finalizedMediaCipherForAsset;
    WAMMSTaskDescription *_commonMMSTaskDescription;
    WAMMSMediaTransferOperationAsset *_currentAsset;
    WAMediaKey *_mediaKey;
    NSData *_hashIdentifier;
    BOOL _usedFakeHashIdentifier;
    unsigned int _uploadOffset;
    // Error parsing type: Ai, name: _progressPercentage
    NSString *_downloadURL;
    NSData *_responseData;
    double _startTime;
    double _optimisticUploadTakeoverTime;
    WamEventMediaUpload *_uploadEvent;
    double _resumeCheckRouteRequestTimeInterval;
    NSError *_uploadError;
}

+ (BOOL)generateFromError:(id)arg1 httpResponse:(id)arg2 uploadEventResult:(int *)arg3 finalError:(out id *)arg4 terminal:(char *)arg5;
@property(readonly, nonatomic) NSData *fakeStreamingHash; // @synthesize fakeStreamingHash=_fakeStreamingHash;
@property(retain) NSError *uploadError; // @synthesize uploadError=_uploadError;
- (void).cxx_destruct;
- (void)setAndRunCompletionPhaseWithError:(id)arg1 httpResponse:(id)arg2;
- (void)performCompletionPhase;
- (void)performFinalizePhase;
- (void)performFileUploadPhase;
- (void)performResumeCheck;
- (void)performPreflightPhase;
- (void)runPhase;
@property(readonly, nonatomic) unsigned int taskType;
@property(readonly, nonatomic) BOOL optimistic;
@property(readonly, nonatomic) BOOL streaming;
@property unsigned int currentPhase;
- (void)optimisticUploadTakeover;
- (void)finishStreaming;
- (void)queued;
- (void)cancel;
- (void)resume;
@property(readonly) double progressPercentage;
@property(readonly) WAMMSMediaUploadOperationRequest *request;
- (id)initWithUploadRequest:(id)arg1 mmsSession:(id)arg2 queue:(id)arg3 uploadType:(unsigned int)arg4 delegate:(id)arg5;
- (id)initWithUploadRequest:(id)arg1 mmsSession:(id)arg2 queue:(id)arg3 delegate:(id)arg4;
- (void)start;
- (unsigned int)priority;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

