//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WAMMSMediaDownloadOperationHelper : NSObject
{
}

+ (id)downloadPathForCiphertextHash:(id)arg1;
+ (id)downloadOperationWithMediaKey:(id)arg1 ciphertextHash:(id)arg2 ciphertextFilePath:(id)arg3 plaintextHash:(id)arg4 plaintextFilePath:(id)arg5 isStatus:(BOOL)arg6 mimeType:(id)arg7 autoDownload:(BOOL)arg8 allowsCellularAccess:(BOOL)arg9 maxConcurrentOperations:(unsigned int)arg10 expectedFileLength:(unsigned int)arg11 mmsTaskSession:(id)arg12 queue:(id)arg13 delegate:(id)arg14;
+ (id)downloadOperationWithSticker:(id)arg1 autoDownload:(BOOL)arg2 allowsCellularAccess:(BOOL)arg3 maxConcurrentOperations:(unsigned int)arg4 mmsTaskSession:(id)arg5 queue:(id)arg6 delegate:(id)arg7;
+ (id)downloadOperationWithMessage:(id)arg1 autoDownload:(BOOL)arg2 allowsCellularAccess:(BOOL)arg3 maxConcurrentOperations:(unsigned int)arg4 mmsTaskSession:(id)arg5 queue:(id)arg6 delegate:(id)arg7;

@end

