//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAViewController.h"

#import "MKMapViewDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "WACardNavigationControllerDelegate-Protocol.h"
#import "WALiveLocationFriendsDataSource-Protocol.h"
#import "WALiveLocationFriendsDelegate-Protocol.h"
#import "WALiveLocationMapViewDelegate-Protocol.h"
#import "WALiveLocationMenuTableViewControllerDelegate-Protocol.h"
#import "WALiveLocationSender-Protocol.h"
#import "WALocationUpdateHandler-Protocol.h"
#import "WAMapBatchUpdaterDelegate-Protocol.h"
#import "WAShareLocationControllerDelegate-Protocol.h"

@class NSArray, NSMutableDictionary, NSSet, NSString, NSTimer, UIBarButtonItem, UITapGestureRecognizer, UIToolbar, WACardNavigationController, WAChatSession, WAFriendLocationAnnotationView, WAGroupedAnnotation, WALiveLocationFriendsTableViewController, WALiveLocationMapView, WALocationGroupMembersTableViewController, WALocationUpdateThrottler, WAMapBatchUpdater, WAMapTypeSegmentedControl, WAMapWrapperView, WANewUserExperienceView, WAUserTrackingButton, WAWeakTimer, WAZoomOutButton;
@protocol WANewFriendsLocationViewControllerDelegate;

@interface WANewFriendsLocationViewController : WAViewController <MKMapViewDelegate, UIGestureRecognizerDelegate, WACardNavigationControllerDelegate, WALiveLocationFriendsDataSource, WALiveLocationFriendsDelegate, WALiveLocationMapViewDelegate, WALiveLocationMenuTableViewControllerDelegate, WALiveLocationSender, WALocationUpdateHandler, WAMapBatchUpdaterDelegate, WAShareLocationControllerDelegate>
{
    WAUserTrackingButton *_userTrackingButton;
    WAZoomOutButton *_zoomOutButton;
    NSString *_groupJID;
    WAChatSession *_chatSession;
    NSMutableDictionary *_participantsLocations;
    BOOL _autoScale;
    BOOL _sharingIsActive;
    NSTimer *_annotationsUpdateTimer;
    WACardNavigationController *_navigationController;
    WALiveLocationFriendsTableViewController *_tableViewController;
    WALocationGroupMembersTableViewController *_focusedGroupTableViewController;
    BOOL _regionChangeIsUserInitiated;
    BOOL _updateWhenUserLocationArrives;
    WANewUserExperienceView *_newUserExperienceView;
    WAMapWrapperView *_mapWrapper;
    WAMapTypeSegmentedControl *_segmentedControl;
    UIBarButtonItem *_segmentedControlBarItem;
    WAWeakTimer *_removeUserAnnotationTimer;
    WAWeakTimer *_updateMapTimer;
    NSString *_focusedJID;
    BOOL _needsReload;
    WAMapBatchUpdater *_updater;
    BOOL _updateAfterRegionChange;
    NSArray *_portraitConstraints;
    NSArray *_landscapeConstraints;
    BOOL _updating;
    NSString *_anchorJID;
    double _statusLockedUntil;
    WALocationUpdateThrottler *_throttler;
    NSSet *_focusedGroupJIDs;
    UITapGestureRecognizer *_touchRecognizer;
    BOOL _menuOpen;
    NSString *_selectedJID;
    WAFriendLocationAnnotationView *_selectedAnnotationView;
    WAGroupedAnnotation *_focusedGroupAnnotation;
    BOOL _suppressStatusChanges;
    BOOL _restoreAutoScale;
    BOOL _zoomingOnGroup;
    BOOL _haveOutstandingSubscriptionRequest;
    id <WANewFriendsLocationViewControllerDelegate> _delegate;
    WALiveLocationMapView *_mapViewMain;
    UIToolbar *_toolbar;
}

@property BOOL haveOutstandingSubscriptionRequest; // @synthesize haveOutstandingSubscriptionRequest=_haveOutstandingSubscriptionRequest;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) WALiveLocationMapView *mapViewMain; // @synthesize mapViewMain=_mapViewMain;
@property(nonatomic) __weak id <WANewFriendsLocationViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)liveLocationMapViewBounceGroupedAnnotation:(id)arg1;
- (void)liveLocationMenuWillDismiss;
- (void)liveLocationMenuDidSelectShareLiveLocation;
- (void)liveLocationMenuMapTypeDidChange:(unsigned int)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)sendMessageContainingPlace:(id)arg1 liveLocationEndDate:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)shareLocationControllerDidCancel:(id)arg1;
- (void)shareLocationControllerDidSelectWAPlace:(id)arg1;
- (void)mapBatchUpdaterDidUpdateJID:(id)arg1 newLocation:(id)arg2;
- (void)cardNavigationControllerStatusSelected:(id)arg1;
- (void)cardNavigationControllerDidPopLastViewController:(id)arg1;
- (void)cardNavigationController:(id)arg1 opaqueFrameDidChange:(struct CGRect)arg2;
- (void)liveLocationTableViewDidScroll;
- (id)liveLocationTableViewChatSession;
- (void)showAnnotation:(id)arg1;
- (void)liveLocationTableViewShowFriend:(id)arg1;
- (id)sortedFriendLocationsForDictionary:(id)arg1;
- (void)liveLocationFriends:(id)arg1 getFriendsBlock:(CDUnknownBlockType)arg2;
- (void)removeUserAnnotationIfSharingEnded;
- (void)updateUserLocation:(id)arg1;
- (void)mapView:(id)arg1 didUpdateUserLocation:(id)arg2;
- (void)mapView:(id)arg1 didAddAnnotationViews:(id)arg2;
- (void)mapView:(id)arg1 annotationView:(id)arg2 calloutAccessoryControlTapped:(id)arg3;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)updateAlphaOfGroupedAnnotation:(id)arg1 withAnnotationView:(id)arg2;
- (void)zoomOnGroup:(id)arg1;
- (void)mapView:(id)arg1 didDeselectAnnotationView:(id)arg2;
- (void)mapView:(id)arg1 didSelectAnnotationView:(id)arg2;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(BOOL)arg2;
- (void)mapView:(id)arg1 regionWillChangeAnimated:(BOOL)arg2;
- (void)sendMessageTo:(id)arg1;
- (void)placeCallToJID:(id)arg1 video:(BOOL)arg2;
- (void)unblockContact:(id)arg1;
- (void)askToUnblockContactBeforeCalling:(id)arg1;
- (BOOL)contactIsBlocked:(id)arg1;
- (void)showContactInfoForJID:(id)arg1;
- (BOOL)haveLocationPermission;
- (void)followJID:(id)arg1;
- (id)allParticipantsLocations;
- (void)asyncActiveParticipantsLocations:(CDUnknownBlockType)arg1;
- (void)asyncActiveJIDs:(CDUnknownBlockType)arg1;
- (id)chatSession;
- (void)activateLandscapeConstraints:(BOOL)arg1;
- (void)activatePortraitConstraints:(BOOL)arg1;
- (void)updateConstraintsForCurrentOrientation;
- (BOOL)landscapeMode;
- (void)removeInactiveParticipants:(id)arg1;
- (void)sharingEndDateDidChange:(id)arg1;
- (void)didRemoveSenderFromGroup:(id)arg1;
- (void)locationStorageSenderEndDateDidChange:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)xmppConnectionLocationSharingChangedNotification:(id)arg1;
- (void)xmppConnectionLocationNotification:(id)arg1;
- (id)annotationWithJID:(id)arg1;
- (void)setNeedsReload;
- (void)didGetActiveParticipantsLocations:(id)arg1 jidsFromDatabase:(id)arg2 jidsFromServer:(id)arg3 xmppParticipants:(id)arg4 amSharing:(BOOL)arg5;
- (void)didRequestLocationSharingWithParticipants:(id)arg1;
- (id)databaseJIDs;
- (void)handleRequestLocationSharingResponseWithError:(id)arg1 resubscribePeriod:(int)arg2 requestedParticipants:(BOOL)arg3 participants:(id)arg4 retries:(int)arg5;
- (BOOL)updateLocationsUsingTestDriverWithParticipants:(BOOL)arg1 retries:(int)arg2;
- (void)requestLocationsWithParticipants:(BOOL)arg1 retries:(int)arg2;
- (void)requestLocationsWithParticipants:(BOOL)arg1;
- (void)resubscribeForLocations;
- (void)onAnnotationsUpdateTimer;
- (void)reallySetLocation:(id)arg1 forJid:(id)arg2 lastUpdateDate:(id)arg3;
- (BOOL)setLocation:(id)arg1 forJid:(id)arg2 lastUpdateDate:(id)arg3;
- (double)maximumAccuracyAmongAnnotations:(id)arg1;
- (id)allAnnotationsExceptUser;
- (void)reallyAutoSetMapRegionAnimated:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)autosetMapRegionAnimated:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (BOOL)centerOnUserLocation;
- (struct UIEdgeInsets)edgePadding;
- (struct UIEdgeInsets)preferredLayoutMargins;
- (id)invalidLocation;
- (id)myCachedLocation;
- (void)addSender:(id)arg1;
- (void)updateStatusMessage;
- (void)tapOnMap:(id)arg1;
- (void)showMenu:(id)arg1;
- (void)zoomOut:(id)arg1;
- (void)changeUserTrackingModeAction:(id)arg1;
- (void)updateFocusedGroupMembership;
- (void)finishUpdate;
- (void)update;
- (void)mapTypeChanged:(id)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)stopTracking;
- (BOOL)setStatus:(id)arg1 minimumDuration:(double)arg2 highPriority:(BOOL)arg3;
- (void)showNeedLocationPermissionStatus;
- (void)showInitialStatus;
- (BOOL)lackNeededLocationPermission;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (BOOL)amSharing;
- (void)updateAndRestartTimer;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateMenuButton;
- (struct CGPoint)standardCenterOffset;
- (void)dismissGroupMembersTableView:(id)arg1;
- (void)focusOnGroupAnnotation:(id)arg1;
- (void)viewDidLayoutSubviews;
- (BOOL)rtl;
- (void)setupIOS7Toolbar;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithGroupJID:(id)arg1 anchorJID:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

