//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSFileHandle;

@interface WAOffsetsFile : NSObject
{
    NSFileHandle *_handle;
    unsigned long long *_offsets;
    unsigned int _lastChangedBlock;
    BOOL _readOnly;
    unsigned int _maximumCount;
    unsigned int _count;
}

@property(readonly, nonatomic) unsigned int count; // @synthesize count=_count;
- (void).cxx_destruct;
- (unsigned int)blockForIndex:(unsigned int)arg1;
- (void)save;
- (void)invalidateFromIndex:(unsigned int)arg1;
- (void)loadBlock:(unsigned int)arg1;
- (void)setOffset:(unsigned long long)arg1 atIndex:(unsigned int)arg2;
- (unsigned long long)offsetAtIndex:(unsigned int)arg1;
- (void)dealloc;
- (id)initWithHandle:(id)arg1 readOnly:(BOOL)arg2 maximumCount:(unsigned int)arg3;
- (id)initWithPath:(id)arg1 readOnly:(BOOL)arg2 maximumCount:(unsigned int)arg3;
- (id)initWithReadOnlyPath:(id)arg1;
- (id)initWithUpdatablePath:(id)arg1 maximumCount:(unsigned int)arg2;
- (id)initWithPath:(id)arg1 andCount:(unsigned int)arg2;
- (id)init;

@end

