//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAStaticTableViewController.h"

#import "WAPaymentUPICoordinatorDelegate-Protocol.h"

@class NSString, WAPaymentAccount, WAPaymentUPICoordinator, WAProgressAlertController;

@interface WAPaymentAccountViewController : WAStaticTableViewController <WAPaymentUPICoordinatorDelegate>
{
    WAPaymentAccount *_account;
    WAPaymentUPICoordinator *_coordinator;
    WAProgressAlertController *_progressController;
}

- (void).cxx_destruct;
- (void)paymentUPICoordinatorDidUserCancel:(id)arg1;
- (void)paymentUPICoordinatorDidFail:(id)arg1 error:(id)arg2;
- (void)paymentUPICoordinatorDidComplete:(id)arg1 result:(id)arg2;
- (void)resetUPIMPIN;
- (void)changeUPIMPIN;
- (void)checkUPIMPIN;
- (void)processAccountRemovalRequest:(id)arg1;
- (void)reallyUnlinkPaymentAccount;
- (void)unlinkPaymentAccount;
- (void)processEditDefaultCredentialRequest:(id)arg1;
- (void)makeDefault;
- (void)setupTableView;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithPaymentAccount:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

