//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAPaintBrushRenderer.h"

@interface WAPaintBrushBitmapContextRenderer : WAPaintBrushRenderer
{
    struct CGSize _stampSize;
}

+ (BOOL)requiresPaintBlobPaintPositionSampleEquivalence;
+ (int)defaultCapacity;
- (struct CGSize)brushSizeHint;
- (void)setPaintBlob:(CDStruct_37a3040a)arg1 atIndex:(unsigned int)arg2;
- (BOOL)addPaintBlob:(CDStruct_37a3040a)arg1;

@end

