//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WAPaymentTextFormatters-Protocol.h"

@class NSNumberFormatter, NSString;

@interface WAPaymentMoneyTextFormatter : NSObject <WAPaymentTextFormatters>
{
    NSNumberFormatter *_moneyFormatter;
}

- (void).cxx_destruct;
- (id)numberForFormattedString:(id)arg1;
- (id)formattedStringForNumber:(id)arg1;
- (id)stringValueForFormattedString:(id)arg1;
- (id)stringForStringValue:(id)arg1 trimSystemCharacters:(BOOL)arg2;
- (BOOL)isValidStringForFormatting:(id)arg1;
- (id)initWithCurrencyCode:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

