//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WAPaintCanvasTextItemView;

@protocol WAPaintCanvasTextItemViewDelegate <NSObject>
-     // Error parsing type: {?=[3]}12@0:4@"WAPaintCanvasTextItemView"8, name: canvasSpaceToCropSpaceTransformForItemView:
- (CDStruct_1a69c163)canvasTransformInfoForItemView:(WAPaintCanvasTextItemView *)arg1;
@end

