//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIColor;
@protocol WAPaymentsBubbleThemeProtocol, WAPaymentsPaymentDetailsCellThemeProtocol;

@interface WAPaymentsTheme : NSObject
{
    UIColor *_failureIconColor;
    UIColor *_successIconColor;
    UIColor *_pendingIconColor;
    UIColor *_refundedIconColor;
    UIColor *_iconTextColor;
    UIColor *_highlightedTextBackgroundColor;
    id <WAPaymentsBubbleThemeProtocol> _bubble;
    id <WAPaymentsPaymentDetailsCellThemeProtocol> _paymentDetailsCell;
}

@property(readonly, nonatomic) id <WAPaymentsPaymentDetailsCellThemeProtocol> paymentDetailsCell; // @synthesize paymentDetailsCell=_paymentDetailsCell;
@property(readonly, nonatomic) id <WAPaymentsBubbleThemeProtocol> bubble; // @synthesize bubble=_bubble;
@property(readonly, nonatomic) UIColor *highlightedTextBackgroundColor; // @synthesize highlightedTextBackgroundColor=_highlightedTextBackgroundColor;
@property(readonly, nonatomic) UIColor *iconTextColor; // @synthesize iconTextColor=_iconTextColor;
@property(readonly, nonatomic) UIColor *refundedIconColor; // @synthesize refundedIconColor=_refundedIconColor;
@property(readonly, nonatomic) UIColor *pendingIconColor; // @synthesize pendingIconColor=_pendingIconColor;
@property(readonly, nonatomic) UIColor *successIconColor; // @synthesize successIconColor=_successIconColor;
@property(readonly, nonatomic) UIColor *failureIconColor; // @synthesize failureIconColor=_failureIconColor;
- (void).cxx_destruct;
- (void)dealloc;
- (void)contentSizeCategoryDidChange:(id)arg1;
- (id)init;

@end

