//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSLocale;

@interface WAPaymentSettings : NSObject
{
    NSLocale *_localeForCurrency;
}

- (void).cxx_destruct;
- (short)amountPrecision;
- (id)maximumAmount;
- (id)minimumAmount;
- (int)defaultPayoutMethod;
- (int)defaultPaymentMethod;
- (id)localeForCurrency;
- (id)currencyDecimalSeparatorSymbol;
- (id)currencySymbol;
- (id)currencyCode;
- (id)countryCode;
- (BOOL)enabled;

@end

