//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAStaticTableViewController.h"

#import "WAPaymentUPICoordinatorDelegate-Protocol.h"

@class NSString, WAPaymentUPICoordinator, WAProgressAlertController, WATableSection;

@interface WAPaymentsViewController : WAStaticTableViewController <WAPaymentUPICoordinatorDelegate>
{
    BOOL _reloadDataInViewWillAppear;
    WATableSection *_sectionPaymentHistory;
    BOOL _paymentAccountsSynchronized;
    WATableSection *_sectionPaymentAccounts;
    WATableSection *_sectionDeletePaymentAccount;
    WAPaymentUPICoordinator *_coordinator;
    WAProgressAlertController *_progressController;
}

- (void).cxx_destruct;
- (void)processAccountRemovalRequest:(id)arg1;
- (void)reallyDeletePaymentAccount;
- (void)deletePaymentAccount;
- (void)reloadDeletePaymentAccountSectionAndUpdateTableView:(BOOL)arg1;
- (void)paymentUPICoordinatorDidUserCancel:(id)arg1;
- (void)paymentUPICoordinatorDidFail:(id)arg1 error:(id)arg2;
- (void)paymentUPICoordinatorDidComplete:(id)arg1 result:(id)arg2;
- (void)addPaymentAccount;
- (void)showDetailsForPaymentAccount:(id)arg1;
- (void)processGetMethodsRequest:(id)arg1;
- (void)synchronizePaymentAccounts;
- (void)reloadPaymentAccountsAndUpdateTableView:(BOOL)arg1;
- (void)showTransactionHistory;
- (void)showTransactionDetails:(id)arg1;
- (void)reloadPaymentHistoryAndUpdateTableView:(BOOL)arg1;
- (void)showSupportPage;
- (void)paymentTransactionUpdated:(id)arg1;
- (void)paymentAccountUpdated:(id)arg1;
- (void)dealloc;
- (void)setupTableView;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

