//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSData, NSString, WAPBContextInfo;

@interface WAPBMessage_LocationMessage : GPBMessage
{
}

+ (id)descriptor;
@property(copy, nonatomic) NSString *addressWithSanitization;
@property(copy, nonatomic) NSString *nameWithSanitization;

// Remaining properties
@property(copy, nonatomic) NSString *URL; // @dynamic URL;
@property(nonatomic) unsigned int accuracyInMeters; // @dynamic accuracyInMeters;
@property(copy, nonatomic) NSString *address; // @dynamic address;
@property(copy, nonatomic) NSString *comment; // @dynamic comment;
@property(retain, nonatomic) WAPBContextInfo *contextInfo; // @dynamic contextInfo;
@property(nonatomic) unsigned int degreesClockwiseFromMagneticNorth; // @dynamic degreesClockwiseFromMagneticNorth;
@property(nonatomic) double degreesLatitude; // @dynamic degreesLatitude;
@property(nonatomic) double degreesLongitude; // @dynamic degreesLongitude;
@property(nonatomic) BOOL hasAccuracyInMeters; // @dynamic hasAccuracyInMeters;
@property(nonatomic) BOOL hasAddress; // @dynamic hasAddress;
@property(nonatomic) BOOL hasComment; // @dynamic hasComment;
@property(nonatomic) BOOL hasContextInfo; // @dynamic hasContextInfo;
@property(nonatomic) BOOL hasDegreesClockwiseFromMagneticNorth; // @dynamic hasDegreesClockwiseFromMagneticNorth;
@property(nonatomic) BOOL hasDegreesLatitude; // @dynamic hasDegreesLatitude;
@property(nonatomic) BOOL hasDegreesLongitude; // @dynamic hasDegreesLongitude;
@property(nonatomic) BOOL hasIsLive; // @dynamic hasIsLive;
@property(nonatomic) BOOL hasJpegThumbnail; // @dynamic hasJpegThumbnail;
@property(nonatomic) BOOL hasName; // @dynamic hasName;
@property(nonatomic) BOOL hasSpeedInMps; // @dynamic hasSpeedInMps;
@property(nonatomic) BOOL hasURL; // @dynamic hasURL;
@property(nonatomic) BOOL isLive; // @dynamic isLive;
@property(copy, nonatomic) NSData *jpegThumbnail; // @dynamic jpegThumbnail;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(nonatomic) float speedInMps; // @dynamic speedInMps;

@end

