//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@interface WAPBGroupInfoExtension_Permissions : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int editing; // @dynamic editing;
@property(nonatomic) unsigned long long editingTimestamp; // @dynamic editingTimestamp;
@property(nonatomic) BOOL hasEditing; // @dynamic hasEditing;
@property(nonatomic) BOOL hasEditingTimestamp; // @dynamic hasEditingTimestamp;
@property(nonatomic) BOOL hasMessaging; // @dynamic hasMessaging;
@property(nonatomic) BOOL hasMessagingTimestamp; // @dynamic hasMessagingTimestamp;
@property(nonatomic) int messaging; // @dynamic messaging;
@property(nonatomic) unsigned long long messagingTimestamp; // @dynamic messagingTimestamp;

@end

