//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@class WAProfilePictureCacheItem;

@interface WAProfilePictureFixedThumbnailView : UIImageView
{
    BOOL _needsImage;
    BOOL _round;
    WAProfilePictureCacheItem *_profilePicture;
}

@property(nonatomic, getter=isRound) BOOL round; // @synthesize round=_round;
@property(retain, nonatomic) WAProfilePictureCacheItem *profilePicture; // @synthesize profilePicture=_profilePicture;
- (void).cxx_destruct;
- (void)loadIfNeeded;
- (void)updateImage;
- (void)layoutSubviews;
- (void)copyFrom:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

