//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FMDatabaseQueue, NSCharacterSet, NSPredicate;
@protocol OS_dispatch_queue;

@interface WASearchEngine : NSObject
{
    FMDatabaseQueue *_dbQueue;
    NSObject<OS_dispatch_queue> *_privateQueue;
    NSCharacterSet *_whitespaceCharacterSet;
    NSCharacterSet *_punctuationCharacterSet;
    long long _lastRowID;
    BOOL _indexingEnabled;
    // Error parsing type: Ai, name: _closeDatabaseCounter
    NSPredicate *_predicateForIndexableMessages;
}

- (void).cxx_destruct;
- (id)searchTermToQueryDocsFor:(id)arg1;
- (void)queryDocsForSearchContent:(int)arg1 matchingSearchTerm:(id)arg2 chatSessionJIDs:(id)arg3 minimumScore:(float)arg4 type:(int)arg5 offset:(unsigned int)arg6 limit:(unsigned int)arg7 docIDs:(id *)arg8 countOfMatches:(id *)arg9;
- (id)docIDsMatchingSearchTerm:(id)arg1 chatSessionJIDs:(id)arg2 minimumScore:(float)arg3 type:(int)arg4 offset:(unsigned int)arg5 limit:(unsigned int)arg6;
- (id)totalCountOfMessagesMatchingSearchTerm:(id)arg1 chatSessionJIDs:(id)arg2 type:(int)arg3;
- (void)setDocumentType:(int)arg1 ofDocIDs:(id)arg2;
- (void)updateSearchScoreForMessage:(id)arg1;
- (void)removeDocIDs:(id)arg1;
- (void)removeMessage:(id)arg1;
- (id)internalInsertTo:(id)arg1 timeShift:(double)arg2 message:(id)arg3;
- (void)internalIndexMessages:(id)arg1;
- (BOOL)isMessageValid:(id)arg1;
- (int)indexMessagesOfCount:(unsigned int)arg1 inContext:(id)arg2;
- (BOOL)indexMessages:(id)arg1;
- (BOOL)openDatabaseAtPath:(id)arg1;
- (void)openDatabaseIfNeeded;
- (void)markSearchDatabaseAsCorrupted;
- (void)deleteDatabaseShouldBackupToTmpDirectory:(BOOL)arg1;
- (unsigned int)numberOfIndexedMessages;
- (unsigned long long)sizeOfDatabase;
- (BOOL)isIndexReady;
- (void)markIndexReady;
- (void)closeDatabaseAfterDelayIfIdle;
- (void)internalCloseDatabase;
- (void)closeDatabase;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)dealloc;
- (id)init;

@end

