//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WASQLObject : NSObject
{
}

+ (unsigned int)countInDB:(struct sqlite3 *)arg1;
+ (BOOL)createTableIfNecessaryInDB:(struct sqlite3 *)arg1;
+ (id)tableName;
- (BOOL)replaceInDB:(struct sqlite3 *)arg1;
- (BOOL)insertIntoDB:(struct sqlite3 *)arg1;
- (BOOL)insertOrReplace:(id)arg1 db:(struct sqlite3 *)arg2;
- (BOOL)deleteFromDB:(struct sqlite3 *)arg1;
- (id)initWithDictionary:(id)arg1;
- (BOOL)populateWithDictionary:(id)arg1;
- (BOOL)bindAllValuesToStatement:(id)arg1;
- (id)allValues;
- (BOOL)bindIdentityToStatement:(id)arg1;
- (id)identityWhereClause;

@end

