//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WAStatusHelper : NSObject
{
}

+ (id)shortWebURLFromText:(id)arg1;
+ (int)statusTextLengthforTextLength:(unsigned int)arg1;
+ (int)alignmentForTextLength:(unsigned int)arg1;
+ (float)fontSizeForTextLength:(unsigned int)arg1;
+ (id)fontImageForFontType:(int)arg1;
+ (id)fontOfType:(int)arg1 forTextLength:(unsigned int)arg2;

@end

