//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, NSString, WAMessage, WAStreamingMediaLoaderManager, WAStreamingMediaLoaderProgress;

@protocol WAStreamingMediaLoaderManagerDownloadDelegate <NSObject>
- (void)streamingMediaLoaderManager:(WAStreamingMediaLoaderManager *)arg1 didFailToDownloadMediaInMessage:(WAMessage *)arg2 userInitiated:(BOOL)arg3 error:(NSError *)arg4;
- (void)streamingMediaLoaderManager:(WAStreamingMediaLoaderManager *)arg1 didFinishDownloadingMediaInMessage:(WAMessage *)arg2 ackRef:(NSString *)arg3 toRelativePath:(NSString *)arg4;
- (void)streamingMediaLoaderManager:(WAStreamingMediaLoaderManager *)arg1 didUpdateDownloadProgress:(WAStreamingMediaLoaderProgress *)arg2 inMessage:(WAMessage *)arg3;
- (void)streamingMediaLoaderManager:(WAStreamingMediaLoaderManager *)arg1 didBeginDownloadingMediaInMessage:(WAMessage *)arg2 currentProgress:(WAStreamingMediaLoaderProgress *)arg3;
@end

