//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSError, NSHTTPURLResponse, NSString, NSURLRequest, NSURLSessionDownloadTask, WAURLTaskData;

@interface WAURLSessionTask : NSObject
{
    int _processingCounter;
    NSError *_error;
    NSURLSessionDownloadTask *_task;
}

+ (id)queue;
@property(retain, nonatomic) NSURLSessionDownloadTask *task; // @synthesize task=_task;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
- (void).cxx_destruct;
- (void)reportStatsWithResult:(int)arg1 error:(id)arg2;
- (BOOL)prepareForRetryWithError:(id)arg1;
@property(readonly, copy, nonatomic) NSString *shortIdentifier;
@property(readonly, copy, nonatomic) NSString *identifier;
@property(copy, nonatomic) WAURLTaskData *taskData;
@property(readonly, nonatomic) long long countOfBytesReceived;
@property(readonly, nonatomic) NSHTTPURLResponse *response;
@property(readonly, nonatomic) NSURLRequest *currentRequest;
@property(readonly, nonatomic) int state;
- (void)endProcessingTaskData;
- (void)beginProcessingTaskData;
@property(readonly, nonatomic) float progress;
- (void)destroy;
- (void)suspend;
- (void)resume;
- (id)initWithTaskHandler:(id)arg1;

@end

