//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAViewController.h"

#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSManagedObjectContext, NSManagedObjectModel, NSMutableArray, NSString, UIButton, UIImage, UIImageView, UIMotionEffectGroup, UIScrollView, UISegmentedControl, UITableView, UIView;
@protocol WAWallpaperPreviewControllerDelegate;

@interface WAWallpaperPreviewController : WAViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
{
    UIView *_bottomView;
    BOOL _inversePaging;
    UIScrollView *_pagingScrollView;
    NSMutableArray *_scrollViewPages;
    UIScrollView *_scrollView;
    UIImageView *_imageView;
    UITableView *_tableViewMessages;
    UISegmentedControl *_wallpaperModeControl;
    UIMotionEffectGroup *_parallaxEffect;
    BOOL _parallaxEnabled;
    UIButton *_buttonDone;
    UIButton *_buttonCancel;
    NSArray *_leftCellDataObjects;
    NSArray *_middleCellDataObjects;
    NSArray *_rightCellDataObjects;
    NSArray *_singlePhotoCellDataObjects;
    NSManagedObjectContext *_moc;
    NSManagedObjectModel *_model;
    id <WAWallpaperPreviewControllerDelegate> _delegate;
    int _libraryMode;
    int _libraryObjectIndex;
    UIImage *_image;
}

+ (id)controllerWithSolidColorIndex:(unsigned int)arg1;
+ (id)controllerWithLibraryImageIndex:(unsigned int)arg1;
+ (id)controllerWithImage:(id)arg1;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) int libraryObjectIndex; // @synthesize libraryObjectIndex=_libraryObjectIndex;
@property(nonatomic) int libraryMode; // @synthesize libraryMode=_libraryMode;
@property(nonatomic) __weak id <WAWallpaperPreviewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)chatCellDataObjectsForTableView:(id)arg1;
- (id)cellDataWithText:(id)arg1 isIncoming:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(float)arg3;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)updateScrollViewAfterEnablingMotion:(BOOL)arg1;
- (void)checkIfMotionShouldBeDisabledUnintentionally;
- (void)updateWallpaperModeControlState;
- (void)setParallaxEffectEnabled:(BOOL)arg1;
- (void)wallpaperModeChanged:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)doneAction:(id)arg1;
- (void)bottomButtonAnyTouch:(id)arg1;
- (id)imageForCurrentZoomRect;
- (void)reloadSingleImage;
- (void)setCurrentObjectIndex:(unsigned int)arg1;
- (void)scrollToObjectAtIndex:(int)arg1 animated:(BOOL)arg2;
- (void)unloadScrollViewPageForObjectAtIndex:(int)arg1;
- (void)loadFullImageForScrollViewPage:(id)arg1 objectIndex:(unsigned int)arg2;
- (void)loadScrollViewPageForObjectAtIndex:(int)arg1 shouldLoadFullImage:(BOOL)arg2;
- (int)objectIndexForScrollViewPageIndex:(int)arg1;
- (int)scrollViewPageIndexForObjectIndex:(int)arg1;
- (id)newWallpaperModeControl;
- (id)newSampleConversationTable;
- (void)presentFromViewController:(id)arg1 animated:(BOOL)arg2;
- (unsigned int)supportedInterfaceOrientations;
- (void)relayoutPage:(id)arg1 atIndex:(int)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

