//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAAnalogClockStamp.h"

@interface WAWhiteAnalogClockStamp : WAAnalogClockStamp
{
}

- (Class)nextContentStampClass;
- (id)initWithCoder:(id)arg1;
- (id)initWithImageName:(id)arg1 minuteHand:(id)arg2 hourHand:(id)arg3;
- (id)init;
- (id)initWithContentStamp:(id)arg1;

@end

