//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WAWordStemmer : NSObject
{
    struct sb_stemmer *_stemmer;
}

+ (id)stemmerForLanguage:(id)arg1;
+ (id)stemmerForCurrentLanguage;
+ (id)stemmerForMainQueue;
- (const char *)stemForWord:(const char *)arg1 length:(int)arg2;
- (void)dealloc;
- (id)initWithStemmer:(struct sb_stemmer *)arg1;

@end

