//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_XMPPWebClientRequest.h"

@interface XMPPRequestWebClientSendThumbnailPreview : _XMPPWebClientRequest
{
}

- (id)initWithPictureID:(id)arg1 picture:(id)arg2 requestID:(id)arg3 forWebSession:(id)arg4 completion:(CDUnknownBlockType)arg5;

@end

