//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface XMPPContact : NSObject
{
    BOOL _whatsAppContact;
    NSString *_number;
    NSString *_jid;
}

@property(nonatomic, getter=isWhatsAppContact) BOOL whatsAppContact; // @synthesize whatsAppContact=_whatsAppContact;
@property(copy, nonatomic) NSString *jid; // @synthesize jid=_jid;
@property(copy, nonatomic) NSString *number; // @synthesize number=_number;
- (void).cxx_destruct;
- (id)description;

@end

